### ISSUE TITLE
BreadcrumbBar sample lacking context and navigation

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/WinUI-Gallery#1000]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] New sample
- [ ] Addition to existing sample
- [x] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**
BreadcrumbBar

**Describe the sample**
The current `BreadcrumbBar` sample is fairly lacking in details. There are two examples. In the first, all it shows for 'source code' is XAML without the data to drive it (the list of strings here):

https://github.com/microsoft/WinUI-Gallery/blob/55af91f5993029d073ef5129bbc07b7b908c2ebe/WinUIGallery/ControlPages/BreadcrumbBarPage.xaml.cs#L13

Then the second example at least shows how to work with a custom data type, but then doesn't show how to maintain the same click behavior in order to navigate when a custom item is clicked from the template.

(I've also noticed this with NavigationViewItem, but it seems odd to have to create the container as part of the DataTemplate as done here in the 2nd example as well. Usually things like `DisplayMemberPath` were how these things connected in WPF, so I feel like these two controls are trying to warp a known pattern?)

**Is your sample request related to a problem? Please describe it**
Hard to understand how BreadcrumbBar works and can be used in an application to provide contextual navigation with custom data objects.

**Additional context**

**Comment by michael-hawker** [comment]
Also just noticed that the last item in the list isn't clickable by default, showing how to make that clickable would be useful to.

**Comment by chingucoding** [comment]
@gregwoo-microsoft I think we should show the necessary C# sample code too here.
