### ISSUE TITLE
Theme brushes guidance / Icons / Design library section

### ISSUE THREAD

**Issue by gregwoo-microsoft** [microsoft/WinUI-Gallery#1019]
### Issue type

sample request

### Which version of the app?

WinUI 3 Gallery

### Description

Provide a page with all of the recommended design colors/guidance.

**Comment by niels9001** [comment]
During a recent hackathon, I have been playing around with some sort of companion experience for developers to make it easier for them to look up certain things, like typeramps and colors.

The one thing that I think is really nice about the Windows Visual Library is the fact that it provides descriptions on when to use what brushes, and even some examples. I copied that principle as you can see below:

![WinUIGallery](https://user-images.githubusercontent.com/9866362/195870065-b5d1230e-8e2a-46ab-aacf-85915f2414e8.gif)

Would love to see something similar in the WinUI Gallery :)! cc @chingucoding @gregwoo-microsoft

**Comment by gregwoo-microsoft** [comment]
This is amazing @niels9001 ! Let's sync together to merge our efforts. We are currently in the process of creating a new Design Guidance section in the Gallery.
