### ISSUE TITLE
Switching to NavigationView page will make all CheckBoxes rounded in WinUI 2 Gallery

### ISSUE THREAD

**Issue by GetGet99** [microsoft/WinUI-Gallery#1029]
### Which version of the app?

WinUI 2 Gallery

### Description

Switching to NavigationView page will make all CheckBoxes in the WinUI 2 app rounded until you reopen the app.

Steps to reproduce:
1. Open WinUI 2 Gallery
2. Go to the CheckBox page (You should see the normal checkbox appearance)
3. Go to the NavigationView page
4. Go to the CheckBox page (You should see the rounded checkbox appearance)
5. You can go to any other page containing CheckBox and they will be rounded

### Screenshots

![image](https://user-images.githubusercontent.com/41405393/174432878-201680b6-7669-45f9-887d-090cb3adf01e.png)

![image](https://user-images.githubusercontent.com/41405393/174432860-c47b8f80-7c59-4255-bffa-bc3dfa32a274.png)

![image](https://user-images.githubusercontent.com/41405393/174432838-1079a992-bfdc-48ea-a435-af04c3f5e891.png)

### Windows version

Insider Build (xxxxx)

### Additional context

WinUI 3 Gallery does not have this issue.

**Comment by karkarl** [comment]
Unable to repro - closing.
