### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by christiannagel** [microsoft/WinUI-Gallery#1030]
### Which version of the app?

WinUI 3 Gallery

### Description

The WinUI 3 documentation moved to a new home, thus all the documentation links are broken now, e.g.
ListBox contains these links with a 404 result:

* [ListBox - API](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.listbox)
* [ListBoxItem - API](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.listboxitem)

The new links:
* https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.listbox
* https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.listboxitem

Relates to: https://github.com/MicrosoftDocs/winrt-api/issues/2240 - maybe redirects from the old links could be done.

### Windows version

Windows 11 21H2 (22000)

**Comment by gregwoo-microsoft** [comment]
We just released a new update to the Store (1.3.15) which fixes that issue :)
