### ISSUE TITLE
ProgressRing code sample does not work

### ISSUE THREAD

**Issue by NagiaME** [microsoft/WinUI-Gallery#1033]
### Which version of the app?

WinUI 3 Gallery

### Description

The simplest sample provided in WinUIGallery/ControlPages/ProgressRingPage.xaml does not work and will break the app. But using the x:Bind on IsActive property is working well. It's maybe a bug of the SDK. I've no idea about that.

### Screenshots

![image](https://user-images.githubusercontent.com/11983319/174772514-6f67b870-702f-489d-a550-383c63b845ba.png)
![image](https://user-images.githubusercontent.com/11983319/174773731-1f781a35-4d2b-4885-b49b-7c2b00839f64.png)

### Windows version

Windows 11 21H2 (22000)

### Additional context

The app breaks so suddenly that cannot see the error detail in the Diagnostic window.

**Comment by chingucoding** [comment]
@NagiaME are you still able to reproduce this issue? Unfortunately (or luckily) this does not crash the app for me.

**Comment by Jay-o-Way** [comment]
Is this still an issue with the latest version?
