### ISSUE TITLE
Use the same minimum window size as WinUI 2 Gallery

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/WinUI-Gallery#1038]
### Issue type

enhancement

### Which version of the app?

WinUI 3 Gallery

### Description

consistency is gud

### Windows version

November 2021 Update/21H2 (19044)

**Comment by Jay-o-Way** [comment]
What's the global size that Microsoft uses? 500-by-something?

**Comment by niels9001** [comment]
![Image](https://github.com/user-attachments/assets/61474ead-eff6-4a57-8c30-fe403bbefe48)

I think this issue has been resolved with setting the min size a while back? We are using 500 for WinUI 2 Gallery

![Image](https://github.com/user-attachments/assets/0be03871-803d-4e9d-8304-dda8f091d186)

**Comment by Jay-o-Way** [comment]
@niels9001 I'm sure that second screenshot is not relevant to this issue 😉
