### ISSUE TITLE
”SystemBackdropsSample1“punctuation error

### ISSUE THREAD

**Issue by MrJone2457** [microsoft/WinUI-Gallery#1041]
### Which version of the app?

WinUI 3 Gallery

### Description

```
private void SetConfigurationSourceTheme();
{
    switch (((FrameworkElement)this.Content).ActualTheme)
    {
        case ElementTheme.Dark:    m_configurationSource.Theme = Microsoft.UI.Composition.SystemBackdrops.SystemBackdropTheme.Dark; break;
        case ElementTheme.Light:   m_configurationSource.Theme = Microsoft.UI.Composition.SystemBackdrops.SystemBackdropTheme.Light; break;
        case ElementTheme.Default: m_configurationSource.Theme = Microsoft.UI.Composition.SystemBackdrops.SystemBackdropTheme.Default; break;
    }
}
```
private void SetConfigurationSourceTheme()
There should be no ";" after this statement.

### Screenshots

![image](https://user-images.githubusercontent.com/29790257/177028112-d0e54a3b-9eea-46b5-8492-a15fd0f71973.png)

### Windows version

Windows 11 21H2 (22000)

**Comment by chingucoding** [comment]
Thank you for filing this issue @MrJone2457! Would you like to create a PR for this? The file you need to modify would be the [this one](https://github.com/microsoft/WinUI-Gallery/blob/main/WinUIGallery/ControlPagesSampleCode/SystemBackdrops/SystemBackdropsSample1.txt).

**Comment by MrJone2457** [comment]
> Thank you for filing this issue @MrJone2457! Would you like to create a PR for this? The file you need to modify would be the [this one](https://github.com/microsoft/WinUI-Gallery/blob/main/WinUIGallery/ControlPagesSampleCode/SystemBackdrops/SystemBackdropsSample1.txt).

sorry i don't know how to do this yet
