### ISSUE TITLE
Win UI Nuget error

### ISSUE THREAD

**Issue by yusuf8421** [microsoft/WinUI-Gallery#1053]
### Which version of the app?

WinUI 3 Gallery

### Description

Hi everyone
I downloaded Microsoft's winui3 package, but when I compile the project, I get the following error.
Cannot resolve metadata for WinUI types. Please ensure that Nuget Restore was successful

**Comment by gregwoo-microsoft** [comment]
Thanks for filing this @yusuf8421. Were you able to fix it using Nuget Restore?

**Comment by yusuf8421** [comment]
Yes fixed my project.Was created .net 4.8 framework when I was created new one with .net6 than I did not encounter any errors

**Comment by gregwoo-microsoft** [comment]
Ok great I'm glad to hear that. I'm going to close the issue now. Feel free to create another issue if you encounter any bug.
