### ISSUE TITLE
NavigationView design changes?

### ISSUE THREAD

**Issue by MajorXAML** [microsoft/WinUI-Gallery#1060]
### Which version of the app?

WinUI 3 Gallery

### Description

Hello

I noticed that NavigationView in WinUI-Gallery 3 is different from the version presented in Windows UI Toolkit (figma)

So I was wondering, is it the WinUI team made changes in the NavigationView and forgot to update the Toolkit or it is a feature of WinUI-Gallery 3 only?

### Screenshots

Pay attention to the lack of rounded border & shadow in WinUI-Gallery 3 version 
![nav](https://user-images.githubusercontent.com/93913816/183406006-4591c2bd-4f54-4592-8ead-74939029603a.PNG)

### Windows version

November 2021 Update/21H2 (19044)

**Comment by niels9001** [comment]
@MajorXAML Not able to replicate in the latest version of the Gallery? (Except for the shadow being less dense). Even then, this might be more of a WinUI issue vs. a WinUI-Gallery issue as we're using the default styles :).
