### ISSUE TITLE
WinUI Gallery Icons

### ISSUE THREAD

**Issue by Pdawg-bytes** [microsoft/WinUI-Gallery#1062]
### Issue type

enhancement

### Which version of the app?

WinUI 3 Gallery

### Description

Hey! I've installed both WinUI 2 Gallery and WinUI 3 Gallery. They are great apps, expect for one thing. The icons. They are both exactly the same, and when they're on my taskbar, I have no idea what app is what. Please just change an icon for one of the versions, it's just a small quality of life update!

### Screenshots

![image](https://user-images.githubusercontent.com/83825746/183552286-ed5095e8-3d97-4fdd-b6e8-6baabd1251b2.png)

### Windows version

Windows 11

**Comment by gregwoo-microsoft** [comment]
Thank you @Pdawg-bytes for the suggestion. We are actively looking into modernizing the icons. Stay tuned ;)

**Comment by Pdawg-bytes** [comment]
> Thank you @Pdawg-bytes for the suggestion. We are actively looking into modernizing the icons. Stay tuned ;)

Awesome! Can't wait to see the new icon. Hopefully it'll save a lot of developers some confusion.

**Comment by Pdawg-bytes** [comment]
Hey! Any updates on this? The icons still haven't changed, it's been more than 6 months now :(

**Comment by gregwoo-microsoft** [comment]
@Pdawg-bytes thanks for being so patient. Our designers created a new icon and we're currently going through the last round of the approval process. It will be released within the next couple of weeks.

**Comment by Pdawg-bytes** [comment]
Wow, awesome! Thank you for the quick response, can't wait to see it.

**Comment by Pdawg-bytes** [comment]
You guys did it! Saw the mention on the community call. Thanks a lot! Happy developing, everyone.

**Comment by gregwoo-microsoft** [comment]
Thank you @Pdawg-bytes! I'm really excited about this update. Please let me know what you think of it, I'd love to hear your feedback.
