### ISSUE TITLE
Bug title

### ISSUE THREAD

**Issue by Jeremy-Knudsen** [microsoft/WinUI-Gallery#1063]
### Which version of the app?

WinUI 3 Gallery

### Description

1, Touch and hold the toggle switch (pressed state appears)
2. Drag your finger off of the control and release outside of the toggle switch (toggle switch stops tracking to the finger during drag off of the control, and the pressed state gets stuck in an "in-between" state)

RESULT: Pressed (touch down) state stays visible and so you can get the Toggle Switch visually stuck in a middle state. This feels clunky.

EXPECTED: Toggle Switch will track with the finger even if the finger has dragged off the control while the touch is still down (pressed) and the Toggle Switch is either visually on or off and does not get stuck in an "in-between" state.

### Screenshots

<img width="377" alt="image" src="https://user-images.githubusercontent.com/11559173/186030071-2745e0e2-4938-45bb-94fc-c91457d38a44.png">

<img width="431" alt="image" src="https://user-images.githubusercontent.com/11559173/186030143-a5f49df4-e019-4c15-bbeb-a00cb41248d0.png">

**Comment by chingucoding** [comment]
This seems to be an issue with WinUI 3 rather then the gallery; issues around WinUI 3 are better suited on their [GitHub repo](https://github.com/microsoft/microsoft-ui-xaml).
