### ISSUE TITLE
Use Mica in WinUI 3 Gallery Main Window

### ISSUE THREAD

**Issue by MSEDGE-CORE** [microsoft/WinUI-Gallery#1066]
There's no Mica or Acrylic on WinUI3Gallery while WinUI3 supports them;
The window size resets when launch.

[Video]https://1drv.ms/u/s!AtEykNVQgVMNk2GXCXhow5UpauaK?e=4jQchr

**Comment by chingucoding** [comment]
Regarding the window size reset upon launch, this is currently not entirely supported as of WinUI 3 (https://github.com/microsoft/microsoft-ui-xaml/issues/2680). Regarding the Mica/Acrylic, can you elaborate what exactly is the issue? The video seems to show Acrylic and Mica just fine.

**Comment by MSEDGE-CORE** [comment]
> Regarding the window size reset upon launch, this is currently not entirely supported as of WinUI 3 ([microsoft/microsoft-ui-xaml#2680](https://github.com/microsoft/microsoft-ui-xaml/issues/2680)). Regarding the Mica/Acrylic, can you elaborate what exactly is the issue? The video seems to show Acrylic and Mica just fine.

In the video, there's no Mica in the Gallery main window

**Comment by chingucoding** [comment]
Ah I see what you mean, thanks for the clarification. @gregwoo-microsoft and @karenbtlai , should we update the app to have Mica as background material?

**Comment by l619534951** [comment]
> Ah I see what you mean, thanks for the clarification. @gregwoo-microsoft and @karenbtlai , should we update the app to have Mica as background material?

Mica background  is  awesome. Settings、Task Manager、Caculator、File Explorer and Microfost Store have already used mica.

**Comment by Jay-o-Way** [comment]
@gregwoo-microsoft and @karenbtlai please say yes :)

**Comment by Jay-o-Way** [comment]
https://github.com/microsoft/microsoft-ui-xaml/pull/8139

**Comment by karenbtlai** [comment]
> @gregwoo-microsoft and @karenbtlai please say yes :)

For sure, this feature will be a long time coming. Let's add this to feature to the projects backlog. @Jay-o-Way are you interested in picking this up?

**Comment by Jay-o-Way** [comment]
I love to help but I'm not familiar enough with this yet. @niels9001 said in the above-mentioned pr that there's an easy way just in a pre-release

**Comment by niels9001** [comment]
@karenbtlai @Jay-o-Way Adding Mica is the easy part 😊 - handling in-app theme switching (in the Gallery settings) is something that might be trickier, see: https://github.com/microsoft/microsoft-ui-xaml/issues/8249

I guess the only way to do this is restart the app?

**Comment by l619534951** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/8249 This problem seems to have appeared very early, my solution is set the ThemeResource background to window.Content

contract13Present (windows 11)
contractNot13Present (windows 10)
```xaml
xmlns:contract13Present="http://schemas.microsoft.com/winfx/2006/xaml/presentation?IsApiContractPresent(Windows.Foundation.UniversalApiContract,13)"
xmlns:contractNot13Present="http://schemas.microsoft.com/winfx/2006/xaml/presentation?IsApiContractNotPresent(Windows.Foundation.UniversalApiContract,13)"
```

Grid is root element of window.Content
`LayerOnMicaBaseAltFillColorTransparent`  is Transparent, so we can see mica effect in windows 11.(mica is only supported in windows 11)
```xaml
<Grid contract13Present:Background="{ThemeResource LayerOnMicaBaseAltFillColorTransparent}" contractNot13Present:Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
```

in the code
```
backdropHelper.SetMicaBackdrop()
```
This will avoid that problem, Hope this is useful to you。
[App1.zip](https://github.com/microsoft/WinUI-Gallery/files/11200935/App1.zip)

**Comment by Jay-o-Way** [comment]
@karkarl I don't see a pr linked to this?
https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.media.micabackdrop shows a very simple XAML solution. Sounds like this should be an easy fix, now. (right?)
