### ISSUE TITLE
ContentDialog example using XAML

### ISSUE THREAD

**Issue by EddieLotter** [microsoft/WinUI-Gallery#1069]
### Issue type

sample request

### Which version of the app?

WinUI 3 Gallery

### Description

There used to be an example of using a ContentDialog defined with XAML.
Now there is only one example that creates a ContentDialog entirely in code.
Please add back the ContentDialog XAML example. It is instructive and important for people to see that it can be done.

### Windows version

Windows 11 22H2 (22621)

**Comment by Jay-o-Way** [comment]
Version 1.3.15 has some XAML:
```xaml
<Page
    x:Class="AppUIBasics.ControlPages.ContentDialogContent"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

    <StackPanel VerticalAlignment="Stretch" HorizontalAlignment="Stretch">
        <!-- Content body -->
        <TextBlock Text="Lorem ipsum dolor sit amet, adipisicing elit." TextWrapping="Wrap" />
        <CheckBox Content="Upload your content to the cloud."/>
    </StackPanel>

</Page>
```
Does that suffice?

**Comment by EddieLotter** [comment]
Close. :) See: [https://github.com/microsoft/WinUI-Gallery/blob/main/WinUIGallery/ControlPages/ContentDialogExample.xaml](https://github.com/microsoft/WinUI-Gallery/blob/main/WinUIGallery/ControlPages/ContentDialogExample.xaml)
