### ISSUE TITLE
Title is the same when window is active and inactive

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/WinUI-Gallery#108]
**Describe the bug**

The title of the app stays the same when inactive

**Steps to reproduce the bug**

1. Open XAML Controls Gallery
2. Click on an empty spot in the taskbar

**Expected behavior**

Title would be a lighter grey with the light theme

**Actual behavior**

Title is the same colour. 

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 

1.2.8.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by chingucoding** [comment]
I agree, that for some apps this a desired behaviour, however if you look at apps that manage the border themself, for example Outlook, Visual Studio, VS Code or Spotify, you will notice that none of them behave that way. 
All of those app preserve the colors even when they are not focused. 
The question now is if XLC should change it or not, however I think that it is not unusal for an app to behave that way and not change the color of the title.

**Comment by Poopooracoocoo** [comment]
>I think that it is not unusal for an app to behave that way and not change the color of the title.

@chingucoding @stmoy When is that ever a desired behaviour???

Oh and the title bar caption buttons are invisible! White on a white title bar.

**Comment by gregwoo-microsoft** [comment]
I'll close this as it no longer applies to the current version of the XCG.

**Comment by Poopooracoocoo** [comment]
@gregwoo-microsoft I'm still seeing this issue.

**Comment by gregwoo-microsoft** [comment]
Could you please post a screenshot? :)

**Comment by Poopooracoocoo** [comment]
https://user-images.githubusercontent.com/51363864/148634372-c7ee1c52-6c1b-4644-a290-3d07a9d89108.mp4

**Comment by gregwoo-microsoft** [comment]
This seems to only occur in Windows 10. I can't repro this in Windows 11.

https://user-images.githubusercontent.com/90726278/149015882-446bb262-dc5a-4414-802e-a4cfde4ff06a.mp4

**Comment by Poopooracoocoo** [comment]
I can still see the bug in your video... @gregwoo-microsoft

**Comment by gregwoo-microsoft** [comment]
My bad, I had misunderstood your issue as "Title bar" not the actual title itself. You are right, the title does not currently change when the XCG is inactive. What I meant to say with the video was that there is an active/inactive difference with the top right buttons of the window (light grey when inactive and darker grey when active).

Thanks for filing this issue @poopooracoocoo, I'll reopen it now. Please keep in mind though that this is not a top priority right now.

**Comment by Poopooracoocoo** [comment]
You're referring to #653 which relates to the caption buttons.

**Comment by gregwoo-microsoft** [comment]
Thanks! I've closed #653 but I'll leave this one open since I can repro it.

**Comment by niels9001** [comment]
This was fixed in #1293
