### ISSUE TITLE
WebView2 Source Code Not Visible in WinUI 3 Gallery

### ISSUE THREAD

**Issue by Ritvik-UX** [microsoft/WinUI-Gallery#1084]
### Which version of the app?

WinUI 3 Gallery

### Description

Source Code for WebView2 is Missing in WinUI 3 Gallery.

Step 1: Open WinUI 3 Gallery.
Step 2: Search for "WebView2".
Step 3: Expand the Source Code Section.

### Screenshots

![webview2 winui 3 gallery - source code missing](https://user-images.githubusercontent.com/73193822/193478249-a80d8f24-92fc-4e6d-a123-0839a8f550a6.png)

### Windows version

Windows 11 22H2 (22621)

**Comment by gregwoo-microsoft** [comment]
Thanks for filing this issue @Ritvik-UX. I am able to repro this bug. I will look into this.
