### ISSUE TITLE
WebView2 Sometimes Rendering some HTML after refreshing page using F5 key

### ISSUE THREAD

**Issue by ritvikos** [microsoft/WinUI-Gallery#1085]
### Which version of the app?

WinUI 3 Gallery

### Description

Sometimes WebView is rendering some HTML randomly after refreshing page by pressing F5 key.

Step 1: Open WinUI 3 Gallery.
Step 2: Search for "WebView2".
Step 3: Click any element in the WebView Window and press the "F5" key 3-5 times and some HTML will be rendered randomly.

Video Here ([https://webm.red/view/5xj8.webm](https://webm.red/view/5xj8.webm)) 
(Video deletes automatically after 90 day inactivity)

### Screenshots

![winui rendering html randomly 1](https://user-images.githubusercontent.com/73193822/193479355-b452d962-9b94-4dd7-b22d-24cbee6eb909.png)
![winui rendering html randomly 2](https://user-images.githubusercontent.com/73193822/193479359-c3151219-21eb-483d-a658-7a5b39b6cc9f.png)
![winui rendering html randomly 3](https://user-images.githubusercontent.com/73193822/193479365-f4128ce0-c3bf-438b-adb8-740d472909ab.png)

### Windows version

Windows 11 22H2 (22621)

**Comment by chingucoding** [comment]
I'm inclined to say this is an issue with WebView2 not correctly loading the CSS file of the website. A similar behavior can also be seen when throttling your browser to fast or slow 3G and opening the website except that the menu disappears after a few seconds once the CSS has loaded. @bpulliam What do you think?

**Comment by karkarl** [comment]
Closing as I'm unable to repro this issue.
