### ISSUE TITLE
Maybe A Easy Sample For Tabs In title bar

### ISSUE THREAD

**Issue by jarno9981** [microsoft/WinUI-Gallery#1089]
### Issue type

sample request

### Which version of the app?

WinUI 3 Gallery

### Description

saw the docs but no clear indication how to make tabs in titlebar can you make a separate sample for this so the code is more clear

### Screenshots

![samplecodeanything](https://user-images.githubusercontent.com/53493418/193769131-2c6c423b-58c9-4faa-a0b8-6011d9553a40.png)

where is sample project for this

### Windows version

Windows 11 22H2 (22621)

**Comment by jarno9981** [comment]
![make this work](https://user-images.githubusercontent.com/53493418/193770261-b67babd5-be37-44e5-859e-8a705285c4d2.png)
make this code work in a new project

**Comment by jarno9981** [comment]
Any update here @....

**Comment by karkarl** [comment]
There's work on WASDK side to simplify this scenario from an implementation perspective. Will update the sample accordingly when that's public.

**Comment by jarno9981** [comment]
I fixed it with my app have working blank sample available
