### ISSUE TITLE
Navigation style Top does not work correct

### ISSUE THREAD

**Issue by jbe2277** [microsoft/WinUI-Gallery#1099]
WinUI 3 Gallery Version: 1.3.15.0
Windows 10 21H2 (19044)

![image](https://user-images.githubusercontent.com/10452896/194726346-fcc993c3-d352-4bf0-8b0c-6c4a0fd951f1.png)

## How to reproduce
- Settings > Navigation Style: select Top
- Try to select "Home" or "All controls" by clicking in the middle of the navigation button -> no reaction

## Result
The navigation bar is shown but it does not react on mouse interaction (e.g. click). It seems that the Windows title bar takes the mouse clicks and does not forward it to the navigation bar.

**Comment by chingucoding** [comment]
Hi @jbe2277, can you confirm that this is the same issue as #1065? #1065 was fixed recently but hasn't been published to the store yet as far as I know.

**Comment by jbe2277** [comment]
Yes, #1065 seems to be the same issue as this one.

**Comment by bpulliam** [comment]
Closing as duplicate
