### ISSUE TITLE
PasswordBox reveal button disappears

### ISSUE THREAD

**Issue by MortezaGholami-2** [microsoft/WinUI-Gallery#1100]
### Which version of the app?

WinUI 3 Gallery

### Description

When I type some password in **PasswordBox** of "**WinUI 3 Gallery app**", it shows a button for showing the password and it works perfectly. But when I go to another control and get back to **PasswordBox** it doesn't show the reveal button again.

### Screenshots

![2022-10-15 (1)](https://user-images.githubusercontent.com/57088744/195967666-a6637974-ae32-482f-b6af-750fe6de6090.png)
![2022-10-15](https://user-images.githubusercontent.com/57088744/195967699-c5b7f6c3-c5e5-4e15-bab1-311bfb11d9fd.png)

### Windows version

Windows 11 21H2 (22000)

**Comment by chingucoding** [comment]
This is not a bug with the WinUI Gallery or the PasswordBox control but rather by design. See https://github.com/microsoft/microsoft-ui-xaml/issues/1224 for more context.
