### ISSUE TITLE
ComboBox Blue Selector ThemeResource

### ISSUE THREAD

**Issue by mani009** [microsoft/WinUI-Gallery#1104]
### Issue type

sample request

### Which version of the app?

WinUI 2 Gallery

### Description

Hello everbody,

it would be great to change the color of the combobox selected item(color at the moment blue).
Preferably with an ThemeResource would be great.

### Screenshots

![ChangeSelectedItem](https://user-images.githubusercontent.com/13287806/196617463-0d8b2572-aafd-47a5-9a20-7ff164a9df55.jpg)

### Windows version

November 2021 Update/21H2 (19044)

**Comment by karkarl** [comment]
This is related to #1388 to include available themeresources for lightweight styling.
