### ISSUE TITLE
C++ implementation for ListBox itemSources

### ISSUE THREAD

**Issue by alexlozdev** [microsoft/WinUI-Gallery#1110]
### Issue type

sample request

### Which version of the app?

WinUI 3 Gallery

### Description

https://stackoverflow.com/questions/74260243/winui3-c-listbox-itemssource

**Comment by bpulliam** [comment]
The application is currently set up for C# and Xaml code samples only. Adding c++ would be a new feature.

**Comment by wsfrancis71** [comment]
When can we expect a C++ version?

**Comment by bpulliam** [comment]
We currently don't have C++ samples anywhere in the app. At that point, it would be worth discussing a full C++ version of the app.  That is not in scope at this time.
