### ISSUE TITLE
Viewbox control is missing in WinUI gallery but present in docs and links

### ISSUE THREAD

**Issue by pratikone** [microsoft/WinUI-Gallery#1111]
### Which version of the app?

WinUI 3 Gallery

### Description

The MSDN docs for Viewbox shows a control demo for it is present in WinUI gallery but that doesn't seem to be the case. 
https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.Viewbox?view=windows-app-sdk-1.1

Searching for viewbox in search bar doesn't yield any results.
However, if you come across any page like to it like here then you can navigate to its page. 
The page still appears to be blank with only description and no demo.

### Screenshots

![image](https://user-images.githubusercontent.com/115935/199359137-ac11f3da-7eb2-4e97-8ce4-31e5630ecb2f.png)

![image](https://user-images.githubusercontent.com/115935/199359250-9bc04f9b-bf38-4c46-bf53-bb2032cead66.png)

### Windows version

Insider Build (xxxxx)

**Comment by chingucoding** [comment]
@bpulliam Do you happen to know why this page is present in the WinUI 2 gallery but not in the WinUI 3 gallery?

**Comment by bpulliam** [comment]
Fixed with #1207
