### ISSUE TITLE
How to obtain the business logic for processing in an event when a treelist selects an item? I can't see any demos

### ISSUE THREAD

**Issue by git102347501** [microsoft/WinUI-Gallery#1122]
### Issue type

enhancement

### Which version of the app?

WinUI 3 Gallery

### Description

Select the project node of treelist

Get the selected event and process the business logic

### Windows version

Windows 11 22H2 (22621)

**Comment by chingucoding** [comment]
Can you elaborate what you mean by business logic in that context? Do you mean in C#
