### ISSUE TITLE
MediaPlayerElement's audio keep playing after navigating to another page

### ISSUE THREAD

**Issue by roxk** [microsoft/WinUI-Gallery#1123]
### Which version of the app?

WinUI 3 Gallery

### Description

As titled.

### Screenshots

1. Navigate to MediaPlayerElement page
2. After the auto-played video plays (can you add a control to allow stopping there? It's annoying there is no way to stop it), navigate to any other page
3. Observe the audio is still playing

### Windows version

Insider Build (xxxxx)

### Additional context

Build: 22623.891

*Note*: I'm not sure if its only the audio but it seems like the whole media player is not released/stopped.

*Note2*: If you rapidly switch between `MediaPlayerElement` page and other pages, the gallery crashes. This is not acceptable for a showcase of WinUI 3. The app seems to lack even the most basic test.

**Comment by Jaiganeshkumaran** [comment]
Probably related to microsoft/microsoft-ui-xaml/issues/6561.

**Comment by chingucoding** [comment]
Was fixed with #1338
