### ISSUE TITLE
Update Settings page

### ISSUE THREAD

**Issue by niels9001** [microsoft/WinUI-Gallery#1125]
### Issue type

enhancement

### Which version of the app?

WinUI 3 Gallery

### Rationale
We want the WinUI Gallery to be a showcase of the Windows 11 design language. W11 Settings and most of the inbox applications moved to a new cards based system.

### Proposal
Use the SettingsCard and SettingsExpander (from Community Labs) and update the UI. Should be an easy tweak :).

https://devblogs.microsoft.com/ifdef-windows/windows-community-toolkit-labs-experiments-are-here/#settingscard-and-settingsexpander

![image](https://user-images.githubusercontent.com/9866362/202703996-e73876d8-8344-464a-b225-3b56db588a40.png)

**Comment by chingucoding** [comment]
@gregwoo-microsoft @bpulliam Do we want to add a depdendency for this, especially in case we might want to use more from the labs?

**Comment by gregwoo-microsoft** [comment]
Thanks for pointing it out @niels9001. I think that this is a great idea + sets the path to have more integration w/ the labs. @chingucoding any thoughts?

**Comment by chingucoding** [comment]
I think thats fine. if we achieve even greater design with this, sure lets do that!

**Comment by ShakedGold** [comment]
> @chingucoding @bpulliam
> 
> When adding the Toolkit Labs package I get the following error when running WinUIGallery.DesktopWap.Package:
> 
> ![image](https://user-images.githubusercontent.com/9866362/204587464-9241c60e-e991-4e72-8dc6-1cb367de85d4.png)
> 
> Call stack: ![image](https://user-images.githubusercontent.com/9866362/204587589-19fefa2e-3db0-49a6-8987-3f08cbe2168f.png)
> 
> Any idea what's going on?

Hi I looked into my packages in .nuget (C:\Users\USERNAME\.nuget\packages\microsoft.ui.xaml), and there were 2 version, when I deleted the older one It worked for me

**Comment by niels9001** [comment]
@ShakedGold That didn't work for me 😣.. We were able to reproduce this though, and are tracking the issue in our repo: https://github.com/CommunityToolkit/Labs-Windows/issues/262#issuecomment-1377678778

**Comment by niels9001** [comment]
Related: https://github.com/microsoft/WinUI-Gallery/issues/834
