### ISSUE TITLE
Cannot find resource key DefaultContentDialogStyle.' in contentDialog.

### ISSUE THREAD

**Issue by BBerndog** [microsoft/WinUI-Gallery#1126]
### Which version of the app?

WinUI 3 Gallery

### Description

Copied this code directly from WinUI 3 Gallery on a button click and get the following error:

Cannot find a resource with the given key: DefaultContentDialogStyle.'

This is for a UWP app with the latest insider build of Windows with the latest version of Visual Studio Community.

### Screenshots

![image](https://user-images.githubusercontent.com/23566647/202909271-3c89f855-d169-420b-9c82-4ad7d0faa145.png)

### Windows version

Insider Build (xxxxx)

**Comment by chingucoding** [comment]
Which version of WinUI are you using in your app?

**Comment by niels9001** [comment]
@bberndog the `DefaultContentDialogStyle` is part of WinUI - so make sure, after creating your UWP app, you add WinUI 2.7 to it. Getting started steps here: https://learn.microsoft.com/en-us/windows/apps/winui/winui2/getting-started

Link to the `DefaultContentDialogStyle`: https://github.com/microsoft/microsoft-ui-xaml/blob/4cbade6959cda4fca42a299fb540adc2f99c1e8a/dev/CommonStyles/ContentDialog_themeresources.xaml#L69
