### ISSUE TITLE
NavigationView ShoulderNavigationEnabled doesn't work

### ISSUE THREAD

**Issue by AlexRUiLs** [microsoft/WinUI-Gallery#1127]
I am trying to enable ShoulderNavigationEnabled in my UWP app but it doesn't work as expected.
According to the description, bumpers should navigate on the top menu but it doesn't.
In the WinUI 2 Gallery bumpers don't work as well. In WinUI 3 Gallery the gamepad doesn't work at all.

Please assist to make bumpers navigation work in my app.

**Comment by chingucoding** [comment]
If you still require assistance with shoulder navigation, feel free to create an issue on the WinUI repository: https://github.com/microsoft/microsoft-ui-xaml
