### ISSUE TITLE
WinUI 3 gallary icon-font display issue in Win10

### ISSUE THREAD

**Issue by yangbo** [microsoft/WinUI-Gallery#1128]
Win UI3 gallary icon-font display issue in Win10 in Chinese Language settings.
![image](https://user-images.githubusercontent.com/23898/204076571-ceb750e1-bdac-4a5b-9fae-e7de30ac32dd.png)

**Comment by niels9001** [comment]
Related to: https://github.com/microsoft/microsoft-ui-xaml/issues/7850#issuecomment-1334842932

Seems that legacy icon glyphs are used - (everything under E6, according to the docs: https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font#icon-list)

**Comment by yangbo** [comment]
Thanks, that is useful, I will try to install the new font.
