### ISSUE TITLE
Throw an exception when right clicked the code block.

### ISSUE THREAD

**Issue by AW23304** [microsoft/WinUI-Gallery#1129]
### Which version of the app?

WinUI 3 Gallery

### Description

I accidentally right-clicked the code block and the app throw an exception🤣.

### Screenshots

![image](https://user-images.githubusercontent.com/92253239/204149938-2117d32a-c39b-4ba8-8bee-5ed22041dfaa.png)

### Windows version

Windows 11 22H2 (22621)

**Comment by Jay-o-Way** [comment]
Is this still an issue?

**Comment by AW23304** [comment]
I believe it has been fixed after the Windows SDK updated .
