### ISSUE TITLE
SelectedItem incorrectly mentioned where InvokedItem should be

### ISSUE THREAD

**Issue by eduardobragaxz** [microsoft/WinUI-Gallery#1143]
### Which version of the app?

WinUI 3 Gallery

### Description

In the C# code of the section  "Tying selection and focus - Tabs" in the NavigationView page "args.SelectedItem" is used instead of "args.InvokedItem".

Additionally, the section's introductory text tells you to set SelectionFollowsFocus to "True" but the options are "Enabled" and "Disabled".

### Screenshots

![wrong](https://user-images.githubusercontent.com/50815710/209009171-cb216f98-b289-4621-b02b-c5099d386bd7.png)

**Comment by chingucoding** [comment]
Thank you for creating this issue @eduardobragaxz ! Would you like to create a PR to fix this? If not that's totally fine too.

**Comment by eduardobragaxz** [comment]
> Thank you for creating this issue @eduardobragaxz ! Would you like to create a PR to fix this? If not that's totally fine too.

I completely forgot about this, my bad.

**Comment by gregwoo-microsoft** [comment]
No worries! I made the PR :) Thanks for filing this issue @eduardobragaxz
