### ISSUE TITLE
Connected Animation Missing Source code

### ISSUE THREAD

**Issue by A1steaksa** [microsoft/WinUI-Gallery#1145]
### Which version of the app?

WinUI 3 Gallery

### Description

The `Motion>Connected` Animation page does not have source code available for the first two examples.  Only the final example has source code attached.

### Screenshots

![image](https://user-images.githubusercontent.com/8369707/209367362-a0a93f57-0a3f-4034-875b-7b86c6c90ac6.png)
![image](https://user-images.githubusercontent.com/8369707/209367381-e28ec0da-0c5d-4c47-ad6c-dc0c62dd69bd.png)

**Comment by gregwoo-microsoft** [comment]
Thank you for filing this issue @A1steaksa. I created a PR to fix this.
