### ISSUE TITLE
WinUI 3 TreeView IsSelected is not persistent when collapsing/expanding tree

### ISSUE THREAD

**Issue by rcohn** [microsoft/WinUI-Gallery#1153]
### Describe the bug

Hello -

I am building a WinUI 3 app using TreeView. One of the simplest things that appears not to be working correctly is that a selected TreeViewItem does not stay selected when collapsing the node containing that item and then re-expanding that node.

For example, I have a simple TreeView with a node containing three children items.  After starting the app, I select any of the children items and then collapse the node using the little expand/collapse chevron.  When I re-expand the node, the item is no longer selected (at least it is no longer visibly selected).  The TreeView does not contain any bound data.

In the above description, all selection is through UI interaction with a mouse.

So, is this a bug or do I have to do something further (such as camp on the TreeView.Expanding event and set the item's IsSelected property)?  BTW - I see the same behavior in the TreeView samples in the WinUI 3 Gallery.

Thanks very much for your help.

Best regards,
Robert Cohn

PS - Please let me know if you would need sample code.

### Steps to reproduce the bug

As per the app description above:

- Click on TreeView node to expand it
- Click on one of the child items contained in the node so that it is selected (showing the little selection bar to the left of the item)
- Click on TreeView node to collapse it
- Click on TreeView node to expand it again
- The child item I clicked on is no longer selected (none of the items are selected for that matter)

### Expected behavior

I would expect the clicked child item to still be selected.

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

I'm using WindowsAppSDK 1.1.4.

**Comment by chingucoding** [comment]
I've just tried the sample for this in the WinUI Gallery and it works as expected. Are you also still able to reproduce with WinApp SDK 1.4?

**Comment by rcohn** [comment]
Hello -

We are currently using Windows App SDK 1.3.230502000.  The bug that I found in 1.1.5 does not seem to exist anymore.

Thank you for following up.
Regards.
