### ISSUE TITLE
Animation Interop Problem

### ISSUE THREAD

**Issue by kadir-ince** [microsoft/WinUI-Gallery#1170]
### Which version of the app?

WinUI 3 Gallery

### Description

Damping ratio & Period combination problem under the Motion > Animation Interop section 
- 25 ms and 0.8 - 0.6 - 0.4 damping ratio
- 50 ms and 0.8 damping ratio 

and same problem has under the following two section (ExpressionAnimation on an Ellipse element - Driving several related animations...) when period is:
- 25 ms and 0.8 - 0.6 - 0.4 damping ratio
- 50 ms and 0.8 damping ratio 

> You must change damping ratio if you can't see problem when 25 ms - 0.6 damping ratio (once click any damping ratio then click 0.6)

 

### Screenshots

https://user-images.githubusercontent.com/52853427/212882857-340481f1-9f4c-491e-8e4f-fbdc9b989a96.mp4

### Windows version

Windows 11 22H2 (22621)

**Comment by chingucoding** [comment]
Thank you for reporting this bug, I'll close this in favor of #1049 to make tracking this bug easier; PR #1375 will fix this issue.
