### ISSUE TITLE
Access violation exception

### ISSUE THREAD

**Issue by GuildOfCalamity** [microsoft/WinUI-Gallery#1183]
### Which version of the app?

WinUI 3 Gallery

### Description

Upon closing the application (after selecting any of the basic input examples) the following unhandled exception is thrown...

`Exception thrown at 0x00007FFFAF8047F8 (threadpoolwinrt.dll) in WinUIGallery.DesktopWap.exe: 0xC0000005: Access violation reading location 0x0000000000000000.`

### Screenshots

![WinUI_Samples](https://user-images.githubusercontent.com/81915293/215298783-ea4d2f93-f208-4eab-b986-5fc421dc00dd.png)

### Windows version

Windows 11 22H2 (22621)

**Comment by karkarl** [comment]
I am not able to repro this issue. Please re-open if the issue is still persisting.

**Comment by GuildOfCalamity** [comment]
@karkarl Were you logged into a domain/network account when you tried this? I've found that most of the issues arise from being logged into a domain account while using WinUI3. e.g. the print dialog works fine from my home computer (no domain login) but crashes when I try it from my work machine (logged into a domain).
