### ISSUE TITLE
Bug title

### ISSUE THREAD

**Issue by Melendez1209** [microsoft/WinUI-Gallery#1187]
### Which version of the app?

WinUI 3 Gallery

### Description

When I call the function with null as an argument, my application title bar is only a small portion of the top right corner, which is clearly not the fallback title bar demonstrated by this repository.

### Screenshots

![image](https://user-images.githubusercontent.com/92637479/217270658-b2ba9c28-0f7d-407d-9209-f1dac736ada6.png)
![image](https://user-images.githubusercontent.com/92637479/217272188-709b426c-31c3-4ec0-b1f8-0d4503e538df.png)

### Windows version

Windows11 22H2

**Comment by chingucoding** [comment]
Thank you for creating this issue, however please use the discussions tab of this repository to ask questions surrounding samples.

Regarding your question, calling `SetTitleBar` only tells the OS which area the user can use to drag the window around. To have your app use the default Windows TitleBar, you need to set `ExtendsContentIntoTitleBar` to false. If you have any other questions or this does not solve your issue let me know.

**Comment by Melendez1209** [comment]
No, I meant to use the fallback title bar.
According to the content in the screenshot, I just need to
`
ExtendsContentIntoTitleBar = true;
 SetTitleBar(null);
`

**Comment by chingucoding** [comment]
I'm afraid the sample code shown in the app is not correct. The app actually sets the `ExtendsContentIntoTitleBar` property to false. The "fallback" titlebar is in fact the small area next to the titlebar buttons (as described in the explanation of the API).

**Comment by Melendez1209** [comment]
So how do I do that？

**Comment by chingucoding** [comment]
Can you elaborate on what exactly you want to achieve?

**Comment by Melendez1209** [comment]
Implement the fallback title bar.

**Comment by chingucoding** [comment]
You get the fallback title bar by callint `SetTitlebar` with `null` as parameter. From what I understand, the fallback titlebar is the blue are in this screenshot: 
![Screenshot of fallback titlebar](https://user-images.githubusercontent.com/16122379/217751186-d9bc14c3-49cb-4f38-80a8-702ec91af115.png)

This is also shown as part of the sample even though it's a bit hard to see given the area has the background of the app.

**Comment by chingucoding** [comment]
The standard fallback title bar is the area marked **blue** in my screenshot. If you do not like the blue area as your titlebar, you will need to implement the Titlebar yourself. You can find the respective code for that [here](https://github.com/microsoft/WinUI-Gallery/blob/ae2d7c304a7345feac395bf29dbefab6dbd1979b/WinUIGallery/App.xaml#L134) and [here](https://github.com/microsoft/WinUI-Gallery/blob/ae2d7c304a7345feac395bf29dbefab6dbd1979b/WinUIGallery/ControlPages/TitleBarPage.xaml.cs#L59).

**Comment by Melendez1209** [comment]
Thanks, I'll check it out later.
