### ISSUE TITLE
Questions about webview2 components

### ISSUE THREAD

**Issue by git102347501** [microsoft/WinUI-Gallery#1188]
### Issue type

sample request

### Which version of the app?

WinUI 3 Gallery

### Description

Can webview2 support calling js methods of internal web pages?

How can webview2 refresh the page content without changing the url?

Can webview2 access local static web resources? For example, I put the packaged website under the project directory and directly use the local path to access the website

### Windows version

Windows 11 22H2 (22621)

**Comment by chingucoding** [comment]
Hi, thank you for creating this issue, however this repository is for the WinUI Gallery. Next time, for questions around WinUI 2 or WinUI 3, please use the discussions feature on their [repository](https://github.com/microsoft/microsoft-ui-xaml/discussions).

Regarding your questions:
> Can webview2 support calling js methods of internal web pages?

I think you can call JS methods of the web page using as described [here](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/javascript).

> How can webview2 refresh the page content without changing the url?

I think that would be possible using [Reload](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.wpf.webview2.reload?view=webview2-dotnet-1.0.1518.46).

> Can webview2 access local static web resources? For example, I put the packaged website under the project directory and directly use the local path to access the website

As far as I'm aware, you can also open files inside WebView2 as discussed [here](https://stackoverflow.com/questions/66023241/webview2-how-to-load-local-file).
