### ISSUE TITLE
DiagramOrganigramm

### ISSUE THREAD

**Issue by TurbinoTo** [microsoft/WinUI-Gallery#1191]

**Comment by chingucoding** [comment]
Hi, thank you for creating this issue @TurbinoTo! It seems that you provided no issue description which makes it hard to act on this. Can you please provide a description of your bug, issue or question regarding the WinUI Gallery? (For questions regarding WinUI 2/3 please use their respective [repository](https://github.com/microsoft/microsoft-ui-xaml).
