### ISSUE TITLE
No support for Visual Studio ARM 64?

### ISSUE THREAD

**Issue by ultra133** [microsoft/WinUI-Gallery#1196]
### Which version of the app?

WinUI 3 Gallery

### Description

Build on Visual Studio 2022 (ARM 64-bit) fails with following error:

`Task 'ValidateAppxManifest' failed. Retrieving the COM class factory for component with CLSID {5842A140-FF9F-4166-8F5C-62F5B7B0C781} failed due to the following error: 800700c1  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1).`

### Windows version

Windows 11 22H2 (22621)

**Comment by chingucoding** [comment]
Hmm that's strange. I wish I would have an ARM64 device to test this more accurately now, building with ARM64 as target works for me though. @bpulliam thoughts?

**Comment by Scottj1s** [comment]
Thanks for reporting.  We have a repro, and this looks like a bug in Visual Studio.  A workaround may be to use the x64 version of msbuild, which prevents launching the Microsoft.Build.AppxPackage.dll task in a separate process that in turn causes the architecture mismatch error (BadImageFormatException) loading AppxPackaging.dll.

e.g.,
>"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" /bl WinUIGallery.DesktopWap.sln /t:build /p:publishreadytorun=true /p:PackageCertificateKeyFile=WinUIGallery.DesktopWap.Package_TemporaryKey.pfx

**Comment by Scottj1s** [comment]
The Visual Studio team has responded:

We’re aware of this bug, it’s already fixed for the 17.5 release, which is scheduled to GA next week.
  In the short term if you need to work around this you can retarget your app to 10.0.22621.  I believe setting this property in your wapproj will also do the trick:

`<UseX64ToolsOnArm64OS>true</UseX64ToolsOnArm64OS>`

**Comment by bpulliam** [comment]
The fix for this is in the upcoming 17.5 release of Visual Studio, which hits GA very soon.
