### ISSUE TITLE
Titlebar context menu is no longer dark mode in WinUI3 gallery

### ISSUE THREAD

**Issue by AndyHTML2012** [microsoft/WinUI-Gallery#1200]
### Which version of the app?

WinUI 3 Gallery

### Description

In WinUI2 gallery when right clicking on the title bar you would get the dark context menu when the app was in dark mode. In WinUI3 gallery the context menu is stuck in light mode.

### WinUI2 Gallery Titlebar context menu when in dark mode:
![WinUI2-Gallery-Titlebar-ContextMenu](https://user-images.githubusercontent.com/54720001/220807924-c9489137-5d75-4113-86c0-25cb6a740620.png)

### WinUI3 Gallery Titlebar context menu when in dark mode:
![WinUI3-Gallery-TitlebarContextMenu](https://user-images.githubusercontent.com/54720001/220807757-3c4f5d52-1cb4-4e88-bda2-82b0ec19cbdc.png)

### Windows version

Windows 11 22H2 (22621)

### Additional context

This is noticeable on both Windows 11 22H2 main release and in the release preview for the Moment 2 update to Windows 11.

**Comment by niels9001** [comment]
As this a WinUI/WASDK issue - better to discuss in the WASDK repo: https://github.com/microsoft/WindowsAppSDK/issues/95
