### ISSUE TITLE
The Viewbox Control has been Disabled

### ISSUE THREAD

**Issue by MarkBrainfire** [microsoft/WinUI-Gallery#1202]
### Which version of the app?

WinUI 3 Gallery  1.3.17.0

### Description

The Viewbox control is one of the most important WinUI 3 controls and essential for a major application I'm developing.

Yet it appears the Viewbox control has been disabled deliberately.  

Ironically, I came to this repos today to offer to enhance the WinUI 3 Gallery Viewbox page.

https://user-images.githubusercontent.com/78389339/222337679-de355a69-699a-47e9-8fa3-1b187c8c638a.mp4

### Windows version

Windows 11 22H2 (22621)

**Comment by chingucoding** [comment]
@bpulliam @gregwoo-microsoft Do you happen to know why the page was removed?

**Comment by MarkBrainfire** [comment]
Yes.  Someone used the wrong name for this control: ViewBox instead of Viewbox.  This causes the name type to be null and there's a line of code that checks for this and disables the control when this occurs.

But there's more going on than just a simple name fix.  There are XAML parsing errors under some circumstances.

Don't bother assigning this to anyone.  Hopefully I'll have a merge request for you soon, but I must be absolutely sure to find out why there are XAML parsing errors and make sure they never occur.
