### ISSUE TITLE
[Meta] Mouse forward and back buttons no longer navigate the gallery

### ISSUE THREAD

**Issue by citelao** [microsoft/WinUI-Gallery#1205]
### Which version of the app?

WinUI 3 Gallery

### Description

In the WinUI 3 gallery, the mouse navigation hotkeys (mouse side buttons, back and forward) do not navigate the gallery. This works in the WinUI 2 gallery.

1. Open either gallery.
2. Navigate to a page.
3. Press the back button on your mouse (or press Alt-left arrow).
    * WinUI 2 Gallery: navigates to previous page.
    * WinUI 3 Gallery: no action.
5. Press the forward button on your mouse (or press Alt-right arrow).
    * WinUI 2 Gallery: navigates to previous page.
    * WinUI 3 Gallery: no action.

### Windows version

Insider Build (xxxxx)

**Comment by MarkBrainfire** [comment]
I see what you're saying citelao.  Alt + left / right arrow is equivalent to going back and forward in the browser just like clicking the back arrow and then forward arrow in the upper left of a browser window.  All of this works in THIS GitHub window.

In the WinUI 3 Gallery you can click on the back arrow (upper left)  but a forward arrow is never displayed, and pressing Alt+ Left / Right arrows doesn't seem to work at all.

Of course, if you have selected a menu item on the left and click Alt + Up / Down arrow, you can move a selection box up and down through the list of menu items and then press enter to navigate to the currently selected menu item.

At any point you can click that back arrow displayed in the upper left to go back through the list of pages visited until you get to the home menu.  

I think they are using the WinUI 3 NavigationView control in the gallery.
https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.navigationview?view=windows-app-sdk-1.2

And the control in the WinUI 2 gallery may have been different.

Mark
