### ISSUE TITLE
ScrollViewer page is confusing

### ISSUE THREAD

**Issue by chigy** [microsoft/WinUI-Gallery#121]
**Describe the bug**

ScrollViewer sample is confusing because the page doesn't even show scroll indicator or scroll bar unless I zooomed out the image. Perhaps better representation of scroll viewer is better here?

**Steps to reproduce the bug**

**Expected behavior**

**Actual behavior**

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [ ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by chingucoding** [comment]
I agree that the "normal" ScrollViewer page is confusing. Since there is the "ScrollViewer (Preview)" page which has more and better examples.
It is pretty confusing to see that there are 2 Pages for the same control, so maybe we should delete the normal page and leave the preview page in?

**Comment by chingucoding** [comment]
Given that the "ScrollViewer (Preview)" page no longer exists in the WinUI 3 gallery, I think we should update the ScrollViewer page. @gregwoo-microsoft what are your thoughts on this?

**Comment by gregwoo-microsoft** [comment]
I agree, this page is not intuitive when you first launch it because you have to zoom in to see the scrollviewer. A simple fix could be to start the page with a Zoom = 2. What do you think @chingucoding ?

**Comment by chingucoding** [comment]
Seems like a good idea, that should fix the sample.
