### ISSUE TITLE
Remaining fixes before Design Guidance update

### ISSUE THREAD

**Issue by gregwoo-microsoft** [microsoft/WinUI-Gallery#1210]
### Issue type

enhancement

### Which version of the app?

WinUI 3 Gallery

### Description

@chingucoding @niels9001 I'm using this issue to list the remaining fixes we need to implement so that we can keep track of what is left before we can publish a new app update. Feel free to edit the list as needed :)

~1. Add new home banner bloom~
~2.  Add the new app icon (it finally got approved!)~ 
~3. Add the template studio icon asset~
~4. Remove the "Controls" header in the NavView and rename the "All controls" page to "All samples" or "All pages" --> I think that we should move away from the word "control" since a lot of the sample pages are not really controls per see (e.g. some of the motion & styles pages + the windows & system sections). Any thoughts?~
~5. Home tiles:~
  ~- Move the 'external link' icon to the bottom right of the card instead of the top right (the design team gave this feedback. They think that it is best to have the logo and title be at the top of the hierarchy)~
 ~- Decrease the size (both width and length) of the home tiles. They seem really big right now but let me know what you think is best~
   
~6. Toggle light/dark mode doesn't work for typography, icons, and colors page. On the typography page, the infobadges are not visible in dark mode.~
   - ![image](https://user-images.githubusercontent.com/90726278/223634833-f10e4cb7-6ae9-4dda-b80c-17b071223d9c.png)
7. Bug: Interacting with the autosuggest box crashes the app and creates an error.
   - ![image](https://user-images.githubusercontent.com/90726278/223634985-1e444e92-6db0-45e1-b1c0-9f092335a5c8.png)

**Comment by niels9001** [comment]
@chingucoding @gregwoo-microsoft 

This is what's currently in main:

<img width="682" alt="image" src="https://user-images.githubusercontent.com/9866362/223719675-fbc736a8-1f65-4bc1-b56b-2037b5ceb664.png">

Do you have repro steps for the search bug crash? Can't replicate it 😨

**Comment by niels9001** [comment]
@gregwoo-microsoft All issues are resolved :)!
