### ISSUE TITLE
Taskbar preview icon missing

### ISSUE THREAD

**Issue by niels9001** [microsoft/WinUI-Gallery#1215]
### Which version of the app?

WinUI 3 Gallery

### Description

Icon is missing on the taskbar preview. We should set the .ico.

### Screenshots

![image](https://user-images.githubusercontent.com/9866362/224677540-6e57263a-f5d2-4d23-8f57-cd9eac0e1fc8.png)

**Comment by MattBDev** [comment]
This is still an issue in 2.2.0. I request that this be reopened please.
![image](https://github.com/microsoft/WinUI-Gallery/assets/4009945/adb93613-e9d7-4b5c-81f3-db9c4445c83d)

**Comment by chingucoding** [comment]
It seems that the fix was not published to the store yet. When building the app from source, this bug is not present.
