### ISSUE TITLE
Title bar controls are sometimes only visible when hovering 

### ISSUE THREAD

**Issue by gregwoo-microsoft** [microsoft/WinUI-Gallery#1220]
### Which version of the app?

WinUI 3 Gallery

### Description

Description: The title bar controls are sometimes not visible and can only be revealed when hovering on the upper right section of the window.

I was only able to repro this bug when launching the app in the theme that is different from my system's chosen theme (e.g. Light theme when my computer is set to Dark theme)

<img width="594" alt="image" src="https://user-images.githubusercontent.com/90726278/226495816-f9ca75e7-b8fc-433c-812d-28b552808704.png">

**Comment by bpulliam** [comment]
Fixed by #1239
