### ISSUE TITLE
[Accessibility] Document F6 hotkey for moving between landmarks

### ISSUE THREAD

**Issue by citelao** [microsoft/WinUI-Gallery#1228]
### Issue type

sample request

### Which version of the app?

WinUI 3 Gallery

### Description

F6 is a common, although not super well-known, hotkey across Windows and Mac for switching between landmarks on a page (try it in Explorer, on the Desktop, in Edge, Chrome, or any Office app).

We should document this as a suggestion for app developers (although, why doesn't XAML do this automatically 🤔).

**Comment by karkarl** [comment]
This is moreso documenting a Windows behaviour. This may not be appropriate for the scope of WinUI Gallery.
