### ISSUE TITLE
I want to build it in macos(m2pro), but i cant build it

### ISSUE THREAD

**Issue by theSmokingSea** [microsoft/WinUI-Gallery#1249]
### Issue type

sample request

### Which version of the app?

WinUI 3 Gallery

**Comment by chingucoding** [comment]
This app is build using the Windows App SDK (short WASDK) and WinUI 3 which are only available on Windows (hence the name). There is however an outdated fork of this repo from the Uno Platform Team that should also be buildable on macOS: https://github.com/unoplatform/Uno.Xaml-Controls-Gallery.
