### ISSUE TITLE
XAML code still declares Font Family "MDL2"

### ISSUE THREAD

**Issue by Jay-o-Way** [microsoft/WinUI-Gallery#1252]
### Which version of the app?

WinUI 3 Gallery

### Description

`FontFamily="Segoe MDL2 Assets"` shouldn't be used anymore

### Screenshots

![image](https://user-images.githubusercontent.com/65828559/230216337-68ea733e-08bb-4e8d-ba83-debb70f79233.png)

**Comment by Jay-o-Way** [comment]
Seems simple. Should I wait for a "green light" or may I?

**Comment by chingucoding** [comment]
I think you can go ahead on this. I assume you would replace it with `SymbolThemeFontFamily` then?

**Comment by Jay-o-Way** [comment]
Thank you. It'll be replaced by either \<nothing> or Symboltheme, indeed.

**Comment by Jay-o-Way** [comment]
I have a problem in order to actually test this. See, the computer I build/run this on is on Windows 10. Because of this issue https://github.com/microsoft/WinUI-Gallery/discussions/1246 I can't actually run any of the exe's and therefore I can't copy that folder to my Windows 11 laptop... Can I solve this? Or shall I just create the pr and let people like you or Niels check this on their own device?

**Comment by chingucoding** [comment]
Hmm that's strange. I'm curious, is there a reason you want to test this on a Window 11 device? After all we also should support Windows 10 as WinUI 3 does. Regarding #1246, I'll take a look what the correct way would be to get an exe file working.

**Comment by Jay-o-Way** [comment]
> is there a reason you want to test this on a Window 11 device?

Of course, Windows 10 doesn't have the Fluent font (well, unless you installed it manually). The icons _show_ without a problem, just wanna double-check the font.

**Comment by Jay-o-Way** [comment]
P.S. I found a way to use Fluent Icons on Windows 10. Just install the font, that's it! 🤣
