### ISSUE TITLE
Bug title

### ISSUE THREAD

**Issue by Alyl968** [microsoft/WinUI-Gallery#1257]
### Which version of the app?

WinUI 3 Gallery

### Windows version

November 2021 Update/21H2 (19044), October 2018 Update/RS5 (17763)

**Comment by Alyl968** [comment]
![Splashscreen scale-100](https://user-images.githubusercontent.com/130268839/230755032-0ac5be1f-9958-4036-8890-20a1d85961ac.png)
Duplicate of #

**Comment by chingucoding** [comment]
Hi @alyl958 it seems there is no description on the actual issue. Can you please provide a description?

**Comment by bpulliam** [comment]
Blank Issue
