### ISSUE TITLE
Include a bit more text about icon font(s) in the main page

### ISSUE THREAD

**Issue by Jay-o-Way** [microsoft/WinUI-Gallery#1263]
### Issue type

enhancement

### Which version of the app?

WinUI 3 Gallery

### Description

On the page https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.fonticon?view=windows-app-sdk-1.2#default-font-family we can read

>If you don't specify a FontFamily, or you specify a FontFamily that is not available on the system at runtime, the FontIcon falls back to the default font family defined by the SymbolThemeFontFamily theme resource.

> By default, Windows uses the [Segoe Fluent Icon](https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-ui-symbol-font) font family. If your app is run on Windows 10, version 20H2 or earlier, the Segoe Fluent Icon font family is not available and the SymbolThemeFontFamily resource falls back to the [Segoe MDL2 Asset](https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-ui-symbol-font) font family instead. To use glyphs from the default system font, don't set the FontFamily property, let it use its default value.

Apparenty, this seems to be unclear to some people. Can we add this info on the Icons page?

**Comment by niels9001** [comment]
@jay-o-way A condensed version of this makes sense to add - and the guidance on using particular icon sizes as well? Is this something you'd like to pick up?

**Comment by Jay-o-Way** [comment]
Yes I would. 👍🏻

**Comment by Jay-o-Way** [comment]
Extra idea: we _could_ place the TextBlock text inside of the RichTextBlock and use SemiBold. Functionally not much of a difference, just thinking.

**Comment by Jay-o-Way** [comment]
Would it be good to have a way to collapse the info text, so that there will be more room for the important bits below that? (starting with "Fluent Icons Library")

**Comment by niels9001** [comment]
> Would it be good to have a way to collapse the info text, so that there will be more room for the important bits below that? (starting with "Fluent Icons Library") ![Expand text](https://user-images.githubusercontent.com/65828559/239691038-f9e35354-8bb0-41d0-a544-eedcb160b7a7.gif)

I agree.. the Icon search tool is the most important item on this page. I think using an `Expander` is a good idea, altought it looks a bit strange now with the expandable background/border being transparent?

Here's an potential setup:

[TextBlock] "Segoe Fluent Icons is the recommended icon font on Windows 11....."

[SettingsExpander] "Instructions on how to use Segoe Fluent Icons" (Collapsed by default)
[SettingsExpander.Content]
   [SettingsCard] "How to get the font: ..."
   [SettingsCard] "How to use Segoe Fluent Icons" (showing different types of code snippets, e.g. using `FontIcon` and `SymbolIcon` ....."
[/SettingsExpander.Content]

[Icon tool]

**Comment by Jay-o-Way** [comment]
Oké, so I have made this now. How's that look?
```
labs:SettingsExpander
    SettingsCard
        RichTextBlock
    SettingsCard
        RichTextBlock
        SampleCodePresenter CodeSourceFile="Icons/FontIconSample1_xaml.txt"
```
![image](https://github.com/microsoft/WinUI-Gallery/assets/65828559/20f8152e-2230-4eb1-95bc-77c673b2c022)

**Comment by Jay-o-Way** [comment]
> FontIcon and SymbolIcon

As long as the SymbolIcon functionally is broken, I'm hesitant to recommend it.
