### ISSUE TITLE
[Icon tool] Keyboard navigation support

### ISSUE THREAD

**Issue by niels9001** [microsoft/WinUI-Gallery#1264]
### Which version of the app?

WinUI 3 Gallery

### Description

The current implementation of the icon tool uses an `ItemsRepeater`, which does not provide keyboard navigation by default.

It also selects items when scrolling using touch, which might be unintended.

Switching to a `GridView` or another type of control is probably more appropriate?

cc @karenbtlai

**Comment by karkarl** [comment]
Fixed with linked PR!
