### ISSUE TITLE
Fluent Icons Library Example Page Link Broken

### ISSUE THREAD

**Issue by mboedigh** [microsoft/WinUI-Gallery#1268]
### Which version of the app?

WinUI 3 Gallery

### Description

From the WinUI 3 Gallery go to Design guidance and then Icons. Then Click Source and select either Xaml or c#. 
When I did this, I got 404 Page was not found error.

### Windows version

Windows 11 22H2 (22621)

**Comment by Jay-o-Way** [comment]
Looks like it's fixed now
