### ISSUE TITLE
Theme Resource missing

### ISSUE THREAD

**Issue by greatoceansoftware** [microsoft/WinUI-Gallery#1269]
### Which version of the app?

WinUI 3 Gallery

### Description

When referencing the colors in the Colors section of the WinUI 3 Gallery app, they are not found. Specifically, the color I am trying to use is ControlFillColorDefaultBrush. I get the error: "Cannot find a Resource with the Name/Key ControlFillColorDefaultBrush"

The offending line of XAML code referred to is:

`    <Setter Property="Background" Value="{ThemeResource ControlFillColorDefaultBrush}"/>`

I have confirmed that this resource is not in generic.xaml nor themeresources.xaml located in:

C:\Program Files (x86)\Windows Kits\10\DesignTime\CommonConfiguration\Neutral\UAP\10.0.22000.0\Generic

Nor in:

C:\Users\...\nuget\packages\microsoft.windowsappsdk\1.3.230331000\lib\net6.0-windows10.0.18362.0\Microsoft.WinUI\Themes\generic.xaml

My Application Resources are as follows:

```
  <Application.Resources>
    <ResourceDictionary>
      <ResourceDictionary.MergedDictionaries>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls"/>
        <ResourceDictionary Source="Views/Styles.xaml"/>
      </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
  </Application.Resources>
```

Am I missing some reference or have the wrong version of WinUI installed? Otherwise, there's a disconnect between the documentation of the WinUI 3 Gallery and the versions deployed in the field. Thanks!

### Screenshots

![image](https://user-images.githubusercontent.com/78753788/232346831-2880fe51-7508-4e24-b533-a71b5e994aaf.png)

### Windows version

Windows 10 22H2 (19045)

### Additional context

Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.5.4

**Comment by niels9001** [comment]
@greatoceansoftware Are you using UWP + WinUI2 or WindowsAppSDK + WinUI 3? For the later, there is no need to manually add the `XAMLControlsResources` in your `App.xaml.cs`.

Both ship with `ControlFillColorDefaultBrush`, as you can see here:
https://github.com/microsoft/microsoft-ui-xaml/blob/4041a77fa1468062ef45bfe7a136aeca6e9044f2/dev/CommonStyles/Common_themeresources_any.xaml#L133

I just tested this with a blank packaged Windows App SDK app on W11 and that worked..

Let me know if removing the `XAMLControlsResources` help - and if not, a standalone repro would be helpful!

**Comment by greatoceansoftware** [comment]
A bit more on this... First to answer your question:

If I create a new WinUI 3 project, XAMLControlResources is automatically added to the App.xaml file. I am using Windows 10.

![image](https://user-images.githubusercontent.com/78753788/232520899-b211a9dc-8ab9-4a03-963a-15e37d0df0ae.png)

If I comment out XAMLControlResources, I get this error:

![image](https://user-images.githubusercontent.com/78753788/232521709-63bbadef-9101-4e3e-9f04-975c0c8bf867.png)

Hopefully that tells you something about the requirement for XAMLControlResources.

Since the original post, I have found that the original error only occurs when trying to set the Background property of ProgressRing. Using the theme resource SolidBackgroundFillColorSecondaryBrush (or any theme resource) causes the XAML Parsing error.

![image](https://user-images.githubusercontent.com/78753788/232522946-c88d9ad2-26db-4393-91c5-4d251ade5c1f.png)

So I'm wondering if this is isolated to ProgressRing and is related to the control rather than the arrangement of dictionaries and resources? If so I can post it on the WindowsAPPSDK repository.

**Comment by niels9001** [comment]
@greatoceansoftware Ooooh, my bad.. yeah, you're right - WASDK adds it automatically to the `App.xaml` whereas for UWP you need to do it manually.. hence the confusion.

This is working for me without any crashes:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/9866362/232527449-274e744d-b35a-41ea-bde7-df65ffbbdbe0.png">

In your screenshot, I see that you are using `SolidBackgroundFillColorSecondary` and not `SolidBackgroundFillColorSecondaryBrush` - does that might be the reason for the crash?

**Comment by greatoceansoftware** [comment]
No, I was just testing the color vs. the brush to see if it made a difference. Forgot to change it back. (I know Background property is brush, but grasping for anything here).

I'm convinced now that this is one of those weird arrangement of the dictionaries, and for some reason the ProgressRing can't find its way back up the tree all the way to the WinUI 3 ThemeResources dictionary. I had hard coded all of my colors while developing and now I'm circling back to replace them with theme colors. I had read somewhere in the last few months that the order of the dictionaries and the precedence they take can cause such issues.

**Comment by greatoceansoftware** [comment]
Resolved it. Placing a reference to XamlControlsResources (including in the MergedDictionaries) inside my Styles.xaml (ResourceDictionary) did the trick.

![image](https://user-images.githubusercontent.com/78753788/232535743-4e956af3-9f78-4910-9b30-31f440459c16.png)
