### ISSUE TITLE
Update Mica XAML and C# samples

### ISSUE THREAD

**Issue by Jay-o-Way** [microsoft/WinUI-Gallery#1286]
### Issue type

enhancement

### Which version of the app?

WinUI 3 Gallery

### Description

Now that Mica is in W.A.SDK 1.3, we should mention the xaml on the Backdrops page. And/or link to https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.media.micabackdrop

### Screenshots

![image](https://github.com/microsoft/WinUI-Gallery/assets/65828559/677a3eef-b720-45dc-b24e-8824d95d5b54)

**Comment by niels9001** [comment]
@jay-o-way @karkarl Should we remove the existing sample code altogether and just show the one line XAML / C# strings? Not really a point to show complicated/verbose code if 1.3 introduces an easy way to do things 😊? (Might convince devs to adopt it as it's just so easy now!)

**Comment by Jay-o-Way** [comment]
Sounds perfect!

**Comment by LoganDark** [comment]
> @Jay-o-Way @karkarl Should we remove the existing sample code altogether and just show the one line XAML / C# strings? Not really a point to show complicated/verbose code if 1.3 introduces an easy way to do things 😊? (Might convince devs to adopt it as it's just so easy now!)

Absolutely, it took me a while to discover the easy way. Just need to make it explicit that Visual Studio projects don't use version 1.3 of the SDK by default, and you have to manually upgrade the NuGet package after creating the project
