### ISSUE TITLE
How to set the fontsize of the PivotItem's header

### ISSUE THREAD

**Issue by Jerry-ojk** [microsoft/WinUI-Gallery#1288]
### Issue type

enhancement

### Which version of the app?

WinUI 3 Gallery

### Description

My application needs to set the PivotItem's header to a smaller font, but I don't know how to implement it. After checking the official documents and examples, I didn't find any relevant descriptions, and it seems that there is no corresponding API. Although PivotItem has the 'FontSize' attribute, in practical terms, it sets the font size of the content contained in the PivotItem rather than its header.

### Screenshots

![image](https://github.com/microsoft/WinUI-Gallery/assets/27681779/9beec82e-c3e5-4b15-97bc-cfce29776bf7)

### Windows version

Windows 11 22H2 (22621)

**Comment by niels9001** [comment]
@jerry-ojk The `Pivot` control was never updated to enable developers to easily change the fontsize. You'd need to copy the entire style and make changes there.

The Calculator app did this, and this might be of help: https://github.com/microsoft/calculator/blob/14f35d19f776fa50a3eeca9fb52c90e0c857e9a9/src/Calculator/Views/Calculator.xaml#L827

<img width="137" alt="image" src="https://github.com/microsoft/WinUI-Gallery/assets/9866362/1fe0d0a9-3102-49ac-ab1d-2b7a75b474f4">


Other options are using a `NavigationView` instead set the `PaneDisplayMode` to top. Or, you could use a more lightweight [`Segmented` control from the Windows Community Toolkit](https://github.com/CommunityToolkit/Labs-Windows/blob/27d4acdc096c912081163224806d39512f1ada56/components/SegmentedControl/samples/SegmentedControlStylesSample.xaml#L22) - that also comes with a 'PivotStyle' (however, you'd need to create a frame yourself to handle content changes).

Hope this helps

**Comment by Jerry-ojk** [comment]
Fine, thank you very much!
