### ISSUE TITLE
Incorrect version for Windows App SDK on main page

### ISSUE THREAD

**Issue by Mysterious-Dev** [microsoft/WinUI-Gallery#1296]
### Which version of the app?

WinUI 3 Gallery

### Description

All is in the title (It should be **Windows App SDK 1.3.1**).

By the way, I wanted to know how to change this in visual studio with recent commits (if ever for a day it happens again ^^).

### Screenshots

![image](https://github.com/microsoft/WinUI-Gallery/assets/40738104/6f4c951c-057c-49bd-af81-990c8de62d57)

### Windows version

Windows 11 22H2 (22621)

**Comment by chingucoding** [comment]
The code for this can be found here: https://github.com/microsoft/WinUI-Gallery/blob/2722266d28bef6d7ab5efb059699bd7ec704f864/WinUIGallery/App.xaml.cs#L38-L42

Given we are relying on generated files from the WinAppSDK here, the version might just be specified wrongly in the package. @scottkuhl @bpulliam maybe you are the right folks on this matter?

**Comment by Mysterious-Dev** [comment]
Yeah, but the informations that are stored in auto generated file called `WindowsAppSDK-VersionInfo.cs`, where can I found them ?

**Comment by Mysterious-Dev** [comment]
Yes. Where can I modify the actually value to fix this (with a PR) ?

**Comment by chingucoding** [comment]
I'm afraid you can't really edit this file since it is autogenerated by the framework. We include this file using the following item: https://github.com/microsoft/WinUI-Gallery/blob/main/WinUIGallery/WinUIGallery.DesktopWap.csproj#L74

The file itsself lives inside the directory where the WinAppSDK library sits in which is not part of the checked in code of this repository.

**Comment by Scottj1s** [comment]
Internal tracking: task.ms/44938134

**Comment by Scottj1s** [comment]
Until this is fixed in the framework, I've removed the incorrect patch number from display.  The next publish of Gallery to the store will have the fix.

**Comment by Mysterious-Dev** [comment]
> Until this is fixed in the framework, I've removed the incorrect patch number from display.  The next publish of Gallery to the store will have the fix.

Lovely ! Thank you for your follow-up on this issue ^^
