### ISSUE TITLE
Deep linking to specific pages does not work

### ISSUE THREAD

**Issue by niels9001** [microsoft/WinUI-Gallery#1300]
### Which version of the app?

WinUI 3 Gallery

### Description

Deep linking doesn't work.

Steps to reproduce:
- Go to any page
- Click the "Copy link" button.
- Open `Run` prompt, copy-and-paste and hit enter
- WinUI opens, but doesn't navigate to the correct page

Related: #1164

**Comment by chingucoding** [comment]
I think this is an issue with the protocol activation which just seems to be entirely broken. There is/was #979 but that didn't get far :/

**Comment by niels9001** [comment]
> I think this is an issue with the protocol activation which just seems to be entirely broken. There is/was #979 but that didn't get far :/

Correct, we should be using the new APIs introduced for WinAppSDK: https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.windows.applifecycle.appinstance.getactivatedeventargs?view=windows-app-sdk-1.3#microsoft-windows-applifecycle-appinstance-getactivatedeventargs

```csharp
var eventargs = Microsoft.Windows.AppLifecycle.AppInstance.GetCurrent().GetActivatedEventArgs();

if (eventargs.Kind is ExtendedActivationKind.Protocol && eventargs.Data is ProtocolActivatedEventArgs)
{
      ProtocolActivatedEventArgs ProtocolArgs = eventargs.Data as ProtocolActivatedEventArgs;
      var uri = ProtocolArgs.Uri;
}
```
