### ISSUE TITLE
App notifications sample Request

### ISSUE THREAD

**Issue by GID0317** [microsoft/WinUI-Gallery#1303]
### Issue type

sample request

### Which version of the app?

WinUI 3 Gallery

### Description

it will be very helpfull if WinUI3 Gallery has the App notification sample like in this website: https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/notifications/app-notifications/?source=recommendations

### Windows version

Windows 11 22H2 (22621)

**Comment by Mysterious-Dev** [comment]
#1021

**Comment by GID0317** [comment]
I will close as duplicate
