### ISSUE TITLE
This makes the links stick to the word beforehand, we should probably revert that:

### ISSUE THREAD

**Issue by eradzh87** [microsoft/WinUI-Gallery#1306]
This makes the links stick to the word beforehand, we should probably revert that: 
![Screenshot of text with links not being properly spaced to the text before it](https://github.com/microsoft/WinUI-Gallery/assets/16122379/7a401cbd-2eac-4198-a90d-f5e384191b08)

_Originally posted by @chingucoding in https://github.com/microsoft/WinUI-Gallery/pull/1294#discussion_r1222735405_

**Comment by chingucoding** [comment]
Thank you for mentioning this again, gladly before merging the PR that was fixed and the issue is not present on the main branch.
