### ISSUE TITLE
For AnimatedIcon, display all built-in AnimatedVisuals

### ISSUE THREAD

**Issue by Marv51** [microsoft/WinUI-Gallery#1312]
### Issue type

enhancement

### Which version of the app?

WinUI 3 Gallery

### Description

The ["AnimatedIcon"-page](https://github.com/microsoft/WinUI-Gallery/blob/main/WinUIGallery/ControlPages/AnimatedIconPage.xaml) currently shows 2 animated icons: AnimatedFindVisualSource and AnimatedSettingsVisualSource.

There are currently six additional built-in animated icons: 
- AnimatedAcceptVisualSource
- AnimatedBackVisualSource
- AnimatedChevronDownSmallVisualSource
- AnimatedChevronRightDownSmallVisualSource
- AnimatedChevronUpDownSmallVisualSource
- AnimatedGlobalNavigationButtonVisualSource

Can this example page be extended to also show these other icons? 

This would be especially useful, because the [documentation](https://learn.microsoft.com/de-de/windows/winui/api/microsoft.ui.xaml.controls.animatedvisuals?view=winui-2.8) lacks any visualizations on what these icons look like.

### Windows version

Windows 11 22H2 (22621)

**Comment by manabu-nakamura** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/10243: The AnimatedChevronRightDownSmallVisualSource and AnimatedChevronUpDownSmallVisualSource of the AnimatedIcon cannot play correctly

**Comment by ghost1372** [comment]
> [microsoft/microsoft-ui-xaml#10243](https://github.com/microsoft/microsoft-ui-xaml/issues/10243): The AnimatedChevronRightDownSmallVisualSource and AnimatedChevronUpDownSmallVisualSource of the AnimatedIcon cannot play correctly

https://github.com/microsoft/microsoft-ui-xaml/issues/10243#issuecomment-3099410948
