### ISSUE TITLE
Content Dialog backdrop not displaying over custom TitleBar

### ISSUE THREAD

**Issue by BrancheyJuhas** [microsoft/WinUI-Gallery#1315]
### Which version of the app?

WinUI 3 Gallery

### Description

The backdrop that shows over the window does not extend into the non-system title bar when the ContentDialog is displayed. This is causing an inconsistent design and can lead to confusion and unwanted result, because the problem remains still, even if the sample code is copied by the user.

### Screenshots

![Dialog Box Bug](https://github.com/microsoft/WinUI-Gallery/assets/98485942/23839ffa-e432-441a-9c92-7579c1a45d92)

### Windows version

Windows 11 22H2 (22621)

**Comment by Jay-o-Way** [comment]
External issue: https://github.com/microsoft/microsoft-ui-xaml/issues/6534
