### ISSUE TITLE
RadioButtons page is under Layout category instead of Basic Input

### ISSUE THREAD

**Issue by A1steaksa** [microsoft/WinUI-Gallery#1320]
### Which version of the app?

WinUI 3 Gallery

### Description

Unless there's something I'm missing about RadioButtons, they should not be listed under "Layout" and would fit much better under "Basic Input"

### Screenshots

![image](https://github.com/microsoft/WinUI-Gallery/assets/8369707/34782beb-012f-456e-8f9b-2f5c5a7e2c5a)

### Windows version

Insider Build (xxxxx)

### Additional context

![image](https://github.com/microsoft/WinUI-Gallery/assets/8369707/4774d48c-14b3-4747-8360-06f659ef56f4)

**Comment by karkarl** [comment]
RadioButtonS (plural) is a layout control for RadioButton (singular). RadioButton is under basic input as appropriate. Sorry for the confusion on control naming, that is beyond the scope for WinUI Gallery to update.
