### ISSUE TITLE
Fix documentation links to UWP content

### ISSUE THREAD

**Issue by bpulliam** [microsoft/WinUI-Gallery#1344]
### Which version of the app?

WinUI 3 Gallery

### Description

We have a few links that point to UWP docs instead of WinAppSDK.

- [x] 1. https://learn.microsoft.com/uwp/api/windows.ui.xaml.controls.fonticon should be https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.fonticon
- [ ] 2. https://docs.microsoft.com/en-us/windows/uwp/controls-and-patterns should be https://learn.microsoft.com/windows/apps/design/controls
- [x] 3. https://learn.microsoft.com/windows/uwp/debug-test-perf/version-adaptive-apps
- [x] 4. https://learn.microsoft.com/windows/uwp/composition/composition-animation
- [ ] 5. https://learn.microsoft.com/windows/uwp/composition/using-the-visual-layer-with-xaml
- [ ] 6. https://learn.microsoft.com/uwp/api/windows.applicationmodel.datatransfer.clipboard
- [ ] 7. https://learn.microsoft.com/uwp/api/Windows.Storage.Pickers
- [ ] 8. https://learn.microsoft.com/windows/uwp/contacts-and-calendar/images/shoulder-tap-static-

payload.png

**Comment by chingucoding** [comment]
@karkarl Would you mind if I create a PR for this?

**Comment by karkarl** [comment]
> @karkarl Would you mind if I create a PR for this?

Go for it!

**Comment by Jay-o-Way** [comment]
Speaking of links... The specific parts of the URLs for point 2 all start with a `/` which gives the concatenated URL a double `...//...`. Functionally no problem, so no priority, just wanted to mention it.
