### ISSUE TITLE
Help, WebView2 Source Loading local files cannot use special characters

### ISSUE THREAD

**Issue by NmaeXC** [microsoft/WinUI-Gallery#1346]
### Issue type

sample request

### Which version of the app?

WinUI 3 Gallery

### Description

MainWindow.xaml

`
<?xml version="1.0" encoding="utf-8" ?>
<Window
    x:Class="AppWebview_Test.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local="using:AppWebview_Test"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid Margin="20">
        <Grid.RowDefinitions>
            <RowDefinition Height="*" />
            <RowDefinition Height="30" />
        </Grid.RowDefinitions>

        <WebView2
            x:Name="MyWebView2"
            HorizontalAlignment="Stretch"
            VerticalAlignment="Stretch"
            Source="http://www.baidu.com" />

        <StackPanel
            Grid.Row="1"
            HorizontalAlignment="Center"
            Orientation="Horizontal"
            Spacing="20">
            <Button
                HorizontalAlignment="Center"
                Click="Button_Click"
                Content="click" />
            <Button
                HorizontalAlignment="Center"
                Click="Button_Click2"
                Content="click2" />
        </StackPanel>

    </Grid>
</Window>

`

MainWindow.xaml.cs
`
using System;

using Microsoft.UI.Xaml;

namespace AppWebview_Test
{
  
    public sealed partial class MainWindow : Window
    {

        public MainWindow()
        {
            this.InitializeComponent();         
        }
 

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            
            MyWebView2.Source = new Uri("F:/C%23/index.html");
        }

        private void Button_Click2(object sender, RoutedEventArgs e)
        {
            MyWebView2.Source = new Uri("F:/C/index.html");
        }
    }
}
`

I am trying to load a local HTML file,But always unsuccessful.Later on, it was discovered that there may be a path length of '#', but after escaping, I was still unable to open the local file.

### Windows version

Windows 10 22H2 (19045)

**Comment by chingucoding** [comment]
I think this is a bug with WebView 2, there also was an issue including # in folder names: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2264. Since this is not an issue with the Gallery, I'll close this issue. Feel free to create an issue on the https://github.com/MicrosoftEdge/WebView2Feedback repository though, as this seems like a bug.
