### ISSUE TITLE
Title Bar custom background & foreground colors not properly working

### ISSUE THREAD

**Issue by AndyHTML2012** [microsoft/WinUI-Gallery#1355]
### Which version of the app?

WinUI 3 Gallery

### Description

- When switching the background color of the title bar, it doesn't evenly fill up the entire title bar and gets cut off at the title bar logo
- The foreground color controls do not work at all and have no functionality with the new top-level UI Element
- Resetting to the system title bar causes the window minimize, restore/maximize, and close button controls to become impossible to see

A video and screenshot have been attached showing the following issues.

### Screenshots

![SystemTitleBar_Issue_9-9-23](https://github.com/microsoft/WinUI-Gallery/assets/54720001/ea208ea8-9865-4f72-9856-2f51bc964324)

https://github.com/microsoft/WinUI-Gallery/assets/54720001/a6a4a250-95db-42c4-8183-eb4f903fd8b9

### Windows version

Insider Build (xxxxx)

### Additional context

These issues were tested and found on 23H2 (22631.2271) in the video, but I also found them on my laptop running 22H2 release. These issues were found in WinUI3 gallery version 2.2.0.0

**Comment by Jay-o-Way** [comment]
Is this one also related to https://github.com/microsoft/microsoft-ui-xaml/issues/8899?

**Comment by chingucoding** [comment]
I don't really think so given that #1368 fixes the issues in this issue.
