### ISSUE TITLE
C# Code Samples Are Gone

### ISSUE THREAD

**Issue by DJRM2021** [microsoft/WinUI-Gallery#1373]
### Which version of the app?

WinUI 3 Gallery

### Description

C# code samples on the FlipView page are all gone.

### Screenshots

![image](https://github.com/microsoft/WinUI-Gallery/assets/77593544/dfb64296-0476-4b83-9f83-528663668f36)
![image](https://github.com/microsoft/WinUI-Gallery/assets/77593544/253043fb-2e6a-45bc-9b5c-baa034fd531d)

### Windows version

Windows 11 22H2 (22621)

**Comment by chingucoding** [comment]
Thank you for creating this issue, this is indeed a bug. However it is a bug not in the form of the sample code being missing but rather the UI looking like there being one despite there not being one. 
So there is no C# code that you are missing on out here, I've created a fix so we don't indicate code being there despite this being not the truth.
