### ISSUE TITLE
[Suggestion] Add link to _themeresources.xaml for each control

### ISSUE THREAD

**Issue by citelao** [microsoft/WinUI-Gallery#1388]
### Issue type

enhancement

### Which version of the app?

WinUI 3 Gallery

### Description

I often want to look at the default _themresources.xaml (the default style) for XAML controls ([example](https://github.com/microsoft/microsoft-ui-xaml/blob/4873563b7953e2431caed4efcdc3b8261d1405cd/dev/CommonStyles/TextBlock_themeresources.xaml#L38)):

* To see what [lightweight styling](https://learn.microsoft.com/en-us/windows/apps/design/style/xaml-styles#lightweight-styling) brushes are available & see what their default values are
* To see what visual states there are
* To understand how a control is implemented (what parts does XAML use?)

Can we add links to these files for each control? Right now, it is difficult to find those implementations.

**Comment by karkarl** [comment]
@bpulliam Noting here to investigate in proper linking to winui3 source.
