### ISSUE TITLE
Crash when switching to page ”SemanticZoom“

### ISSUE THREAD

**Issue by Hatsuna-Miku** [microsoft/WinUI-Gallery#1409]
### Which version of the app?

WinUI 3 Gallery

### Description

Can easily reproduced by simply clicking the "SemanticZoom" menu, the app first freezes then quickly crashed with no error messages.

### Screenshots

https://github.com/microsoft/WinUI-Gallery/assets/60806013/16f211bf-d682-41f7-8595-0539506a19a9

### Windows version

Windows 11 22H2 (22621)

**Comment by HO-COOH** [comment]
Yep, same windows version, same crash. On my machine, it can't even show the page. Crash immediately after clicking the navigation item.

**Comment by paulushub** [comment]
Confirmed: Crashing on Windows 10 (22H2) - Japanese

**Comment by skrubbeltrang** [comment]
Yes, crashes immediately on Win10, 19045.3758 when clicking Scrolling->SemanticZoom.

**Comment by chingucoding** [comment]
It seems that this issue has been fixed at some point, I was unable to reproduce this when building with commit 149d6357292bfe57354236ec43969b564ceea397

**Comment by Hatsuna-Miku** [comment]
Indeed, it was fixed.
