### ISSUE TITLE
WinUI 2 Gallery Needs a setting to turn off UI objects that can not be used in UWP apps.

### ISSUE THREAD

**Issue by Tudball** [microsoft/WinUI-Gallery#1424]
InfoBar does not compile for UWP app.  Makes Gallery less valuable.

**Comment by chingucoding** [comment]
Given that WinUI 2 Gallery is a UWP app, I'm fairly sure that all samples you see would also work in a UWP app. One pitfall is the fact that some controls are only available as part of WinUI 2, a library for UWP apps that comes with updated design and new controls. Is your issue related to being unable to use WinUI 2 inside your app (curious what those reasons are or if there is an issue blocking you) and thus needing to filter out the controls?

**Comment by Tudball** [comment]
The new AI is a terrific help.   I asked it how to fix the problem.  It knew.   I was able to get everything working.  It turned out to not be your software.  Sorry.

Thanks for the interest.

________________________________
