### ISSUE TITLE
Winui 3 datagrid Row height is not working when we resize column

### ISSUE THREAD

**Issue by chiragpandya04** [microsoft/WinUI-Gallery#1427]
### Issue type

sample request

### Which version of the app?

WinUI 3 Gallery

### Description

When we have set Wrap data for any column and if user resize (shrink) column and then expand column. data grid is not refreshing its height based on content. hence so many blank spaces. Please refer my both snapshots.

 <ctWinUI:DataGrid.Resources>
     <Style TargetType="TextBlock" x:Key="WrapText">
         <Setter Property="TextWrapping" Value="Wrap"/>
     </Style>
 </ctWinUI:DataGrid.Resources>

 <ctWinUI:DataGridTextColumn Header="Parent Mountain"
                             Binding="{Binding Parent_mountain}" ElementStyle="{StaticResource WrapText}"
                             Tag="Parent_mountain" />

### Screenshots

![image](https://github.com/microsoft/WinUI-Gallery/assets/42544312/0aa79aa2-7b4e-49dd-bc43-d304086f951e)

![image](https://github.com/microsoft/WinUI-Gallery/assets/42544312/7548fc0a-5c30-420a-945d-b2927cc8c3a1)

**Comment by karkarl** [comment]
DataGrid is not part of WinUI 3, is this Community Toolkit or another library?
