### ISSUE TITLE
NewControlsPage

### ISSUE THREAD

**Issue by fmassicci** [microsoft/WinUI-Gallery#1437]
CS0121	The call is ambiguous between the following methods or properties: 'GroupInfoList.GroupInfoList(IEnumerable<object>)' and 'GroupInfoList.GroupInfoList(IEnumerable<object>)'	WinUIGallery	C:\WindowAppSDKSample\WinUI-Gallery-main\WinUIGallery\NewControlsPage.xaml.cs 40 Active

Why do I get this error when I compile the application?

**Comment by marcelwgn** [comment]
Can you share the steps to reproduce this issue? After a fresh clone I was able to sucessfully build the WinUIGallery packaged app and the CI is also able to build the app.

**Comment by karkarl** [comment]
Closing from lack of activity.
