### ISSUE TITLE
The app crashes trying to show the search results page

### ISSUE THREAD

**Issue by AndrewKeepCoding** [microsoft/WinUI-Gallery#1438]
### Which version of the app?

WinUI 3 Gallery

### Description

To reproduce the crash, enter some text like "button" in the search box and press Enter.

**Comment by Jay-o-Way** [comment]
I thought i noticed some performance issues too, when searching for icons.

**Comment by AndrewKeepCoding** [comment]
> I thought i noticed some performance issues too, when searching for icons.

I'm not sure if I can see performance issues...🤔
