### ISSUE TITLE
TextBlocks: fast path or slower path? (property versus content)

### ISSUE THREAD

**Issue by Jay-o-Way** [microsoft/WinUI-Gallery#1445]
### Issue type

enhancement

### Which version of the app?

WinUI 3 Gallery

### Description

`<TextBlock Text="Some text" .../>` and `<TextBlock>Some text.</TextBlock>` are both used in (seemingly) the same situations. Let's choose the right version for the situation?

### Windows version

Insider Build (xxxxx)

### Additional context

https://learn.microsoft.com/windows/apps/design/controls/text-block

**Comment by marcelwgn** [comment]
I thin kin some PR, this was discussed and the idea was to do it in the future using fastpath where it makes sense but not migrate existing TextBlocks. The question of course also arrises if fastpath text rendering is still a thing in WinUI 3.

**Comment by Jay-o-Way** [comment]
#1279

**Comment by Jay-o-Way** [comment]
You mean you choose to keep the inconsistency?

**Comment by marcelwgn** [comment]
Back than other things were more important, given we have #1279 I think we could start thinking about this topic again. What do you think @karkarl

**Comment by Jay-o-Way** [comment]
I am going to assume the label "good first issue" is a sign of "green light"?
