### ISSUE TITLE
WinUI3 Gallery will crash when "Enter" typed in the search box when there's content in it

### ISSUE THREAD

**Issue by ShimizuTheLotus** [microsoft/WinUI-Gallery#1447]
### Which version of the app?

WinUI 3 Gallery

### Description

I tried to search with the search bar but it crashed after I pressed enter. It's repeatable.
![image](https://github.com/microsoft/WinUI-Gallery/assets/152269217/992474f8-4104-4dfd-a05f-b327a17594ec)
I typed in the keywords then pressed "Enter" key, and then it crashed.
*The app will not crash when there's no content in the search box*

### Windows version

Insider Build (xxxxx)

### Additional context

Windows 23H2 OS Build 22635.3139
WinUI3 Gallery 2.2.0.0

**Comment by marcelwgn** [comment]
Thank you for reporting this issue, this will be fixed with #1439. Since this was also reported with #1438, I'll close this for simpler tracking of issues. Again, thank you for reporting this!
