### ISSUE TITLE
WinUI 2 Gallery in Microsoft Store does not have an arm64 version

### ISSUE THREAD

**Issue by juliushardt** [microsoft/WinUI-Gallery#1448]
### Issue type

enhancement

### Which version of the app?

WinUI 2 Gallery

### Description

The WinUI 2 Gallery application in the Microsoft Store currently does not have arm64 version. As Windows Insider builds 26058+, where arm32 UWP applications are no longer supported, have arrived in the Canary and Dev Insider channels, this means that users of arm64 devices have to resort to x64 emulation, which leads to decreased performance and hence, makes comparisons between WinUI 2 and WinUI 3, for which the WinUI Gallery is a useful tool, more difficult on these devices. Alternatively, one can build an arm64 version of the application locally, but this is not as convenient as simply installing WinUI 2 Gallery from the Microsoft Store.

Given that WinUI 2 will still be around for some time, I suggest publishing an arm64 version of WinUI 2 Gallery to the store. In #1014, support for arm64 was already added to the application itself. This issue is about the missing arm64 binaries in the store.

### Windows version

Insider Build (xxxxx)

**Comment by karkarl** [comment]
Hey @juliushardt, thanks so much for the feedback. Unfortunately, we are moving away investments for WinUI 2 Gallery and will not be able to add support for this.
