### ISSUE TITLE
WinUI 3 Gallery crashing when searching icons.

### ISSUE THREAD

**Issue by raphael3292383** [microsoft/WinUI-Gallery#1460]
### Which version of the app?

WinUI 3 Gallery

### Description

When we search an icon in Design Guidelines -> Icons on the WinUI 3 gallery, the app become unstable **or** the app crashes.

### Screenshots

![image](https://github.com/microsoft/WinUI-Gallery/assets/81994075/c8f71851-0566-4cf6-b675-1d92d03aa0f8)

### Windows version

Windows 11 22H2 (22621)

**Comment by marcelwgn** [comment]
Seems like a suboptimal implementation of the searching algorithm, I'll take a look.
