### ISSUE TITLE
WinUI 3 Gallery crashes when using the NavigationView search

### ISSUE THREAD

**Issue by garrettpauls** [microsoft/WinUI-Gallery#1463]
### Which version of the app?

WinUI 3 Gallery

### Description

There are several situations where the NavigationView search functionality in the WinUI 3 Gallery app will crash the app.

1. Focus the search box.
2. Enter any text, regardless of whether it results in multiple results (`Button`), no results (`test`), or a single result (`MediaPlayerElement`).
3. Press Enter.
 
The app will crash and leave the following in the Windows event log:

```
Faulting application name: WinUIGallery.exe, version: 2.2.0.0, time stamp: 0x655e0000
Faulting module name: Microsoft.ui.xaml.dll, version: 3.1.4.0, time stamp: 0xd8e270fd
Exception code: 0xc000027b
Fault offset: 0x00000000003ba2f4
Faulting process id: 0x0x90F0
Faulting application start time: 0x0x1DA6A6E004A7A26
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WinUI3ControlsGallery_2.3.0.0_x64__8wekyb3d8bbwe\WinUIGallery\WinUIGallery.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.4_4000.1136.2333.0_x64__8wekyb3d8bbwe\Microsoft.ui.xaml.dll
Report Id: fd8bc85e-1173-4ebb-8430-b5066616a7bc
Faulting package full name: Microsoft.WinUI3ControlsGallery_2.3.0.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

1. Enter any text in the search box with results (`Button`)
2. Click on one of the results to open the corresponding page.
3. Press Control + F.

The app will crash and leave the following in the Windows event log:

```
Faulting application name: WinUIGallery.exe, version: 2.2.0.0, time stamp: 0x655e0000
Faulting module name: Microsoft.ui.xaml.dll, version: 3.1.4.0, time stamp: 0xd8e270fd
Exception code: 0xc000027b
Fault offset: 0x00000000003ba2f4
Faulting process id: 0x0x49E0
Faulting application start time: 0x0x1DA6A6DE39B40B3
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WinUI3ControlsGallery_2.3.0.0_x64__8wekyb3d8bbwe\WinUIGallery\WinUIGallery.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.4_4000.1136.2333.0_x64__8wekyb3d8bbwe\Microsoft.ui.xaml.dll
Report Id: 83ea5083-84fd-43b5-99b6-25f512b0c5b3
Faulting package full name: Microsoft.WinUI3ControlsGallery_2.3.0.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

### Windows version

Windows 11 22H2 (22621)

### Additional context

I currently see the issue on Windows 11 Pro 23H2 (22631.3155), however I also encountered this prior to the 23H2 update.
I'm running WinUI 3 Gallery 2.2.0.0, Windows App Runtime 4000.1136.2333.0

![image](https://github.com/microsoft/WinUI-Gallery/assets/670089/afd5ae98-3bd6-4fbf-b150-b85ba55eb2a5)

**Comment by marcelwgn** [comment]
Thank you @garretpauls for your very detailed issue report! I think this issue was fixed with #1439 and this issue no longer appears when building the app from main, hence I will close this.
