### ISSUE TITLE
Win+Backspace does not navigate back

### ISSUE THREAD

**Issue by karkarl** [microsoft/WinUI-Gallery#1465]
### Which version of the app?

WinUI 3 Gallery

### Description

See title.

Will need to re-enable to verify this bug #379

**Comment by Jay-o-Way** [comment]
I noticed that, when i click the small "navigate back" button on my mouse, nothing happens either. Think that's the same cause?

**Comment by marcelwgn** [comment]
@jay-o-way Do you happen to know what exactly the button is invoking? Most Mouse usually map it to a keycombination so knowing which this is invoking would be helpful

**Comment by Jay-o-Way** [comment]
It's a MS 5000 mouse
![image](https://github.com/microsoft/WinUI-Gallery/assets/65828559/944ecc33-249b-432e-af22-adcf832a48a0)

According to [online check](https://javascript.info/mouse-events-basics), button=3

**Comment by Jay-o-Way** [comment]
I still wonder how the window / framework doesn't handle this.

**Comment by marcelwgn** [comment]
Yeah, it's quite a lot of work to implement this, even more now that Corewindow no longer exists and you need to use the WinProcs
