### ISSUE TITLE
WinUI Gallery sample crashes when clicking Settings

### ISSUE THREAD

**Issue by Karl-Bridge-Microsoft** [microsoft/WinUI-Gallery#1477]
### Which version of the app?

WinUI 3 Gallery

### Description

Start the sample, click the Settings link, app crashes (two independent repros).

**Comment by karkarl** [comment]
Can you provide more detailed repro steps? What sample and settings link are you referring to, and is your OS WIn10.

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @karkarl - Here's a screenshot. It's the latest WinUI 3 Gallery app. The Settings button is lower left, bottom of left TOC/nav.

The only thing I do after starting the app is click that Settings button, which makes the app disappear.

<img width="927" alt="image" src="https://github.com/microsoft/WinUI-Gallery/assets/12849639/61c03cff-44ad-4198-a073-6c6d4f68c69a">

**Comment by mohummedibrahim** [comment]
I'm also seeing the same issue, after opening the WinUI Gallery, as soon as I click the Settings menu on the Navigation, the app crashes. I'm running **Win 10 Pro (Build 19045.4046)**

In the cloned repo, when I run it in debug mode and click on settings, VS stops here, https://github.com/microsoft/WinUI-Gallery/blob/main/WinUIGallery/App.xaml.cs#L51C17-L51C115
![image](https://github.com/microsoft/WinUI-Gallery/assets/10384613/d5c79363-bb75-4cff-aa01-91df9cc6ea93)

Looks like `.First()` in `windowsAppRuntimeVersion.First().FileVersion` throws this.
