### ISSUE TITLE
The SDK 'Microsoft.Build.CentralPackageVersions/2.0.1' specified could not be found

### ISSUE THREAD

**Issue by Balkoth** [microsoft/WinUI-Gallery#1479]
### Which version of the app?

WinUI 3 Gallery

### Description

Can not load WinUIGallery.csproj because of the error:

The SDK 'Microsoft.Build.CentralPackageVersions/2.0.1' specified could not be found

**Comment by karkarl** [comment]
You might be missing .NET Core SDK component in VIsual Studio Installer. This brings up a good point in that WinUI Gallery should have a .vsconfig file to make it easier developers to set up their environment for the repo.
