### ISSUE TITLE
Add Arabic Language Support to Time Picker

### ISSUE THREAD

**Issue by Zakariathr22** [microsoft/WinUI-Gallery#1492]
### Issue type

enhancement

### Which version of the app?

WinUI 3 Gallery

### Description

The time picker component currently lacks support for the Arabic language. To enhance usability and inclusivity, I propose adding Arabic language localization to the time picker. This feature would allow users to select time in Arabic, making it more accessible for Arabic-speaking users.

**Example:**

**- Hour:** ساعة
**- Minute:** دقيقة
**- Second:** ثانية
**- AM:** صباحًا
**- PM:** مساءً

### Additional context

It would be greater to have multiple language support in all components as well.

**Comment by H3llzreaper** [comment]
Sorry, I'm busy. I'll reply shortly.
