### ISSUE TITLE
Unstably Crash when Seatching Icons

### ISSUE THREAD

**Issue by ShimizuTheLotus** [microsoft/WinUI-Gallery#1499]
### Which version of the app?

WinUI 3 Gallery

### Description

I was using WinUI 3 Gallery for searching icons and sometimes when I tried to type in the search box, the app will crash(Not every time).

### Screenshots

![image](https://github.com/microsoft/WinUI-Gallery/assets/152269217/9ad1c739-7b5f-4d50-8174-f73bc01fca96)
the search box with letter "A" in it is the target.

### Windows version

Insider Build (xxxxx)

### Additional context

Windows 23H2 (OS Build 22635.3139)
WinUI 3 Gallery 2.4.1.0

**Comment by marcelwgn** [comment]
In theory, this should have been fixed with #1461, can you try to run the app from source and see if it still repros?

**Comment by karkarl** [comment]
Resolving as dupe of #1500
