### ISSUE TITLE
Source code is partially occluded when "Automatically hide scroll bars in Windows" is off

### ISSUE THREAD

**Issue by YourOrdinaryCat** [microsoft/WinUI-Gallery#1501]
### Which version of the app?

WinUI 3 Gallery

### Description

Some of the source code samples show a horizontal scrollbar. Makes sense - after all, the window might be too small to fully show them, and some examples are pretty long regardless. However, if I disable the "Automatically hide scroll bars in Windows" setting, the horizontal scrollbar occludes the actual source code - see attached image. It is particularly unfortunate here, because it occludes the two most important bindings in the code example - the issue is present throughout the whole app though.

### Screenshots

![The StandardUICommand page in the WinUI 3 Gallery, showing a source code example. The most important bindings - to Command and CommandParameter - are not visible due to the scrollbar occluding them, because the "Automatically hide scroll bars in Windows" setting is off](https://github.com/microsoft/WinUI-Gallery/assets/49221554/5fa42bb4-5781-4421-8e11-e09d787efcae)

### Windows version

November 2021 Update/21H2 (19044)

### Additional context

This applies to both galleries, and it would be quite nice if it was fixed in both.

**Comment by marcelwgn** [comment]
Thank you for creating this issue @YourOrdinaryCat, I'll be closing this in favor of #1489. Also thanks for mentioning that @Jay-o-Way
