### ISSUE TITLE
Enable TabView to support Mica

### ISSUE THREAD

**Issue by LaplaceStudio** [microsoft/WinUI-Gallery#1506]
### Issue type

sample request

### Which version of the app?

WinUI 2 Gallery

### Description

There is no Mica effect on the content background of TabView。

### Windows version

Windows 11 22H2 (22621), Windows 11 21H2 (22000)

### Additional context

Currently, I am using the following code to make the Mica effect effective. Is there a better solution?

`
private void ContentTabView_Loaded(object sender, RoutedEventArgs e) {

    var tabViewListView = (sender as TabView).FindDescendant<TabViewListView>();
    var grid = (tabViewListView.Parent as Grid).Parent as Grid;
    ContentPresenter contentPresenter = grid.Children.FirstOrDefault(c => c is ContentPresenter) as ContentPresenter;
    if (contentPresenter != null) {
        contentPresenter.Background = new SolidColorBrush(Colors.Transparent);  
    }

}
`

**Comment by karkarl** [comment]
May I ask what scenario it is where you're wanting to have a transparent background for tabView content? 

It is recommended to layer TabView content or any Mica backdrop with `LayerOnMicaBaseAltFillColorDefault` to ensure that the content has proper colour contrast for accessibility.

**Comment by LaplaceStudio** [comment]
The key issue is that in a Page with Mica effects enabled, all other elements can display Mica effects normally, and only the content of TabView does not have Mica effects. Through analysis, it was found that it is possible that the background of the Content Presenter in TabView is not Transparent, resulting in the Mica effect on the underlying Page not being displayed at the top level. Therefore, the above code sets the background of the Content Presenter in TabView to be transparent. In this way, TabView can also display Mica effects when the parent page has Mica effects set. Also, what is LOBAFCD and how is it used?
