### ISSUE TITLE
Theme gets broken when rapidly changing themes...

### ISSUE THREAD

**Issue by WinUIDev** [microsoft/WinUI-Gallery#1511]
![Screenshot (37)](https://github.com/microsoft/WinUI-Gallery/assets/101691939/8b583cf7-9ba5-42b1-aaf8-bbe7bca265dc)
![Screenshot (38)](https://github.com/microsoft/WinUI-Gallery/assets/101691939/0b1f0033-90ea-4249-820b-64c30188f571)
![Screenshot (39)](https://github.com/microsoft/WinUI-Gallery/assets/101691939/b8e6e0b1-4094-4b91-82bb-8983b4e04a86)
![Screenshot (40)](https://github.com/microsoft/WinUI-Gallery/assets/101691939/f493707e-7cb2-4745-93a4-d85c53dca8ef)
![Screenshot (41)](https://github.com/microsoft/WinUI-Gallery/assets/101691939/23be01c8-b4a0-4de7-806d-ace7fd0bdaa9)
This problem occurs when you spam click light theme and dark theme alternating between them again and again and then stoppingon light theme.. sorry for bad explanation but i think you can understand

**Comment by HO-COOH** [comment]
Duplicate with my #1399

**Comment by marcelwgn** [comment]
Thank you for reporting this issue @WinUIDev and thank you for pointing out the dupe @HO-COOH, I'll be closing this as duplicate.
