### ISSUE TITLE
RichEditBox performance issues

### ISSUE THREAD

**Issue by tingjiangcao** [microsoft/WinUI-Gallery#1513]
### Which version of the app?

WinUI 3 Gallery

### Description

RichEditBox control

Selection text process (fixed start point, constantly changing end point), selection animation is not smooth.
In wpf and winui2 it's smooth.

This should be a winui3 problem, I also found it not smooth in my own application.
The reason why it doesn't feel smooth could be because of the selection speed or because the animation frame rate is not enough.

**Comment by marcelwgn** [comment]
Thank you for reporting this issue. Given that this seems to be a WinUI 3 issue, I'll close this issue. Please create an issue on their repository for this: https://github.com/microsoft/microsoft-ui-xaml
