### ISSUE TITLE
Filtering icons in Design guiance/Icons crashes the app

### ISSUE THREAD

**Issue by JuanMejiaVelez** [microsoft/WinUI-Gallery#1516]
### Which version of the app?

WinUI 3 Gallery

### Description

When filtering icons using the "Search icons" AutoSuggestTextBox the application crashes, either immediately with the first character or the in the second filter modification.

### Windows version

Insider Build (xxxxx)

**Comment by marcelwgn** [comment]
Hey, can you check if you are able to reproduce this issue when building the app from the main branch? In theory #1515 should have fixed this so it would be good to know if there is another cause for this crash.

**Comment by bogdan-patraucean** [comment]
@marcelwgn I reproduce the issue the following way:

- search for an icon
- copy the glyph
- try to search again
- app crashes

**Comment by marcelwgn** [comment]
Thank you for your input @bogdan-patraucean, did you also try to reproduce this using the app built from the latest commit on main branch or did you try it using the store version?

**Comment by bogdan-patraucean** [comment]
@marcelwgn, the store version.

**Comment by marcelwgn** [comment]
Allright, would you mind checking with a built version from the main branch to see if the fixes work @bogdan-patraucean or if the issue is still present?

**Comment by bogdan-patraucean** [comment]
@marcelwgn, the main branch seems to be working fine

**Comment by marcelwgn** [comment]
Awesome, thank you for testing this out and helping out that much @bogdan-patraucean! I'll be closing this issue then, since it seems the issue is fixed on main.
