### ISSUE TITLE
Text controls focus and scroll the sample pages when clicking on sample page background

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/WinUI-Gallery#1519]
### Which version of the app?

WinUI 3 Gallery

### Description

1. Go to `Implicit Transitions` page, scroll down to the last sample, expand the source code.
2. Click anywhere on the page, it will jump to a position near the top.

This issue is so weird and it did not happens on other pages. 

### Windows version

Windows 11 22H2 (22621)

**Comment by marcelwgn** [comment]
I think this is not an issue with the implicit page but rather all sample pages where there are focusable text inputs. For example this issue also occurs on the TextBox or NumberBox page if you resize the app to be very small, scroll to the bottom, and click on the page background.

**Comment by marcelwgn** [comment]
This also seems to have been an issue for quite some time: https://github.com/microsoft/microsoft-ui-xaml/issues/597
