### ISSUE TITLE
Remove DataGrid Page

### ISSUE THREAD

**Issue by karkarl** [microsoft/WinUI-Gallery#1525]
### Which version of the app?

WinUI 3 Gallery

### Description

#1454

**Comment by w-ahmad** [comment]
May be it can stay since a TableView control is planned in [WindowsAppSDK](https://github.com/microsoft/WindowsAppSDK/blob/main/docs/roadmap.md) and this page can be used for it.

**Comment by HEIC-to-JPEG-Dev** [comment]
> May be it can stay since a TableView control is planned in [WindowsAppSDK](https://github.com/microsoft/WindowsAppSDK/blob/main/docs/roadmap.md) and this page can be used for it.

There is no release date for that though - potentially February 2025.

I say remove it, it isn't a WinUI native control
