### ISSUE TITLE
Crashes when clicking Icons + using search/filter

### ISSUE THREAD

**Issue by avsteele** [microsoft/WinUI-Gallery#1530]
### Which version of the app?

WinUI 3 Gallery

### Description

Open app -> Design guidance -> icons

1) Click an icon
2) Type in the search bar
App Crashes

Event Viewer items relating to the crash are attached
[winui_crash_log_error.txt](https://github.com/microsoft/WinUI-Gallery/files/15142550/winui_crash_log_error.txt)
[winui_crash_log_info.txt](https://github.com/microsoft/WinUI-Gallery/files/15142551/winui_crash_log_info.txt)

### Windows version

Windows 11 23H2 (22631)

**Comment by RaceAlex69** [comment]
Same Problem

**Comment by karkarl** [comment]
Resolving as dupe of #1500
