### ISSUE TITLE
Voice Access commang like "Delete that" is not working wit PasswordBox

### ISSUE THREAD

**Issue by samdsmx** [microsoft/WinUI-Gallery#1534]
I ### Which version of the app?

WinUI 3 Gallery

### Description

I test the voice command with TextBox control and works as expected. But not for PasswordBox when the password is not reveal. If 
PasswordRevealMode is true the "delete that" command works.  

### Screenshots

[delete that.webm](https://github.com/microsoft/WinUI-Gallery/assets/5838427/3a9d793a-774f-4a55-b5ea-11f1b2fffb0f)

![image](https://github.com/microsoft/WinUI-Gallery/assets/5838427/a9d4ca36-2f8f-481e-b6e0-01d0477fc3b0)

### Windows version

Windows 11 23H2 (22631)

**Comment by chrisglein** [comment]
Looks like you opened an issue on the core platform here: https://github.com/microsoft/microsoft-ui-xaml/issues/9615
Closing this duplicate.
