### ISSUE TITLE
Change how source codes (C#/XAML) are displayed

### ISSUE THREAD

**Issue by ghost1372** [microsoft/WinUI-Gallery#1535]
### Issue type

enhancement

### Which version of the app?

WinUI 3 Gallery

### Description

Currently displaying codes is too long and confusing.
Using Pivot/selector bar can shorten the code and make it easier to use.

this Currently design
![image](https://github.com/microsoft/WinUI-Gallery/assets/9213496/22da81d1-cf93-40ff-b70c-fc878f4998ba)

I have used pivot for my app and it is as follows
![Screenshot 2024-05-08 203240](https://github.com/microsoft/WinUI-Gallery/assets/9213496/6aa5fd92-6c5f-4414-b0ad-35271b553c9c)

@karkarl  If approved, I can create a PR for this.

### Windows version

Insider Build (xxxxx), Windows 11 24H2 (26052), Windows 11 23H2 (22631), Windows 11 22H2 (22621), Windows 11 21H2 (22000), Windows 10 22H2 (19045), November 2021 Update/21H2 (19044), May 2021 Update/21H1 (19043), October 2020 Update/20H2 (19042), October 2018 Update/RS5 (17763)

**Comment by Jay-o-Way** [comment]
I've learned that [Pivot is deprecated](https://github.com/microsoft/WinUI-Gallery/pull/1508#issuecomment-2013992248), but **SelectorBar** is _almost_ identical.

**Comment by niels9001** [comment]
@karkarl I think this makes sense? We do the same thing in the Windows Community Toolkit Gallery:

![image](https://github.com/microsoft/WinUI-Gallery/assets/9866362/0c8e6eb8-3baa-41e3-aa3b-5198e3c2536f)

**Comment by ghost1372** [comment]
@karkarl can we use SwitchPresenter from communityToolkit? (nuget package) or can we just copy-paste actual [source code](https://github.com/CommunityToolkit/Windows/tree/main/components/Primitives/src/SwitchPresenter) into gallery repo? 

here we have an excelent example which uses selectorbar with SwitchPresenter 
https://github.com/CommunityToolkit/Windows/blob/main/components/Segmented/samples/SegmentedSwitchPresenterSample.xaml
