### ISSUE TITLE
Add searchable tags to Icons

### ISSUE THREAD

**Issue by AndrewKeepCoding** [microsoft/WinUI-Gallery#1544]
### Issue type

enhancement

### Which version of the app?

WinUI 3 Gallery

### Description

In the **Icons** page, you can search by `Name` and `Unitcode point`. It'd be easier to find icons if they had tags that represent the symbol or its meaning.

For example, the `Color` icon, which is a palette, could also be able to be found with [palette] or [theme].

**Comment by AndrewKeepCoding** [comment]
If this is a change that could be considered as enhancement, I'd be happy to create PR for this.

**Comment by Jay-o-Way** [comment]
Sounds like a fair idea. What would be your solution? Adding a "tag" field in WinUIGallery/DataModel/IconsData.json ?

**Comment by AndrewKeepCoding** [comment]
Yes. Something like this:

```json
{
  "Code": "E790",
  "Name": "Color",
  "Tags": ["Palette", "Theme"]
},
```

But since there are too many icons, I'm thinking on implementing the searching logic and some simple tags. The rest can be implemented/improved by in the future.

**Comment by karkarl** [comment]
That's a great idea! Your contribution is very much welcomed.

**Comment by AndrewKeepCoding** [comment]
I'll create a PR when it's ready.
