### ISSUE TITLE
Minor Inconsistency

### ISSUE THREAD

**Issue by iediagcmd** [microsoft/WinUI-Gallery#1556]
The "Send feedback" button appears to use a Segoe MDL2 icon.
![image](https://github.com/microsoft/WinUI-Gallery/assets/171427875/1121ff77-0ece-4f17-aa50-51790da4899d)

**Comment by niels9001** [comment]
@iediagcmd I'm assuming you are on Windows 10? If so, that would be expected; Segoe Fluent Icons ships as part of Windows 11 and replaces MDL2 as the default icon family.

On my Windows 11 machine, this is what it looks like (as you can see the other icons are different as well):

![image](https://github.com/microsoft/WinUI-Gallery/assets/9866362/b82a11e2-ee3b-4199-a522-a416aa3a83d0)
