### ISSUE TITLE
SplitView Page - Mismatch between source code and rendered example

### ISSUE THREAD

**Issue by fabianoriccardi** [microsoft/WinUI-Gallery#1587]
### Which version of the app?

WinUI 3 Gallery

### Description

The source code contains a Settings "tab" but the rendered content doesn't display it (see screenshot below).

Other than the obvious mismatch between rendered content and source code, IMHO, this similarity between SplitView and NavigationView may be confusing for a learner, so I think it should be deleted.

Here the source code:

```
         <StackPanel Orientation="Horizontal" Grid.Row="2" Margin="14,24,0,24" >
                <SymbolIcon Symbol="Setting" />
                <TextBlock Text="Settings" Margin="24,0,0,0" VerticalAlignment="Center"/>
            </StackPanel>
```

### Screenshots

![Imm](https://github.com/user-attachments/assets/63bae3f3-c3ec-49cd-b0d6-cab554e4857d)

### Windows version

Windows 10 22H2 (19045)

**Comment by Zakariathr22** [comment]
@karkarl This issue can now be closed.
