### ISSUE TITLE
Long text not well displayed in TextBox

### ISSUE THREAD

**Issue by JMLCelec** [microsoft/WinUI-Gallery#1596]
### Which version of the app?

WinUI 3 Gallery

### Description

After 12108 lines in a TextBox, the text is not visible but seems to be taken into account in selection.

### Screenshots

![image](https://github.com/user-attachments/assets/e932fb66-f62c-4bc2-9017-81c70fdb0865)

**Comment by HO-COOH** [comment]
This is more like a winui issue. You should probably file issue [there](https://github.com/microsoft/microsoft-ui-xaml)
