### ISSUE TITLE
Did you forget to add an app icon to the WinUI 3 Gallery main application?

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/WinUI-Gallery#1600]
### Which version of the app?

WinUI 3 Gallery

### Description

Did you forget to add an app icon to the WinUI 3 Gallery main application?

### Screenshots

![{A7295769-EAFD-4DFF-BF89-AA699168FE38}](https://github.com/user-attachments/assets/f7d5bfff-f5cb-42a6-8005-74756206db5d)

### Windows version

Windows 11 24H2 (26052)

### Additional context

None

**Comment by MGGSK** [comment]
The .exe file doesn't need an icon. (by default) WinUI apps use the package icon for the app and not the exe icon. Most apps don't have an exe icon.

**Comment by Gaoyifei1011** [comment]
> The .exe file doesn't need an icon. (by default) WinUI apps use the package icon for the app and not the exe icon. Most apps don't have an exe icon. Edit: The .exe file can't even be launched directly so an exe icon is useless.

But I don't think so. First, Winui 3 is a desktop application, and UWP is a packaged application. In the task Manager, the Winui 3 desktop program shows the icon of the application instead of the packaged application icon, which does not quickly locate the application by the icon in the Task Manager. Second, Microsoft's other official packaging applications, Dev home, drawing and other software, they have set up application ICONS, so I think Winui 3 gallery should add application ICONS
然而我却不是这样认为。首先，Winui 3 是一个桌面程序，UWP 是一个打包后的应用。在任务管理器中，Winui 3 桌面程序显示的是应用程序的图标，而不是打包应用程序的图标，这并不能在任务管理器中通过图标快速定位应用程序。其次，微软官方的其他打包应用，Dev home，画图等等其他软件，他们都设置了应用程序图标，所以我认为应该给 Winui 3 gallery 添加上应用程序图标

**Comment by MGGSK** [comment]
> > The .exe file doesn't need an icon. (by default) WinUI apps use the package icon for the app and not the exe icon. Most apps don't have an exe icon. Edit: The .exe file can't even be launched directly so an exe icon is useless.
> 
> But I don't think so. First, Winui 3 is a desktop application, and UWP is a packaged application. In the task Manager, the Winui 3 desktop program shows the icon of the application instead of the packaged application icon, which does not quickly locate the application by the icon in the Task Manager. Second, Microsoft's other official packaging applications, Dev home, drawing and other software, they have set up application ICONS, so I think Winui 3 gallery should add application ICONS 然而我却不是这样认为。首先，Winui 3 是一个桌面程序，UWP 是一个打包后的应用。在任务管理器中，Winui 3 桌面程序显示的是应用程序的图标，而不是打包应用程序的图标，这并不能在任务管理器中通过图标快速定位应用程序。其次，微软官方的其他打包应用，Dev home，画图等等其他软件，他们都设置了应用程序图标，所以我认为应该给 Winui 3 gallery 添加上应用程序图标 ![{92920F28-79A1-421F-AE98-5DFB73BE5CC2}](https://private-user-images.githubusercontent.com/49179966/357338509-702152e8-92cf-4201-947d-4fb1524d6b72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NjA5NDQsIm5iZiI6MTcyMzU2MDY0NCwicGF0aCI6Ii80OTE3OTk2Ni8zNTczMzg1MDktNzAyMTUyZTgtOTJjZi00MjAxLTk0N2QtNGZiMTUyNGQ2YjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDE0NTA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYWZhMGIzMjdiNmY5ZjE0ZDE0MGMzZTBiYTVmMjAzMzU5Y2Q0ZDM4NjdjYzdkMmE4OTQ0NTc1MjQ5MWI3MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6saNfVWOEvUdNTiCXuwZBiNkQWvbPO0X8j3ADaXPOhc)

First: WinUI 3 apps are also packaged
Second: What I meant by "useless" was applying it as the app exe file icon but it is useful in the taskbar because WinUI is weird (with packaged taskbar icons).
Third: I think it would be good if an exe icon was added because using an png file as a icon in the taskbar doesn't look good (no transparency).

**Comment by HEIC-to-JPEG-Dev** [comment]
The icon should be added - Windows taskbar needs it to display properly
![Image](https://github.com/user-attachments/assets/5a3e6951-7aa6-447d-a715-86207cfc6592)

**Comment by MGGSK** [comment]
> The icon should be added - Windows taskbar needs it to display properly ![Image](https://github.com/user-attachments/assets/5a3e6951-7aa6-447d-a715-86207cfc6592)

I already added the icon but they didn't close this issue. https://github.com/microsoft/WinUI-Gallery/pull/1604

**Comment by HEIC-to-JPEG-Dev** [comment]
> > The icon should be added - Windows taskbar needs it to display properly ![Image](https://github.com/user-attachments/assets/5a3e6951-7aa6-447d-a715-86207cfc6592)
> 
> I already added the icon but they didn't close this issue. [#1604](https://github.com/microsoft/WinUI-Gallery/pull/1604)

It's not in the current release either

**Comment by MGGSK** [comment]
> > > The icon should be added - Windows taskbar needs it to display properly ![Image](https://github.com/user-attachments/assets/5a3e6951-7aa6-447d-a715-86207cfc6592)
> > 
> > 
> > I already added the icon but they didn't close this issue. [#1604](https://github.com/microsoft/WinUI-Gallery/pull/1604)
> 
> It's not in the current release either

It will be in the next update.

**Comment by Zakariathr22** [comment]
@karkarl This issue can now be closed.

**Comment by Zakariathr22** [comment]
@karkarl @niels9001 
Sorry about this, but it looks like the issue still persists in the store version, even though it was resolved in the repo a while ago. Maybe we should consider reopening the issue.

![Image](https://github.com/user-attachments/assets/4494036d-718b-4471-bf64-a462c64534b7) ![Image](https://github.com/user-attachments/assets/65cbbb01-541e-42e8-b636-59ed7c942443)

**Comment by skalsi-pexip** [comment]
This is live bug. But also I think its clearly a bug in WinUI3 or Appx Manifiest as so many Winui-3 devs are experiencing this

<img width="255" height="214" alt="Image" src="https://github.com/user-attachments/assets/77e1fefb-b6f6-4ef1-b32e-7d1c1213ebf7" />

**Comment by HEIC-to-JPEG-Dev** [comment]
I know this is closed. It is not a bug as such, just bad tooling. If you set an icon for an app, it should be represented everywhere, in WinUI you have to set an icon (ico & png) in 3 different places so that it shows in the taskbar, preview, expanded taskbar, task viewer, process viewer and sub-process exe view.
