### ISSUE TITLE
ScrollView - Missing C# code in sample "Programmatic scroll with custom animation"

### ISSUE THREAD

**Issue by szv** [microsoft/WinUI-Gallery#1603]
### Which version of the app?

WinUI 3 Gallery

### Description

The sample "Programmatic scroll with custom animation" on the _ScrollView_ page shows the XAML code but not the required C# code.

### Screenshots

![image](https://github.com/user-attachments/assets/d549c3d3-f9a6-4799-8d70-c63760927614)

**Comment by Zakariathr22** [comment]
@karkarl This issue can now be closed.

**Comment by szv** [comment]
Seems to be solved by #1616, but still requires to be published to the store.
