### ISSUE TITLE
WinUI 3 Gallery Crash in ```AutoSuggestBox``` Page

### ISSUE THREAD

**Issue by ShimizuTheLotus** [microsoft/WinUI-Gallery#1609]
### Which version of the app?

WinUI 3 Gallery

### Description

In the page of ```AutoSuggestBox```, if we type something in the second ```AutoSuggestBox``` and then press ```Enter```, the app will crash.

**Comment by AndrewKeepCoding** [comment]
Duplicate of #1581 which was closed with #1582.

**Comment by marcelwgn** [comment]
Thank you @ShimizuTheLotus none the less and thank you @AndrewKeepCoding for stepping in!
