### ISSUE TITLE
There is very little information for learning winUI3 with C++, so it is strongly recommended to launch the C++ version

### ISSUE THREAD

**Issue by shuilan0066** [microsoft/WinUI-Gallery#1624]
### Issue type

enhancement

### Which version of the app?

WinUI 3 Gallery

### Description

There is very little information for learning winUI3 with C++, so it is strongly recommended to launch the C++ version。
There are no examples. You have to figure it out by yourself. Even a small problem may take a lot of time.
Since winui3 c++ functions are provided, why not provide more examples of c++ learning UI3?

So please provide a C++ version as soon as possible to encourage C++ users to learn UI3

**Comment by karkarl** [comment]
Thanks for the feedback! This is a suggestion we have gotten before, and unfortunately it will take a lot of resources we don't have to populate the samples with its C++ equivalent. 

As such, I am closing this issue as it is not planned.
