### ISSUE TITLE
WinUI-Gallery won't build with .NET 8 on Windows 10 x64

### ISSUE THREAD

**Issue by ScooterTech** [microsoft/WinUI-Gallery#1626]
### Which version of the app?

WinUI 3 Gallery

### Description

Build fails with:
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	NETSDK1083	The specified RuntimeIdentifier 'win10-x86' is not recognized. See https://aka.ms/netsdk1083 for more information.	WinUIGallery.DesktopWap	C:\Program Files\dotnet\sdk\8.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	90		

### Windows version

Windows 10 22H2 (19045)

### Additional context

From what I can google this has something to do with the changes made in .NET 8.

**Comment by MGGSK** [comment]
Try building the app for x64 and not x86. If that doesn't work try using the WinUIGallery.sln file instead of the WinUIGallery.DesktopWap.sln file to build the app.

**Comment by karkarl** [comment]
Hopefully MGGSK's response suffices as a workaround. Closing this issue.
