### ISSUE TITLE
Loading NavigationView causes crash

### ISSUE THREAD

**Issue by Fabi12345** [microsoft/WinUI-Gallery#1635]
### Which version of the app?

WinUI 3 Gallery

### Description

The app crashes when you switch between the "NavigationView" (from the main app, not the sample) item and any other item in the navigation list. You can provoke/accelerate that issue by clicking many times and very fast on that item, it stops responding and then causes the app to crash.

Edition: Windows 10 Education
Version: 22H2
Systembuild: 19045.5011
Windows Feature Experience Pack 1000.19060.1000.0

**Comment by karkarl** [comment]
Thanks for filing this bug. Resolving as dupe of #1206
