### ISSUE TITLE
Support for Fluent System Icons

### ISSUE THREAD

**Issue by Natriss** [microsoft/WinUI-Gallery#1662]
### Issue type

enhancement

### Which version of the app?

WinUI 3 Gallery

### Description

Would it be possible to have an extra section underneath the Fluent Icons Library to show a similar list but for the Fluent System Icons?
It can also have an accordion giving the user information where to get the Fluent System Icons.

**Comment by Zakariathr22** [comment]
@marcelwgn @niels9001 
Do you think it would be a good idea to implement this?

If so, I’ve prepared the data file [FluentSystemIconsData.json](https://github.com/user-attachments/files/18138188/FluentSystemIconsData.json). The glyphs in this file are derived from [FluentSystemIcons-Resizable.ttf](https://github.com/microsoft/fluentui-system-icons/blob/main/fonts/FluentSystemIcons-Resizable.ttf) and follow a structure similar to [IconsData.json](https://github.com/microsoft/WinUI-Gallery/blob/main/WinUIGallery/DataModel/IconsData.json).

I realized this would involve a lot of work, so I wanted to get your input before proceeding with any changes.
I look forward to know your thoughts.

**Comment by niels9001** [comment]
Segoe Fluent Icons (= the iconset that ships with Windows 11) is a subset of Fluent System Icons, with some additional Windows-only icons I believe.

It is the default set that ships with Windows. Therefore, it makes sense to highlight this in the Windows app development documentation and tools like this.

Fluent System Icons does not:

- It has little to do with Windows, as it's not a font that ships inbox. It's basically 'just another' icon font that a developer would need to manually embed into their app.
- It gets updated very frequently, so it would be hard to catch up and stay up to date.

I'd say it does not fall in the scope of WinUI Gallery, and ideally, Fluent System Icons would have an icon tool based on their set, not bound to Windows/WinUI.

@marcelwgn @karkarl thoughts?
