### ISSUE TITLE
`Color > Hight Contrast`: Incorrect Highlighting on Theme Toggle

### ISSUE THREAD

**Issue by Zakariathr22** [microsoft/WinUI-Gallery#1671]
### Which version of the app?

WinUI 3 Gallery

### Steps to Reproduce:
1. Navigate to the "Color > Hight Contrast".
2. Toggle the theme using the theme switch button at the top right corner.
3. Observe the changes in the text highlighting.

### Screenshots
 **Before Toggling the theme**
![Image](https://github.com/user-attachments/assets/d89959d1-b098-4ca5-ba36-f3bde7baad9b)

**After Toggling the theme**
![Image](https://github.com/user-attachments/assets/45d2f354-8fdb-4761-b7f0-bcdb1bbec69e)

### Expected Behavior:
The text should maintain consistent highlighting and text visibility regardless of the theme, with proper contrast between the background and text.

### Actual Behavior:
After toggling the theme, the text become poorly highlighted, making it less readable and causing visual inconsistency.

**Comment by Zakariathr22** [comment]
> Got the same on pages: Iconography, Spacing, ColorPaletteResources, to name a few

The issue in 'SpacingPage' was resolved in #1639

**Comment by Jay-o-Way** [comment]
FYI @marcelwgn

**Comment by Jay-o-Way** [comment]
> Spacing and Iconography were fixed by the PR

That's interesting, because that PR only changes one file...

**Comment by marcelwgn** [comment]
I guess the Iconography page was fixed by some other changes then. I think there were some changes to finding the element to change theme at some point but I cant remember the PR.
