### ISSUE TITLE
Declutter page header

### ISSUE THREAD

**Issue by niels9001** [microsoft/WinUI-Gallery#1678]
There is a lot of information currently displayed at the top of each control header. E.g. `Namespace` and `Inheritance` information is tertiary information that is also listed in the WinUI documentation.

**Comment by Jay-o-Way** [comment]
One may suggest that this infobutton (icon or text) can also be placed in the **PageHeader**, in line with those other buttons. Takes away that awkwardness of aligning icons and text, as you put it :)

![Image](https://github.com/user-attachments/assets/760aed9c-39a1-410f-883f-21add1169f3d)

Also, issue #1503 comes to mind.
