### ISSUE TITLE
⛓️‍💥 Broken links - MS UI XAML repo: directory to controls is changed

### ISSUE THREAD

**Issue by Jay-o-Way** [microsoft/WinUI-Gallery#1681]
### Which version of the app?

WinUI 3 Gallery

### Description

Looks like the repo uses a new structure: they added folder `/src/` to the path:
`https://github.com/microsoft/microsoft-ui-xaml/tree/winui3/release/1.6-stable/src/controls/dev/`
Now, all links to "control source code" are broken.

P.S. what's the difference between the `main` branch?

**Comment by niels9001** [comment]
Thanks jay-o-way for catching this!!

Some context:

The WinUI repo moved the actual controls source code to the `main` branch, as it should be. Before that, the code was in specific release branches. As a result, we had to link to each source code file from within the Gallery.

Now that all the stable code lives in `main`, we can directly link to that.
