### ISSUE TITLE
Icon details are not displayed anymore on iconography page in Gallery version 2.5.0.0

### ISSUE THREAD

**Issue by DavidM29** [microsoft/WinUI-Gallery#1688]
### Which version of the app?

WinUI 3 Gallery

### Description

Icon details like:

- Icon name
- Unicode point
- Text glyph
- Code glyph
- XAML
- C#

Do not display values anymore in the latest WinUI Gallery version.

### Screenshots

![Image](https://github.com/user-attachments/assets/df89cbb2-522b-49ce-86ad-670059463699)
![Image](https://github.com/user-attachments/assets/1f6c7f5e-5b02-4a89-90cb-0d92afbd4ea8)

### Windows version

Windows 11 22H2 (22621)

**Comment by AndrewKeepCoding** [comment]
This was supposed to be fixed with #1668.
