### ISSUE TITLE
Iconography bug

### ISSUE THREAD

**Issue by GabrielePepe** [microsoft/WinUI-Gallery#1690]
### Which version of the app?

WinUI 3 Gallery

### Description

I can't view any information of a icon in iconography section

### Screenshots

![Image](https://github.com/user-attachments/assets/58f555d4-6d52-49f9-93c7-cd433419cd47)

**Comment by AndrewKeepCoding** [comment]
Duplicate of #1688.

**Comment by Zakariathr22** [comment]
@marcelwgn 
This is a duplicate of #1688 and has been resolved through #1668

**Comment by Jay-o-Way** [comment]
OMG so sad the fix didn't make it in the 2.5.0 release :(

**Comment by Jay-o-Way** [comment]
@marcelwgn please tell me this warrants a hotfix. At the moment, the page is useless in public release (!)

**Comment by marcelwgn** [comment]
@jay-o-way We are working on releasing a new version in the next few days :)
