### ISSUE TITLE
Design guidance -> Spacing

### ISSUE THREAD

**Issue by PRZEMPM** [microsoft/WinUI-Gallery#1691]
### Which version of the app?

WinUI 3 Gallery 2.4.3.0

### Description

Navigation View ->Design guidance -> Spacing
After clicking the button in the upper right corner "Toggle team", the application does not properly adjust the contrast of the text to the background and buttons, because they are practically invisible.

### **Before:**
![Image](https://github.com/user-attachments/assets/6fac6c45-fb0f-49ee-9162-25688ab6a6a5)
### **After:**
![Image](https://github.com/user-attachments/assets/df2ed46c-c797-4e98-9a29-b27e49d82c8f)

### Windows version

Windows 10 22H2 (19045)

**Comment by Jay-o-Way** [comment]
@Zakariathr22 looks like we missed a page?

**Comment by Zakariathr22** [comment]
@marcelwgn 
This is a duplicate of #1637 and has been resolved through #1639
