### ISSUE TITLE
What happened to the icons and their details?

### ISSUE THREAD

**Issue by HotCakeX** [microsoft/WinUI-Gallery#1702]
### Which version of the app?

WinUI 3 Gallery

### Description

There is 0 details about the icons in version 2.5, and i'm not sure how to downgrade the app since there is no installer package provided and i installed it from store.

### Screenshots

![Image](https://github.com/user-attachments/assets/58ab3366-0010-4fe1-8282-440afa21750a)

### Windows version

Windows 11 24H2 (26052)

**Comment by AndrewKeepCoding** [comment]
Duplicate of #1688.

**Comment by Jack251970** [comment]
Really annoy me a lot.

**Comment by niels9001** [comment]
We are trying to get a fix out ASAP. Closing this as duplicate.
