### ISSUE TITLE
Complet code of all samples of the XAML Controls Gallery

### ISSUE THREAD

**Issue by SEAFromJahu** [microsoft/WinUI-Gallery#309]
I would like to use some of XAML controls that is on the XAML Controls Gallery.
How can I have a complete code example from each of control that is on XAML Control Gallery?
Is that possible???
I'm trying to build some of then on Visual Studio but ... lack some code that XAML Controls Gallery dont show on documentation.
And I can't go ahead with my learning curve.
If there is a way to have the complete code from each control (XAML/C#/Classes...) please let me know how.
Regards,
Sergio Eduardo Antonio

**Comment by stmoy** [comment]
Hi @SergioEduardoAntonio! 

Each sample includes a small snippet of code, but if you're looking for a more complete sample, you'll need to look at the code file itself. For example, if you wanted to see the complete sample for ComboBox, you can go to the ComboBox xaml and cs files:
- Xaml File: https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/ControlPages/ComboBoxPage.xaml
- C# File:  https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/ControlPages/ComboBoxPage.xaml.cs

Each of the samples live in this folder: https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/ControlPages

In terms of documentation, every page also has links to API and Guidelines links. For example, the ComboBox Gallery page has links to the following pages:
- API: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.combobox
- Guidance: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/combo-box

Are there specific controls that you'd like to see more complete samples for?

**Comment by SergioEduardoAntonio** [comment]
Hi Steven Moyes,

First of all I so glad  with your answers,

Thanks so much for your readiness, and I’m sorry about my poor understand of XAML technology but I promises that I will learn it.

I’m trying to develop a project with need to use a List View like WhatsApp where each record has a column with a photo + another column with one or two lines of text(TextBlocks) + d  the last column with another two lines with a short text in two TextBlock too.

Each of these tree columns need to be responsive with mouse clicks to change the view to another page that corresponding with the column and the record that has the tree colums contents.

Than when I so  inside XAML Controls Gallery>Collection>the Updated ListView, “ListViews with Drag, Drop and Reordering Support, I sad “Here is what I need to learn” to do with my project.
Then when I read all the information I stopped on many doubts, I tried to construct the same on Visual Studio 2019 Community but…without success.

If you have the complete code from the ListView that is inside XAML Controls Gallery that I can study and do changes to do what I need to do on my project I be so glad.

Presently I’m unemployed with 63 years old and I’m trying to have a project to sell on the Market.

Again I’m sorry about my poor English.

Regards for your attention,

Sergio Eduardo Antonio

De: Steven Moyes <notifications@github.com>
Enviada em: segunda-feira, 6 de janeiro de 2020 18:40
Para: microsoft/Xaml-Controls-Gallery <Xaml-Controls-Gallery@noreply.github.com>
Cc: Sergio Eduardo Antonio <sea-56@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [microsoft/Xaml-Controls-Gallery] Complet code of all samples of the XAML Controls Gallery (#309)


Hi @SergioEduardoAntonio<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSergioEduardoAntonio&data=02%7C01%7C%7C973115578e2644c9132308d792f0ee11%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637139435784315459&sdata=pfEaOuASDf%2F8d0509n4EgSKM60%2F7RyR4PBQdKt7b%2B9I%3D&reserved=0>!

Each sample includes a small snippet of code, but if you're looking for a more complete sample, you'll need to look at the code file itself. For example, if you wanted to see the complete sample for ComboBox, you can go to the ComboBox xaml and cs files:

  *   Xaml File: https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/ControlPages/ComboBoxPage.xaml<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FXaml-Controls-Gallery%2Fblob%2Fmaster%2FXamlControlsGallery%2FControlPages%2FComboBoxPage.xaml&data=02%7C01%7C%7C973115578e2644c9132308d792f0ee11%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637139435784315459&sdata=4NlFLkiumIzKFDmyvx%2B9FS84gB55m1iM6VSCnQsp0uQ%3D&reserved=0>
  *   C# File: https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/ControlPages/ComboBoxPage.xaml.cs<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FXaml-Controls-Gallery%2Fblob%2Fmaster%2FXamlControlsGallery%2FControlPages%2FComboBoxPage.xaml.cs&data=02%7C01%7C%7C973115578e2644c9132308d792f0ee11%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637139435784325463&sdata=ZqqjymqrsZ4Pu8WLROfwtZXopa2THDn1VHviLKN9JEQ%3D&reserved=0>

Each of the samples live in this folder: https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/ControlPages<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FXaml-Controls-Gallery%2Fblob%2Fmaster%2FXamlControlsGallery%2FControlPages&data=02%7C01%7C%7C973115578e2644c9132308d792f0ee11%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637139435784325463&sdata=IN8DYdjqrm6%2BR%2Fl1xAC0B13HU5aD1MKe8XiksJ1GxzE%3D&reserved=0>

In terms of documentation, every page also has links to API and Guidelines links. For example, the ComboBox Gallery page has links to the following pages:

  *   API: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.combobox<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fuwp%2Fapi%2Fwindows.ui.xaml.controls.combobox&data=02%7C01%7C%7C973115578e2644c9132308d792f0ee11%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637139435784335468&sdata=euTbrXJp5Gjt9kB%2Ft9y0MmPqt03DMImpgUDP%2FWdy9Jo%3D&reserved=0>
  *   Guidance: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/combo-box<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fwindows%2Fuwp%2Fdesign%2Fcontrols-and-patterns%2Fcombo-box&data=02%7C01%7C%7C973115578e2644c9132308d792f0ee11%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637139435784335468&sdata=dQzdw5pYH0Oy2w0w3SVE227k5fgXp5TC5BAL31aC7oA%3D&reserved=0>

Are there specific controls that you'd like to see more complete samples for?

**Comment by stmoy** [comment]
Hi @SergioEduardoAntonio - thank you for providing more information. 

The complete ListView sample can be found in the following files:
- XAML: https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/ControlPages/ListViewPage.xaml
- C#: https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/ControlPages/ListViewPage.xaml.cs

@anawishnoff was the person who wrote these ListView samples and might be able to provide more information.

The Xaml Controls Gallery is a big app with a bunch of code/infrastructure and it isn't a great "getting started" app. I'd recommend checking out the following resources which might also be useful: 
- ListView Drag and Drop Complete Sample: https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/XamlDragAndDrop
- Win10 App development for absolute beginners series: https://channel9.msdn.com/Series/Windows-10-development-for-absolute-beginners
- UWP Get Started Guide: https://docs.microsoft.com/windows/uwp/get-started/

**Comment by joaosantana** [comment]
The Win10 App development for absolute beginners series is very³ outdated, but it's still a good point to start out, @SergioEduardoAntonio.

**Comment by chingucoding** [comment]
In addition to the links @stmoy sent, there is also a link to the sample pages source code on every sample page now to make it easier to see the full source code for a sample.

**Comment by chingucoding** [comment]
@SEAFromJahu Have your questions been answered and can this issue be closed? 😃
