### ISSUE TITLE
TwoPaneView sample

### ISSUE THREAD

**Issue by YuliKl** [microsoft/WinUI-Gallery#358]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [x] New sample
- [ ] Addition to existing sample
- [ ] Modification to existing sample

**Describe the sample**

We should include TwoPaneView in the Controls Gallery, probably in the Layout section.

**Comment by stmoy** [comment]
Any thoughts on exactly which scenarios to cover?

**Comment by YuliKl** [comment]
> Any thoughts on exactly which scenarios to cover?

I believe that although TwoPaneView is primarily solving some challenges for [dual-screen](https://docs.microsoft.com/en-us/dual-screen/introduction) devices, it's a useful control for [master-details](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/master-details) scenarios on single screen as well. Happy to have @predavid chime in with specifics.

**Comment by karkarl** [comment]
Dual screen devices are no longer being invested in, so this sample is no longer needed. Closing.
