### ISSUE TITLE
Narrator reads contents of the previous page.

### ISSUE THREAD

**Issue by YuliKl** [microsoft/WinUI-Gallery#379]
**Describe the bug**

When navigating to/from Animated Visual Player page, Narrator focus gets stuck on that page.

**Steps to reproduce the bug**

1. Launch XAML Controls Gallery and run Narrator.
2. Activate Animated Visual Player from home page.
3. Use "win+backspace" to go back to the previous page i.e homepage.
4. Now item navigate and observe narrator's description.

**Expected behavior**

Narrator should item navigate and read the contents of the current page.

**Actual behavior**

Narrator reads the contents of the previous page.

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/76574940-096b3f80-647b-11ea-8e1b-b6179c4952bf.png)

**Version Info**

Gallery version (found on Settings page): 

1.2.13.0

**Additional context**

I have not been able to repro this strange behavior with any other page in the app. 

Copied from [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/25441112)

**Comment by niels9001** [comment]
Not reproduceable on the latest version.
