### ISSUE TITLE
[Feature request] Rebrand this repo and app to 'WinUI Controls Gallery'

### ISSUE THREAD

**Issue by niels9001** [microsoft/WinUI-Gallery#386]
## Describe the problem this feature would solve
The current name of this repo and application have no connection to WinUI. Wouldn't it make sense to rebrand this repo (and app) to something that is inline with WinUI?

Since we're also looking into modernizing the app icon (#374) , this could be part of that rebranding!

## Describe the solution
Potential names:
WinUI Controls Gallery

**Comment by Felix-Dev** [comment]
To add to this, we should also add a link to this product on the [WinUI website](https://microsoft.github.io/microsoft-ui-xaml/#devControl). If by then we can refer this product as the WinUI Controls Gallery, even better! FYI @anawishnoff

**Comment by anawishnoff** [comment]
@Felix-Dev Yes, that's on my to-do list! 👍

**Comment by bpulliam** [comment]
Completed with the slight change to remove the word Controls, since the app is showing samples for Mica, Titlebar, Multiple Windows, and other aspects of WinUI that aren't strictly controls.  Thanks for the suggestion!
