### ISSUE TITLE
TabView Tearout sample Issues

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/WinUI-Gallery#399]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] New sample
- [ ] Addition to existing sample
- [x] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**
TabView (bottom multi-windowing example)

**Is your sample request related to a problem? Please describe it**
1. The secondary windows created when tearing off tabs, don't have the TitleBar area set right (so it's harder to click add/remove buttons or drag out tabs)
2. You can't place the final tab of a window back into another window (like Edge)
3. Issue sometimes pulling out a tab from a window (seemed to happen when it was the only one in a window before a new tab was added)
4. Should show drop targets of tab content and titlebar as well.

**Additional context**

**Comment by michael-hawker** [comment]
🦙 For 4) you could show as the Drag starts, put a 'cover' on all the other target windows over all the content that can act as a simple one-stop drop target and just have like a fluent effect and 'drop tab here' type text or something. 😊

**Comment by demberto** [comment]
Also the TabView doesn't seem to recognize the Close, Minimize etc. buttons on top right. The tabs' size isn't properly set.
![image](https://user-images.githubusercontent.com/65948403/91632212-00f0cc00-e9fd-11ea-9df3-01807f8c873a.png)

It gets fixed after going full screen and again restoring back to earlier size.
![image](https://user-images.githubusercontent.com/65948403/91632245-3990a580-e9fd-11ea-9e21-49eaf3463db2.png)

**Comment by karkarl** [comment]
It seems every issue listed above no longer repros except for these two related issue:

- [ ] 2. You can't place the final tab of a window back into another window (like Edge)
- [ ] 3. Issue sometimes pulling out a tab from a window (seemed to happen when it was the only one in a window before a new tab was added)

It seems File Explorer is able to achieve this behaviour, so our sample should be updated.
