### ISSUE TITLE
With Hierarchy, reverse navigation animation fails sometimes

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/WinUI-Gallery#404]
See comment in [PR.](https://github.com/microsoft/Xaml-Controls-Gallery/pull/402#issuecomment-614043525). The reverse navigation connected animation fails sometimes trying to find the source element in the tree. I've disabled the reverse animation temporarily.

If you have selected a control (e.g. StackPanel) in the NavigationView, and then click on a top level group (such as Layout), the app crashes, with an exception being thrown here:

![image](https://user-images.githubusercontent.com/28935693/79475086-13bdb380-7fbc-11ea-8471-490d652e0f17.png)

**Comment by ranjeshj** [comment]
@ojhad can you please investigate this issue. I wonder if we are moving the NavigationViewHeader around.

**Comment by chingucoding** [comment]
Unable to repro this in either of the two WinUI Galleries, closing as stale.
