### ISSUE TITLE
Add StyleCop

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/WinUI-Gallery#414]
**Describe the bug**
Would be great to ensure consistency for samples/helper code to have StyleCop enabled on the project.

**Comment by chingucoding** [comment]
Sounds like a great idea! I've added the StyleCop package to check how much we would need to do and, we got over 4400 warnings :/

Adding this and fixing all those warnings will probably be a lot of work.

**Comment by karkarl** [comment]
Resolving this as dupe of #1279.
