### ISSUE TITLE
App Icon in Store is too small

### ISSUE THREAD

**Issue by kmahone** [microsoft/WinUI-Gallery#473]
The app icon displayed for the app in the Store looks too small. It is a small icon in a large blue tile. It would look better if the icon was a similar size as the tile.

This is true both in the Store app and on the site.

![image](https://user-images.githubusercontent.com/41657372/84710572-5696fb80-af19-11ea-9d57-6234581bc3aa.png)

https://www.microsoft.com/en-us/p/xaml-controls-gallery/9msvh128x2zt?activetab=pivot:overviewtab

**Comment by stmoy** [comment]
I used the built-in asset generator that is included with Visual Studio, and this is what it came up with. Since this was generated by VS, I believe this is the correct size. I'm not opposed to having someone update the assets, but it's not a high pri for me.

**Comment by Spyromaniac31** [comment]
@stmoy  I also think it looks too small compared to the other fluent icons, especially in the Start Menu. I can create an updated assets folder with larger icons.

**Comment by Spyromaniac31** [comment]
@stmoy do you have a file of the icon on its own (preferably vector) that I could use for this?

**Comment by stmoy** [comment]
The SVG and PNG are here: https://1drv.ms/u/s!Aj55ujyRgozspBu7H_OiEiA6YHx9?e=gjpBLr

**Comment by Spyromaniac31** [comment]
[Assets.zip](https://github.com/microsoft/Xaml-Controls-Gallery/files/4944697/Assets.zip)
Here are the updated assets. Let me know if anything's missing.

**Comment by chingucoding** [comment]
@Spyromaniac31 Would you like to create a PR with the updated images? 😃

**Comment by Spyromaniac31** [comment]
All done. Sorry about all the commits. I'm new to GitHub and forgot to link the title in the commit message at first.
