### ISSUE TITLE
AutomationPeer samples

### ISSUE THREAD

**Issue by marcelwgn** [microsoft/WinUI-Gallery#482]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [x] New sample
- [ ] Addition to existing sample
- [ ] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**
N.A.

**Describe the sample**

When writing custom controls, to ensure accessibility, people use AutomationPeer. Given that we also have an "AutomationProperties" page, I think we should also have a page showing how to create automation peers.

**Is your sample request related to a problem? Please describe it**

I've written/updated multiple automationpeers and often the documentation doesn't really tell you what the correct way is to do something, e.g. how to update selection or provide value changes.

**Additional context**

**Comment by chingucoding** [comment]
Cross ref #1022

**Comment by niels9001** [comment]
@chingucoding This is now part of the Accesibility section, right? Should we close it?

**Comment by chingucoding** [comment]
Nope, automation peers are not part of the a11y section yet.

**Comment by karkarl** [comment]
This gallery is more about using WinUI controls. Few people actually create custom controls. For custom AP samples, one can refer to the online docs here: https://learn.microsoft.com/en-us/windows/apps/design/accessibility/custom-automation-peers

Should there be more demand, we can re-open this issue.
