### ISSUE TITLE
NavigationView code sample is incomplete

### ISSUE THREAD

**Issue by YuliKl** [microsoft/WinUI-Gallery#488]
**Describe the bug**

The "Tying selection and focus - Tabs" sample in the NavigationView page is one of two samples with C# code, but this code is annoyingly incomplete. Would be good to add a comment or two explaining what's going on and add the `itemContainer` declaration.

**Expected behavior**

C# code provides a complete template for navigating to different pages on ItemInvoked.

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/86637414-4c04da80-bf8a-11ea-84df-ef12ffc03a88.png)

**Version Info**

Gallery version (found on Settings page): 

1.2.15.0

**Additional context**

**Comment by chingucoding** [comment]
I am not sure what is missing here. Are you refering to the "navigating between items shouldn't be recorded into the Frame's navigation stack" part? Because the sample actually doesn't implement this.

Also I am not quite sure what you mean by "itemContainer" here.

**Comment by chingucoding** [comment]
Closing as stale.
