### ISSUE TITLE
Add XAML Code to sample string helper 

### ISSUE THREAD

**Issue by chingucoding** [microsoft/WinUI-Gallery#496]
In the Debug build, we could add a helper on the settings page, which you can paste the ordinary XAML code and it gives the sample code in the format we currently use for the samples, that is with the special character codes for "<" and ">".

If we include it through conditional compile, it won't affect the store version of the app, yet make it easier to contribute and update XAML sample code.

**Comment by Jay-o-Way** [comment]
Is this still an issue with the latest version?

**Comment by chingucoding** [comment]
@jay-o-way Still would be nice to have IMHO.

**Comment by chingucoding** [comment]
Closing since it's unlikely this will be implemented.
