### ISSUE TITLE
Update Gallery icons when WinUI icons are updated

### ISSUE THREAD

**Issue by stmoy** [microsoft/WinUI-Gallery#504]
**Describe the bug**

https://github.com/microsoft/microsoft-ui-xaml/issues/1204 tracks updating the WinUI icons. If and when WinUI updates the icons in the toolkit, the Xaml Controls Gallery should match to update. 

Proposed icons are found in this conversation: https://github.com/microsoft/Xaml-Controls-Gallery/pull/489#issuecomment-657275399

The XCG should only update the icons after the WinUI icons are agreed-upon. This issue is mainly to track the follow-on work.

**Comment by mdtauk** [comment]
![Light WinUI Gallery Icons](https://user-images.githubusercontent.com/7389110/87737231-4b621480-c7d2-11ea-8702-051af49e5a71.png)
WinUI Control Icons - Light Style

![Dark WinUI Gallery Icons](https://user-images.githubusercontent.com/7389110/87737227-49985100-c7d2-11ea-9b23-9ad7e9b3c902.png)
WinUI Control Icons - Dark Style

[Light and Dark WinUI Gallery Icons.zip](https://github.com/microsoft/Xaml-Controls-Gallery/files/4935144/Light.and.Dark.WinUI.Gallery.Icons.zip)
WinUI Control Icons - Figma File containing both sets

**Comment by Poopooracoocoo** [comment]
Any progress btw?

**Comment by stmoy** [comment]
No updates on this yet; we'd want to change this if/when WinUI updates the other icons. CC: @MarissaMatt for FYI

**Comment by mdtauk** [comment]
It would be good if the Visual Studio SDK team, the Docs team, and the WinUI/Xaml Gallery teams, could all work together on a single set of icons, so there can be consistency across all areas

**Comment by stmoy** [comment]
I agree 👍 

![GIF](https://media.giphy.com/media/3orieQBlWzkKTq4new/giphy.gif)

**Comment by gregwoo-microsoft** [comment]
Hi @mdtauk 😄 I am one of the Microsoft PMs working on the controls gallery. Thank you so much for making the icon set. They look really cool. I'd like to continue this effort of modernizing the icons used in the gallery. Let me know if you would like to contribute!

**Comment by chingucoding** [comment]
Closing since the gallery's icons have all been updated.
