### ISSUE TITLE
Add page for Icons

### ISSUE THREAD

**Issue by YuliKl** [microsoft/WinUI-Gallery#506]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [x] New sample
- [ ] Addition to existing sample
- [ ] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**

**Describe the sample**

New sample page that lists basic usage of [IconElement](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.IconElement?view=winrt-19041) subclasses.

**Is your sample request related to a problem? Please describe it**

I was looking for a quick example of how to specify a custom FontIcon in my app and didn't immediately find anything in XCG.

**Additional context**

**Comment by Jay-o-Way** [comment]
Is released :)
