### ISSUE TITLE
Doc Alignment: ScrollBar Page

### ISSUE THREAD

**Issue by stmoy** [microsoft/WinUI-Gallery#512]
**Describe the bug**

There does not currently exist a page that shows the ScrollBar control. Although this control is mostly used within a ScrollViewer, it'd be useful to have a sample that showed the various ScrollBar states per the documentation.

https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/scroll-controls

**Comment by niels9001** [comment]
The `ScrollView` sample has an extensive sample showing all different variants. Therefore closing this issue as resolved.
