### ISSUE TITLE
ListView with ContextMenu Sample

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/WinUI-Gallery#519]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [x] New sample
- [x] Addition to existing sample
- [ ] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**
ListView

**Describe the sample**
Would be great to show adding a ContextMenu to a ListView. It should also show how to get the context of the item clicked (and not just a general menu).

**Is your sample request related to a problem? Please describe it**
No good resources for best practice in this area, many different solutions on SO with differing implementations. Would be good to show guidance and best-practices in this space here.

**Comment by stmoy** [comment]
We have a sample for this in the Gallery under StandardUICommand - in addition to a ContextMenu, it also includes hover buttons and swipe. This page is linked from the ListView page. 

Does this page cover what you're looking for? Maybe there is a way to increase its discoverability...
