### ISSUE TITLE
Review text color in themes for CommandBarFlyout example

### ISSUE THREAD

**Issue by j0shuams** [microsoft/WinUI-Gallery#545]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] New sample
- [ ] Addition to existing sample
- [X] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**
CommandBarFlyout

**Describe the sample**
When you toggle theme to 'light mode', and click the 3-dot option on the flyout: the 'Resize' and 'Move' options are hard to read. 

**Is your sample request related to a problem? Please describe it**

Not a problem necessarily, perhaps from an accessibility perspective? Just hard to read the options. 

**Additional context**

![Example](https://user-images.githubusercontent.com/70237359/91907446-bb333e00-ec5e-11ea-8820-1d69777aad4e.png)

**Comment by evelynwu-msft** [comment]
This was addressed at some point:
<img width="549" alt="image" src="https://user-images.githubusercontent.com/50890554/212421501-e71f1534-5747-40a8-9fc9-6965b92e5c8d.png">
