### ISSUE TITLE
NavigationView: Flashing underlining

### ISSUE THREAD

**Issue by PapierenTijger** [microsoft/WinUI-Gallery#550]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] New sample
- [ ] Addition to existing sample
- [x] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**
*Tying selection and focus - Tabs* of the NavigationView sample

**Describe the sample**

When I click Item 3 and next Item 4, the line under the tab title flashes very shortly under Item 1. This is not very nice looking and it doesn't happen with e.g. *NavigationView that switches pane orientation based on window width*

**Is your sample request related to a problem? Please describe it**

It doesn't look smooth when Item1 is underlined shortly when clicking another item. This also happens in my app based on that sample. Not only in the Xaml gallery.

**Additional context**

I cannot show a screenvideo made with Gamebar because the Xaml gallery doesn't support gamebar.

**Comment by Poopooracoocoo** [comment]
You could use OBS or ShareX. I used ShareX for this one and then trimmed it using a website:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/51363864/92424023-79f2df00-f1c6-11ea-9dc9-3b78244af81d.gif)

**Comment by PapierenTijger** [comment]
Thanks - good to know, and I'm glad your screenvideo shows the issue too.

**Comment by YuliKl** [comment]
That sample also has a problem with the keyboard focus indicator - keyboard focus is missing from the nav items. Probably some custom code that's causing wonkiness.

**Comment by PapierenTijger** [comment]
Do you mean custom code in the implementation of the WinUI NavigationView or in the sample? Because I have the same issue in my own code. It is possibly, but not necessarily, the same custom code that introduces this behavior, since I have no idea how they implemented the sample apart from what is shown.
Of course maybe they show it wrong, but it is a sample in a gallery, showing users how to do something. I think, they should show the right way of implementing things, so users can copy that.
By the way, I turned off tying between selection and focus, because it introduced other unwanted behavior.

**Comment by chingucoding** [comment]
I think this issue is caused by the SelectionFollowsFocus property on the NavigationView. Disabling that also removes the weird jumps we are currently experiencing.

**Comment by PapierenTijger** [comment]
Indeed, that's the main reason why I removed it from my app. But also because it was responsible for other unwanted behavior: [https://stackoverflow.com/questions/63801972/uwp-settings-buttons-to-isenabled-false-triggers-a-tab-change-in-the-navigati](https://stackoverflow.com/questions/63801972/uwp-settings-buttons-to-isenabled-false-triggers-a-tab-change-in-the-navigati)

**Comment by niels9001** [comment]
With the design refresh of WinUI 2.5 this issue no longer occurs.
