### ISSUE TITLE
Gallery app crashes when rearranging tabs in TabView component

### ISSUE THREAD

**Issue by MrDanixx** [microsoft/WinUI-Gallery#552]
**Describe the bug**
App crashes when user tries to rearrange tabs order in a 'A TabView bound to a collection of MyData objects' section. TabView in other sections are working as expected.

**Steps to reproduce the bug**
1. Go to TabView control
2. Scroll to 'A TabView bound to a collection of MyData objects' section.
3. Try to move the third tab before second one.

**Expected behavior**
Tabs are properly arranged.

**Actual behavior**
App crashes.

**Version Info**

Gallery version (found on Settings page): 
1.2.16.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**
Event_ Viewer log:
Faulting application name: AppUIBasics.exe, version: 1.0.0.0, time stamp: 0x5f0dfb3a
Faulting module name: KERNELBASE.dll, version: 10.0.19041.488, time stamp: 0x5b4a3325
Exception code: 0xc000027b
Fault offset: 0x000000000010b3cc
Faulting process id: 0x39d8
Faulting application start time: 0x01d686109494baf3
Faulting application path: C:\Program Files\WindowsApps\Microsoft.XAMLControlsGallery_1.2.16.0_x64__8wekyb3d8bbwe\AppUIBasics.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 9b42a23b-4ae9-4b35-adc4-06ad90f25962
Faulting package full name: Microsoft.XAMLControlsGallery_1.2.16.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by chingucoding** [comment]
@stmoy Does the store version already have the fix Régis? The crash doesn't appear in freshly built debug versions, so this was probably fixed but not released to the store yet. Respective XCG/WinUI issue: https://github.com/microsoft/microsoft-ui-xaml/issues/2457

**Comment by Poopooracoocoo** [comment]
we're waiting on the winui 2.5 release
