### ISSUE TITLE
RichEditBox file upload crashes Desktop app

### ISSUE THREAD

**Issue by j0shuams** [microsoft/WinUI-Gallery#559]
**Describe the bug**
When you try to upload a file in the RichEditBox page, the app crashes. 
I believe this is an issue with not initializing the file picker* with a window handle.
*The file picker object in `RichEditBoxPage.xaml.cs`. 
See **Additional context** for related links

**Steps to reproduce the bug**

1. Use the `winui3preview` branch
2. Open XamlControlsGallery.Desktop.sln in VS
3. Build and run the app
4. Navigate to Text > RichEditBox > 'A custom editor with RichEditBox'
5. Click the file upload button

**Expected behavior**
A new window should open that allows the user navigation to a RTF file to open.

**Actual behavior**

The app crashes, shuts down.

**Screenshots**

Button that causes the crash:

![image](https://user-images.githubusercontent.com/70237359/93127336-8f628000-f682-11ea-8644-3ea7bda0ce51.png)

Output window after call to `PickSingleFileAsync()`

![image](https://user-images.githubusercontent.com/70237359/93127839-7908f400-f683-11ea-9bc8-8184d90cfbd9.png)

Call stack with breakpoint on `PickSingleFileAsync()`

![image](https://user-images.githubusercontent.com/70237359/93127384-a3a67d00-f682-11ea-8e88-1e624ece8ab9.png)

Output window upon crash:

![image](https://user-images.githubusercontent.com/70237359/93127624-131c6c80-f683-11ea-80c3-89fcf5d4548f.png)

Call stack upon crash:

![image](https://user-images.githubusercontent.com/70237359/93127652-24fe0f80-f683-11ea-8539-8a394b44dde0.png)

**Version Info**

CsWinRT Version used: 0.1.0-prerelease.200629.3
WinUI Version used: 3.0.0-preview2.200713.0

Gallery version (found on Settings page): 

1.2.27.0

Windows 10 version:
- [X] Insider Build (xxxxx)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**
This is very similar to another [issue](https://github.com/microsoft/microsoft-ui-xaml/issues/2716) that was reported 

And a potential solution could be derived from [this cswinrt example](https://github.com/microsoft/CsWinRT/blob/f8637d182f76ee1d5e0b220e5318c7cbb3e58411/UnitTest/TestComponentCSharp_Tests.cs#L1634-L1673)

**Comment by stmoy** [comment]
@j0shuams - thank you for filing this issue!

CC: @MikeHillberg

**Comment by j0shuams** [comment]
@MikeHillberg This no longer repros with XCG on latest reunion bits FWIW
