### ISSUE TITLE
NavigationRootPage.xaml.cs issue - unexpected behaviour

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/WinUI-Gallery#561]
**Describe the bug**

In NavigationRootPage.xaml.cs you have a check for the currently selected item

```cs
            if(args.InvokedItemContainer.IsSelected)
            {
                // Clicked on an item that is already selected,
                // Avoid navigating to the same page again causing movement.
                return;
            }
```

In my own code (built up, not a copy of the sample) - that check always succeeds - the invoked item is always selected, before it's navigated to.

Are you sure about that code?

**Comment by chingucoding** [comment]
Just clicked on an item and the IsSelected property was set to false, so I think it makes sense to have that check.

**Comment by Gavin-Williams** [comment]
![AlwaysTrue](https://user-images.githubusercontent.com/4374176/93544456-7a972c80-f9a1-11ea-9b2f-331dc1aca26a.png)

Always true for me

**Comment by chingucoding** [comment]
Are you using the system XAML NavigationView? The WinUI NavigationView might behave differently in a few areas, and this seems to be one. In the case of the WinUI NavigationView, IsSelected should be false when clicking on an unselected item, and was in the three apps I tested.

**Comment by Gavin-Williams** [comment]
Yes, im using uwp xaml. I will check my code against winui later when I'm at my desk.  See if u could be right, and they behave differently.

**Comment by bpulliam** [comment]
If this is still an issue with the latest versions, please reactivate and give current repro steps and expected/actual results (or just create a new issue).  Thanks!
