### ISSUE TITLE
Add ARM64 Support

### ISSUE THREAD

**Issue by stmoy** [microsoft/WinUI-Gallery#570]
ARM64 is an increasingly important endpoint. This issue tracks the work required to make the Gallery run on ARM64.

Some potential "gotchas":
- XCG depends on some packages that may or may not work on ARM64
- How well does the toolchain support ARM64?

**Comment by chingucoding** [comment]
Regarding the dependencies:
- WinUI: Supports ARM64
- ColorCode.Uwp: Probably supports it?
- Win2D.Uwp: Supports ARM64 with version 1.24.0, we are currently using 1.23.0
- Microsoft.NETCore.UniversalWindowsPlatform: Added support with 6.2.0-Preview1-26502-02, we are currently using 6.1.9
- Microsoft.Xaml.Behaviors.Uwp.Managed: Does NOT support ARM64 right now

So ARM64 is currently blocked on the behaviors SDK not supporting ARM64.

**Comment by stmoy** [comment]
Thanks for this investigation @chingucoding! I wonder if we could see who owns Behaviors and see if they can upgrade to ARM64? CC: @michael-hawker do you recall who owns Behaviors?

Alternatively we could look at removing the Behaviors dependency. Any thoughts on how tightly it's coupled?

**Comment by chingucoding** [comment]
The only reasone we use the behaviors library is to animate the header parallaxing on the "All controls page" and the "What's new page". Beside that, it doesn't seem to be used anywhere else in the XCG. I'm note quite sure how easy it would be to implement the   header scrolling behavior without that library though,

**Comment by michael-hawker** [comment]
@azchohfi is working on the ARM64 story as well, I believe he's been working with the Behaviors folks as well already on this.

ColorCode should be working as we use it in the toolkit and we made the toolkit support ARM64. 🙂

**Comment by azchohfi** [comment]
ARM64 support have been added, we just haven't shipped a new version yet.
https://github.com/microsoft/XamlBehaviors/pull/190

**Comment by azchohfi** [comment]
Btw, Microsoft.Xaml.Behaviors.Uwp.**Managed** already supports ARM64.
We just shipped a new version of Microsoft.Xaml.Behaviors.Uwp.**Native** that supports ARM64:
https://www.nuget.org/packages/Microsoft.Xaml.Behaviors.Uwp.Native/1.0.8
