### ISSUE TITLE
Invalid Window Handle with FileOpenPicker

### ISSUE THREAD

**Issue by j0shuams** [microsoft/WinUI-Gallery#572]
**Describe the bug**

I think this note about `IInitializeWithWindow` [here](https://github.com/microsoft/microsoft-ui-xaml/issues/2716#issuecomment-689988310) is relevant. Note, though, that the `IInitializeWithWindow` interface is not available. So an adjacent solution will be needed.

I encountered this same error with the Upload button as well; opened an issue on XCG a while ago [here](https://github.com/microsoft/Xaml-Controls-Gallery/issues/559), that issue still repros as well.

**Steps to reproduce the bug**

This is using the latest Cswinrt (0.9.0) and the latest WinUI and dotnet RC2.

1. Build and run XamlControlsGallery.Desktop
2. Navigate to Text > RichEditBox > 'A custom editor with RichEditBox'
3. Click the Save button 

**Expected behavior**

File explorer opens to pick a file path to a file.

**Actual behavior**

App crashes.

**Screenshots**

**Callstack**

 	System.Private.CoreLib.dll!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter<System.__Canon>.GetResult()	Unknown
 	[Waiting on Async Operation, double-click or press enter to view Async Call Stacks]	
	XamlControlsGallery.Desktop.dll!AppUIBasics.ControlPages.RichEditBoxPage.SaveButton_Click(object sender, Microsoft.UI.Xaml.RoutedEventArgs e) Line 81	C#

**Output window**
```
...
automationpeer.cpp[404]: Source 'UIA_E_ELEMENTNOTAVAILABLE', Value -2147220991, Message 
'XamlControlsGallery.Desktop.exe' (Win32): Unloaded 'D:\muxl\BuildOutput\obj\x86chk\Samples\XamlControlsGallery\XamlControlsGallery.Desktop.Package\AppX\XamlControlsGallery.Desktop\ColorCode.Core.dll'
automationpeer.cpp[404]: Source 'UIA_E_ELEMENTNOTAVAILABLE', Value -2147220991, Message 
automationpeer.cpp[404]: Source 'UIA_E_ELEMENTNOTAVAILABLE', Value -2147220991, Message 
The thread 0x27e8 has exited with code 0 (0x0).
onecore\shell\lib\calleridentity\callerwindow_twinapi.cpp(116)\twinui.appcore.dll!500F2494: (caller: 500D0BA5) ReturnHr(1) tid(9fd0) 80040155 Interface not registered
    CallContext:[\PickSaveFileAsync\SingleStorageItemOperation] 
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.dll
Invalid window handle. (0x80070578)
```

**Version Info**

Gallery version (found on Settings page): 

Windows 10 version:
- [x] Insider Build (xxxxx)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by Scottj1s** [comment]
Desktop XCG needs to adopt IWindowNative/IInitializeWithWindow to present these dialogs.  Note that there are two C#/WinRT fixes necessary to do this:
https://github.com/microsoft/CsWinRT/pull/491
https://github.com/microsoft/CsWinRT/pull/489
