### ISSUE TITLE
ListView sample empty?

### ISSUE THREAD

**Issue by sdegutis** [microsoft/WinUI-Gallery#600]
**Describe the bug**

ListView sample is empty.

**Steps to reproduce the bug**

https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#xaml-controls-gallery-winui-3-preview-3-branch

**Expected behavior**

Not blank.

**Actual behavior**

Blank.

**Screenshots**

![image](https://user-images.githubusercontent.com/4399718/99805928-d5184a80-2b02-11eb-8c95-0ee7865a66d6.png)
![image](https://user-images.githubusercontent.com/4399718/99805946-dba6c200-2b02-11eb-9d06-afa68fd52bb3.png)

**Version Info**

Latest as of right now.

Gallery version (found on Settings page): 

Latest as of right now.

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [ ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

I'm tired.

**Comment by stmoy** [comment]
What a strange issue. I've seen some lag when loading the ListView, which I'm guessing is related to the data being populated. 

CC: @MikeHillberg @marb2000 @anawishnoff - should I move this to the WinUI repo?

> I'm tired.

![Same](https://media.giphy.com/media/dt5wUdCvLWQghI7xqy/giphy-downsized.gif)

**Comment by anawishnoff** [comment]
Sorry, just seeing this now. @stmoy / @sdegutis I'm not able to repro this after cloning the latest Preview 3 version of XCG. I think this is probably just lag loading the data as Steven mentioned, so not sure if this requires an issue on the WinUI repo, i.e. I don't know if this is a *new* issue.

**Comment by Balkoth** [comment]
Was this ever fixed? To me this looks like `Assets\Contacts.txt` is checked in with wrong line endings, so 

```cs
public async static Task<ObservableCollection<Contact>> GetContactsAsync()
{
    IList<string> lines = await FileLoader.LoadLines("Assets/Contacts.txt");

    ObservableCollection<Contact> contacts = new ObservableCollection<Contact>();

    for (int i = 0; i < lines.Count-2; i += 3)
    {
        contacts.Add(new Contact(lines[i], lines[i + 1], lines[i + 2]));
    }

    return contacts;
}
```

loads only one line and the for loop does nothing...
