### ISSUE TITLE
Page navigation from search results should expand TreeView and select page

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/WinUI-Gallery#613]
Similar to #420 but about search results. 

Windows 10 20H2
XAML Controls Gallery 1.2.17.0

**Comment by hawkerm** [comment]
Same still on 1.2.19.0

**Comment by Poopooracoocoo** [comment]
@stmoy no updates on this issue?

**Comment by Poopooracoocoo** [comment]
It appears that this issue has been resolved/implemented! Always a pleasant surprise when an issue is closed and it was actually fixed. 
#726 has still not been fixed.
