### ISSUE TITLE
Remove workaround for NavigationView visual state on protocol activation

### ISSUE THREAD

**Issue by grochocki** [microsoft/WinUI-Gallery#630]
**Describe the bug**
NavigationView visual state does not always match page navigation, particularly when handling cold launches via protocol activation. A workaround was introduced to correct this issue. If the underlying bug or timing issue that is suspected to be the root cause of this is resolved, consider removing ```EnsureNavigationSelection``` from NavigationRootPage.

**Additional context**
There are some reports (online) of NavigationViewItem selection not always working the first time, which is what I was experiencing when testing protocol activation cold launches. It seems to be timing-related, and possibly impacted by the animation to expand the group. @chingucoding suggested it might be related to microsoft/microsoft-ui-xaml#3149 and/or microsoft/microsoft-ui-xaml#3015.

Additional discussion captured in #624.

**Comment by karkarl** [comment]
This is an WASDK issue, and the bug already exists in the microsoft-ui-xaml repo, so resolving as dupe.
