### ISSUE TITLE
Cannot compile and run Xaml-Controls-Gallery

### ISSUE THREAD

**Issue by sketch34** [microsoft/WinUI-Gallery#649]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] New sample
- [ ] Addition to existing sample
- [x] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**
How to correctly compile / run the Xaml-Controls-Gallery solution.

**Describe the sample**
Compile and run the Xaml-Controls-Gallery solution on Windows 10 with a clean install of latest Visual Studio Community 2019 Preview 16.10.0 Preview 1 and required dependencies following the instructions here: https://docs.microsoft.com/en-au/windows/apps/winui/winui3/

I'm on `winui3preview` branch.

**Is your sample request related to a problem? Please describe it**
I'm having problems compiling and running the solution. I would love a from-scratch / clean install tutorial showing step by step how to get this sample project compiling and running. Currently blocked on this.

1. Had to bump the Microsoft.Net.Compilers.Toolset package up to 3.9.0 because "3.8.X.final" was failing the test ">= 3.8.0-4.20472.6". I'm guessing because ".final" is not numeric and ruins the internal version comparison. Couldn't see any other way around this.

![image](https://user-images.githubusercontent.com/1082293/109756143-769f5400-7c3b-11eb-9e56-825c2d5e4bd3.png)

2. "NuGet package restore failed. Please see Error List window for detailed warnings and errors." - I have NuGet.org package source configured. No additional info is in the Error List window.
2. Which configuration is correct for Win 10 desktop?

![image](https://user-images.githubusercontent.com/1082293/109753959-45bd2000-7c37-11eb-9949-1e081c166917.png)

4. Compilation succeeds but deployment fails for x64, x86, Win32. It is correct that it is trying to copy to an ARM64 output folder when I have not chosen the ARM build configuration? Indeed that output older does not exist.
```
Copying file "C:\Users\jarro\.nuget\packages\microsoft.winui\3.0.0-preview4.210210.4\runtimes\win10-arm64\native\Microsoft.UI.Xaml\Assets\NoiseAsset_256x256_PNG.png" to layout "XamlControlsGallery.Desktop\runtimes\win10-arm64\native\Microsoft.UI.Xaml\Assets\NoiseAsset_256x256_PNG.png"...
DEP1000: Cannot copy file "C:\Users\jarro\.nuget\packages\microsoft.winui\3.0.0-preview4.210210.4\runtimes\win10-arm64\native\Microsoft.UI.Xaml\Assets\NoiseAsset_256x256_PNG.png" to layout "C:\Dev\ABL_180_ThinkAlpha\WinUI3\Xaml-Controls-Gallery\XamlControlsGallery\bin\XamlControlsGallery.Desktop.Package\XamlControlsGallery.Desktop.Package\AppX\XamlControlsGallery.Desktop\runtimes\win10-arm64\native\Microsoft.UI.Xaml\Assets\NoiseAsset_256x256_PNG.png". DirectoryNotFoundException - Could not find a part of the path 'C:\Dev\ABL_180_ThinkAlpha\WinUI3\Xaml-Controls-Gallery\XamlControlsGallery\bin\XamlControlsGallery.Desktop.Package\XamlControlsGallery.Desktop.Package\AppX\XamlControlsGallery.Desktop\runtimes\win10-arm64\native\Microsoft.UI.Xaml\Assets\NoiseAsset_256x256_PNG.png'. [0x80070003]
	DeploymentSucceeded = False
	DeploymentError = Err_LayoutUpdate_CopyFile
	DeploymentHRESULT = 2147942403
	HasSharedCode = False
	Target.Id = 512
	ProjectGuid = {4c7b20d7-5f5c-440e-8da3-b19a328cc8bd}
	Project.TargetPlatformVersion = 10.0.18362.0
	Project.TargetPlatformMinVersion = 10.0.17134.0
Deleting file "vs.appxrecipe" from layout...
DeployAsync: END (Failure, 0:00:00.64)
Deploy: END (Failure, 0:00:00.659)
```

**Additional context**
I'm very experienced with VS C++, but more limited .NET experience, although I have used Nuget and .NET professionally.  Experienced in Qt dev, interested in evalutating WinUI 3 as an alternative for a large windows desktop project. Given the somewhat complex and varied Windows UI historical tech stack (.NET, XAML, Win32, WinRT, UWP) it would be awesome if it was clarified exactly what this repo is and how to compile and run it, which config to use and when etc. Looks very cool, thanks for any help!

**Comment by stmoy** [comment]
@anawishnoff @MikeHillberg - thoughts?

**Comment by rbaprado** [comment]
I just checked out the Winui3 branch. When I try to run it I get  a REGDB_E_CLASSNOTREG exception

**Comment by merojoscimage** [comment]
same issues here: copy failures, nuget update failures, COM exception.  Previously, I had successfully developed and deployed a UWP application ( not for the store, enterprise internal ) , so I've done UWP deployments before.

**Comment by amitpal1979** [comment]
I am trying to build WinUI3 XAML Controls Gallery code in VS2019 and facing compile time issue. Initially, several errors were thrown however updating VS2019 to the latest build resolved all of them except one:

Could not copy the file "C:\Users\Amit.Pal\.nuget\packages\microsoft.web.webview2\1.0.955-prerelease\build\..\runtimes\win-ARM\native_uap\Microsoft.Web.WebView2.Core.dll" because it was not found.

The path mentioned in the error message does contain WebView2.Core.dll however I could not understand the reason behind compiler throwing this error message.

**Comment by michael-hawker** [comment]
@chingucoding @gregwoo-microsoft this still seems to be an issue? I just cloned the repo and Marcel's PR for breadcrumbs #1015 to try out and couldn't deploy that app.

![image](https://user-images.githubusercontent.com/24302614/174191363-6f4195ea-24eb-454c-9654-8038cf6ff20f.png)

```
Creating a new clean layout...
Copying files: Total 78 mb to layout...
Checking whether required frameworks are installed...
Framework: Microsoft.VCLibs.140.00.Debug.UWPDesktop/X64, app package version 14.0.30704.0 is not currently installed.
Installing missing frameworks...
Registering the application to run from layout...
DEP0700: Registration of the app failed. [0x80073CF9] Rejecting a request to register from AppxBundleManifest.xml because the manifest is not in the package root.
3>Deployment of the application to the target device failed
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========
```

I'm on VS 2022 17.2.4, and have other WinUI 3 based projects building/running fine.

I'm assuming I have to run the package project, if I run the other project I get this instead:

![image](https://user-images.githubusercontent.com/24302614/174191836-978b9b5e-ef65-4c4a-93fc-f4d07530a6ff.png)

(I'd also suggest having a different package identity in the repo compared to the store version so you can run both side-by-side, we do this in the toolkit and it's very handy when checking changes in behaviors for samples.)

**Comment by chingucoding** [comment]
@michael-hawker Can you try out if you can build the PR #989 and see if that works? This might be an issue of trying to deploy the app while an app with the same name is installed.

**Comment by michael-hawker** [comment]
@chingucoding, it did prompt me that the app was already installed and if I wanted to overwrite it (or whatever that default dialog is). I clicked 'Yes' as I do with other projects, and then it failed. I'm headed off at the moment, but can try #989 as well later.

**Comment by michael-hawker** [comment]
@chingucoding, whatever is done in #989 seemed to have helped. I was able to run it from that branch, have a comment to add there though. :)
