### ISSUE TITLE
 StandardUICommandPage is content missing in menu item on 17134 build

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/WinUI-Gallery#661]
**Describe the bug**
CalendarViewPage crashes on RS4 with Xaml Parse exception. 

**Steps to reproduce the bug**
1. Launch XCG on RS4 device
2. Click on StandardUICommand page

![image](https://user-images.githubusercontent.com/28935693/112174861-fb82eb00-8bb3-11eb-8ef2-fcba5480f9dd.png)

**Version Info**
- [x] App downloaded from Store 
    - If so, which version? (Found on the Settings page of the app.)
    - 1.2.17.0

Windows 10 version:
- [x ] April 2018 Update (17134)

Device form factor:
- [x ] Desktop

**Comment by bpulliam** [comment]
no repro on 1.2.26
