### ISSUE TITLE
It's possible to navigate to not supported features/controls through Related section.

### ISSUE THREAD

**Issue by bkaankose** [microsoft/WinUI-Gallery#663]
**Describe the bug**
For WinUI 3 version of the app, Reveal is disabled in the Styles menu. However, you can navigate to Reveal page through Acrylic -> Related controls section.

**Steps to reproduce the bug**
1. Go to Styles menu.
2. See 'Reveal' is disabled and can't be clicked.
3. Click on 'Acryclic' and navigate to Acrylic page.
4. Check the 'Related controls' section on the right and see 'Reveal' is there.
5. Click on 'Reveal' and see the empty page.

**Expected behavior**
Reveal should not be visible  in related controls with Acrylic.

**Actual behavior**
Reveal is visible and can be navigatable.

**Screenshots**
![image](https://user-images.githubusercontent.com/12009960/112808463-48196b00-9079-11eb-8228-26e2f1f37bb8.png)
![image](https://user-images.githubusercontent.com/12009960/112808479-4c458880-9079-11eb-992e-362a5c5c537e.png)

**Version Info**
- [X] App downloaded from Store 
    - 1.2.27.0 version
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3preview branch)

**Additional context**

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [X] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by bpulliam** [comment]
No longer applicable to version 1.3.15
