### ISSUE TITLE
UIA Name properties of Group elements in XAML Controls Gallery app are unhelpful

### ISSUE THREAD

**Issue by guybark** [microsoft/WinUI-Gallery#670]
1. Install and run the XAML Controls Gallery app, https://www.microsoft.com/en-us/p/xaml-controls-gallery/9msvh128x2zt?activetab=pivot:overviewtab.
2. Install the Accessibility Insights for Windows tool and point it at the Gallery’s “ListView with Grouped Headers”. The tool can be installed from https://accessibilityinsights.io/docs/en/windows/overview.
3. Consider the names of the Group elements.

Expected: The Group elements' names are helpful to customers.
Actual: The Group elements' names are made up on namespace and class names. The screenshot below shows the unexpected Group names.

Note that each Group element contains another Group element whose name is helpful. I would have thought there'd only be one Group element per group, and its name would be the helpful group name shown visually.

XAML Controls Gallery version 1.2.17.0
Accessibility Insights for Windows version 1.1.1467.1
Windows 10 20H2 19042.

![GroupAIWin](https://user-images.githubusercontent.com/14315611/113791166-e8b1ff80-96f7-11eb-9bfb-2a5ee09696ef.png)

**Comment by evelynwu-msft** [comment]
Verified fix in latest WinUI 3 Gallery app release available in the Store.
