### ISSUE TITLE
Request: Please clean up your stale branches

### ISSUE THREAD

**Issue by kmgallahan** [microsoft/WinUI-Gallery#672]
This repo currently has [20 active branches](https://github.com/microsoft/Xaml-Controls-Gallery/branches/active) and [57 stale branches](https://github.com/microsoft/Xaml-Controls-Gallery/branches/stale).

Please delete your stale branches if no longer needed:

| User | Stale Branches |
| :- | :- |
| @ranjeshj | 22 |
| @stmoy | 7 |
| @anawishnoff | 6 |
| @RBrid | 4 |
| @MarissaMatt | 3 |
| @YuliKl  | 2  |
| @jevansaks  | 2 |
| @micahl | 2 |
| @DmitriyKomin | 2 |
| @gabbybilka | 2 |
| @kaiguo | 1 |
| @LucasHaines | 1 |
| @teaP | 1 |
| @StephenLPeters | 1 |
| @RealTommyKlein | 1 |

**Comment by bpulliam** [comment]
We're down to 5 Active and 7 stale.  Closing
