### ISSUE TITLE
WinUI 3 branch - Theme Mode is not working in the settings

### ISSUE THREAD

**Issue by LeftTwixWand** [microsoft/WinUI-Gallery#685]
**Describe the bug**
I'm testing the winui3 branch - Theme mode is not working in the settings. But in the same time, some controls samples can change a theme of controls. Just like TeachinTip sample:
![image](https://user-images.githubusercontent.com/50652041/115837607-70e71300-a421-11eb-88df-91efac561444.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/50652041/115836359-0ed9de00-a420-11eb-853e-7c303119683d.png)

**Version Info**
- [ ] App downloaded from Store 
    - If so, which version? (Found on the Settings page of the app.)
- [x] App built locally from source 
  - Branch: winui3

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by niels9001** [comment]
With the latest version, this issue has been resolved.
