### ISSUE TITLE
Updated Controls

### ISSUE THREAD

**Issue by zquizmaster** [microsoft/WinUI-Gallery#687]
It would be nice if there were a few hints to what was updated when you release a new version of a control. Having to sift through all the existing information, examples, etc. when we are trying to ascertain what may have changed is sometimes a real burden.

Thanks in advance.

**Comment by chingucoding** [comment]
@anawishnoff @SavoySchuler @ranjeshj FYI

**Comment by anawishnoff** [comment]
Thanks @zquizmaster! I agree, I think it would be really helpful to have some kind of notation next to a sample if it's new or has been updated. I think we've talked about this amongst the team before and it's been agreed upon that this would be a worthy feature to add. I'll make sure that this is added to our list of things to do, and keep you posted once there's an update here.

**Comment by zquizmaster** [comment]
Thanks @anawishnoff.

**Comment by karkarl** [comment]
Resolving this as dupe of #153
