### ISSUE TITLE
Dragging items in a TreeView causes crashes, duplicate items, and other issues

### ISSUE THREAD

**Issue by andrewpratt64** [microsoft/WinUI-Gallery#690]
### Summarized: Dragging items in a Windows TreeView causes issues in both a c++/WinRT project, and in the XAML Controls Gallery

**Describe the bug**
In a c++/WinRT app I was writing I have a tree view (Windows.UI.XamlControls.TreeView, not the one from the Microsoft namespace) and often when I try to drag-and drop nodes around, several issues occur.

I assumed I had a bug in my program at first, but it still happens even when I comment out/return early from any of my event handlers. I tried moving around tree views in the XAML Controls Gallery and experienced crashes as well. I haven't gotten any error messages so far, the controls gallery just immediately terminates.

**Steps to reproduce the bug**
I seem to get problems whenever I try to drag-and-drop content inside a tree view. So far this seems to happen in both a c++/winrt project in Visual Studio, and in the Xaml Controls Gallery app. I haven't been able to tell exactly what causes it, but if you move items around at random (and also moving nodes in/out of other nodes, moving nodes with several layers of children, etc.) it usually only takes about a minute or two.

**Expected behavior**
I expected tree view to not cause errors when dragged, particularly in the Xaml Controls Gallery.

**Actual behavior**
- Nodes end up duplicating
- Nodes move on top of the node I dropped, and would leave an empty space where the node used to be
- Crashes, typically when I drop a node, expand a node containing a node that was dropped, interacting with a duplicate node, etc.
- Any other unintended behavior similar to what I mentioned, or that I haven't noticed

When debugging my program in Visual Studio 2019, errors typically originate from KernelBase.dll, so I'm not able to get much from the debugger other than the disassembly.

**Screenshots**
I can provide screenshots or recordings of the issue in the future if I get any (I didn't think to screenshot some of the non-crashing problems at the time, and I'm not really sure of a good way to capture the control gallery crashing)

**Version Info**

XAML Controls Gallery v1.2.17.0
Visual Studio Community2019 v16.9.4
Windows 10

(More info in attached files)
Visual Studio: [vs_version_info.txt](https://github.com/microsoft/Xaml-Controls-Gallery/files/6437762/vs_version_info.txt)
Project I'm building: [project_misc_info.txt](https://github.com/microsoft/Xaml-Controls-Gallery/files/6437783/project_misc_info.txt)
Windows: [win_version_info.txt](https://github.com/microsoft/Xaml-Controls-Gallery/files/6437764/win_version_info.txt)

**Additional context**
I recently updated Windows 10 the other day. That may be part of the cause, but that was before I started working with tree views so I don't know if it worked prior to updating or not

**Comment by bpulliam** [comment]
I was not able to repro this, but I also know that we have fixed drag and drop issues in general in 1.2.  I'll mark this as fixed in repo (with 1.2).  If this is still an issue with the latest versions, please reactivate and give current repro steps and expected/actual results (or just create a new issue).  Thanks!
