### ISSUE TITLE
DCPP Preview 3 Bug: [MAS1.4.3]:[Color Contrast]:Red color text, in Media-->Sound, is not having minimum luminosity contrast ratio 4.5:1 against the background.

### ISSUE THREAD

**Issue by v-rohra** [microsoft/WinUI-Gallery#695]
Tags
Accessibility, A11yCT, A11yMAS, A11yAuto, AI4D, A11yMediumImpact, MAS4.2.1, ScreenReader,
A11ySev2, XAMLControlsGallery, WinUI, Win32, Wipro

User Impact:
The color contrast ratio for the predicted text for all the card names is less than 4.5:1, So the user with the Low vision might face issue to read this text.

Hardware and Build Details:
UWP or Desktop?: Desktop
OS Version?: 10.0.20246.1
App: WinUI-3 Library
App Version: 1.2.27.0

Repro-Steps:
Launch the WinUI Preview 3 app.
Navigate to Media Tab and invoke it.
Navigate to Sound Card/tile and invoke it
observe the color contrast ratio for the red color text is falling below 4.5:1

Actual Result:
Red color text in Media-->Sound is not having minimum luminosity contrast ratio 4.5:1 against the background.

Expected Result:
Visible text must have a minimum luminosity contrast ratio of 4.5:1 against the background

MAS Reference:
MAS 1.4.3 - Contrast (Minimum)

![image](https://user-images.githubusercontent.com/74231305/118337648-19d8d900-b4c9-11eb-8298-ccb350e26d78.png)

**Comment by v-rohra** [comment]
@chigy  Created issue from internal issue:
Task 30198065: DCPP Preview 3 Bug: WinUI-3 Accessibility:[MAS1.4.3]:[Color Contrast]:Red color text, in Media-->Sound, is not having minimum luminosity contrast ratio 4.5:1 against the background.

**Comment by evelynwu-msft** [comment]
The color of this text has already been updated to no longer have a problematic contrast ratio:
<img width="742" alt="image" src="https://user-images.githubusercontent.com/50890554/212421074-b966c22e-341b-416e-b8af-2cea1b5d5e67.png">
