### ISSUE TITLE
Show in the app what version of WinUI is the app updated for

### ISSUE THREAD

**Issue by JuanMejiaVelez** [microsoft/WinUI-Gallery#700]
**Describe the bug**
As new versions of the app are available, it is not clear against what version of WinUI Nuget Package it is build on. Would be helpful for developers to see the "What's New" applies to what version of WinUI.

**Version Info**
- [X ] App downloaded from Store 
    - If so, which version? (Found on the Settings page of the app.)
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3preview branch)

Windows 10 version:
- [X ] Insider Build (xxxxx)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [ X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by bpulliam** [comment]
Fixed in the latest version
