### ISSUE TITLE
WinUI controls vs. Platform controls

### ISSUE THREAD

**Issue by JuanMejiaVelez** [microsoft/WinUI-Gallery#701]
**Describe the bug**
The XAML Controls Library is a great app to showcase the controls and learn the basics on how to use them, but in some instances it is confusing to mark the difference that certain control exists in the WinUI NuGet package vs the ones that are part of the SDK, specially this confusion is higher when both sources offer a control with the same name as it is the case for ProgressRing and ProgressBar. As we move into porting more a more controls into the NuGet package it would be beneficial that the application states more clearly how to have the control available in projects.

**Comment by chingucoding** [comment]
@gregwoo-microsoft I think if we backport #1023 to the WinUI 2 version we could solve that, but I'm not sure if there is still much benefit to that.

**Comment by niels9001** [comment]
I think this is pretty much resolved with WinUI 3?
