### ISSUE TITLE
NumberBox in GridView - Clear button overlaps with spin button

### ISSUE THREAD

**Issue by KiruyaMomochi** [microsoft/WinUI-Gallery#714]
**Describe the bug**

In "GridView with Layout Customization" sample, the clear button overlaps with spin button.
This makes clicking the clear button impossible.

**Steps to reproduce the bug**

1. Go to "GridView" page
2. Scroll to "GridView with Layout Customization"
3. Click on "Space between columns" number box
4. Then you can see the problem.

**Expected behavior**

The clear button should be on the left of the spin button.

**Actual behavior**

The clear button overlaps with spin button.

**Screenshots**

![image](https://user-images.githubusercontent.com/65301509/123575110-aa624300-d803-11eb-8a56-6e354c691eca.png)

**Version Info**
- [x] App downloaded from Store 
    - Version **1.2.18.0**
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3preview branch)

**Additional context**

Windows 10 version:
- [x] Insider Build (21390) 
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Windows 11 version:
- [x] Leak build (21996)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by bpulliam** [comment]
If this is still an issue with the latest versions, please reactivate and give current repro steps and expected/actual results (or just create a new issue).  Thanks!
