### ISSUE TITLE
Formatting Issue on ProgressBar Page

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/WinUI-Gallery#717]
**Describe the bug**
Formatting issue on ProgressBar Page. Button to increment progress is too narrow causing the buttons to overlap with the displayed progress value. 

**Steps to reproduce the bug**
1. Download XCG.
2. Navigate to ProgressBar page and look at 'A determinate ProgressBar' example.

**Expected behavior**
All parts of progress increment button are visible. 

**Actual behavior**
Overlap between increment arrows and progress value. 

**Screenshots**
![image](https://user-images.githubusercontent.com/34109996/123838714-240c3680-d8c1-11eb-81ce-06627b7b3c41.png)

**Version Info**
- [X] App downloaded from Store 
    - If so, which version? (Found on the Settings page of the app.) - 
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3preview branch): 1.2.19.0

**Additional context**

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by bpulliam** [comment]
Current version looks correct. Please reactivate if you are still seeing this.
