### ISSUE TITLE
Navigation from All Controls or What's New doesn't select page in TreeView

### ISSUE THREAD

**Issue by hawkerm** [microsoft/WinUI-Gallery#726]
**Describe the bug**
Similar to #420 and #613, if you select a page from the What's New or All Controls pages, the TreeView should be expanded and the page selected in the navigation view. This works when you pick a specific control in the search, but doesn't from any other location. So there's logic to do this somewhere in the app, but it's not implemented consistently across the app.

**Steps to reproduce the bug**
1. Go to the What's New or All Controls page.
2. Click on a control sample

**Expected behavior**
Tree should be selected, as if I had picked that from a direct search in the AutoSuggestBox.

**Actual behavior**
Navigation stays on the What's New or All Controls pages even though app is on a different page now.

**Screenshots**

**Version Info**
- [x] App downloaded from Store 
    - If so, which version? 1.2.19.0
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3preview branch)

**Additional context**

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [ ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by niels9001** [comment]
This is resolved in the latest verison.
