### ISSUE TITLE
Null Reference Exception when switch layout on ItemsRepeater

### ISSUE THREAD

**Issue by Wesley-Snipes** [microsoft/WinUI-Gallery#768]
**Describe the bug**
Report NullReferenceException on switch the layout of ItemsRepeater when the items are cleared.

**Steps to reproduce the bug**
1. Go to Layout -> ItemsRepeater
2. Click `Remove Item` for multiple times to clear the items
3. Click `StackLayout - Horizontal`
4. Click `StackLayout - Vertical`

**Expected behavior**
Nothing should change as all the items are removed

**Actual behavior**
Report `NullReferenceException`

**Screenshots**
![image](https://user-images.githubusercontent.com/8622063/133097832-b0d8ed24-9605-41ea-9ae5-1e2476b652dc.png)

**Version Info**
- [x] App built locally from source 
 - Build from master branch

**Additional context**
None

Windows version:
- [x] October 2020 Update (19042)

Device form factor:
- [x] Desktop

**Comment by bpulliam** [comment]
If this is still an issue with the latest versions, please reactivate and give current repro steps and expected/actual results (or just create a new issue).  Thanks!
