### ISSUE TITLE
TabView windowing sample: app crashes when moving last tab of the main window

### ISSUE THREAD

**Issue by manfromarce** [microsoft/WinUI-Gallery#780]
**Describe the bug**
In TabView windowing sample, you can drag tabs outside to move them to a new window.
However, when you drag the last tab out of the first window (in order to merge it with the previously moved tabs) the app crashes. I tried to reproduce the issue in another app and got the error: "Closing main window is not allowed". This is likely a UWP restriction but there might be a workaround (I tried to use ApplicationView.GetForCurrentView().TryConsolidateAsync() but it works but also has some issues).

**Steps to reproduce the bug**
Just drag the last tab of the first window out of the TabView. 

**Expected behavior**
The first window should close properly.

**Version Info**
- [x] App downloaded from Store 
    - XAML Controls Gallery 1.2.21.0

Windows version:
- [ ] Insider Build (xxxxx)
- [x] May 2021 Update (19043)
- [ ] October 2020 Update (19042)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by bpulliam** [comment]
Fixed
