### ISSUE TITLE
In navigation view's compact mode, the top image in what's new page has redundant top padding, and the title has poor contrast

### ISSUE THREAD

**Issue by roxk** [microsoft/WinUI-Gallery#789]
**Describe the bug**
In navigation view's overlay mode, what's new has weird top padding

**Steps to reproduce the bug**
1. Launch the app, make the window as small as possible.
2. Observe in the screenshot below that
  a. the top padding of the image is redundant
  b. The app title and back button, nav view button is a bit hard to read due to poor contrast with the background.
![image](https://user-images.githubusercontent.com/16918354/135873689-ec8cb9c6-34cb-4ae1-aeb6-d661ab5257c3.png)

**Expected behavior**
1. There is no top padding.
2. The app title and back button is easy to read

**Actual behavior**
There is weird padding. The title and back button has poor contrast against the image.

**Version Info**
- [x] App downloaded from Store Version: 1.2.21.0

**Additional context**

Windows version:
- [x] Insider Build (22000.194)
- [ ] May 2021 Update (19043)
- [ ] October 2020 Update (19042)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by gregwoo-microsoft** [comment]
Thank you for filing this @roxk. I was able to repro this and I agree that this needs to be fixed. Thanks for bringing it to our attention.

**Comment by niels9001** [comment]
This was fixed as part of the visual refresh.
