### ISSUE TITLE
Acrylic page does not show the xmlns for "media"

### ISSUE THREAD

**Issue by krisgustafson** [microsoft/WinUI-Gallery#792]
**Describe the bug**
On the WinUI 3 Controls Gallery, the Acrylic page shows good sample code for using the acrylic affect, but never shows the name space reference for "media". So, where is the name space for this?

**Steps to reproduce the bug**

1. Open the WinUI 3 Controls Gallery application.
2. From the right panel (list of control categories) select "Styles"
3. In the Styles-group, select Acrylic.
4. The XAML code references xmlns "media", but nowhere does the page indicate how to reference this library.

**Expected behavior**
The Page xmlns list should include a valid listing for "media", and if possible in which NuGet package needs to be downloaded.

**Actual behavior**
None of the expected information (see "Expected behavior" above" is shown on the gallery page.

**Screenshots**

**Version Info**
- [x] App downloaded from Store 
    - If so, which version? (Found on the Settings page of the app.) Version 1.3.9.0
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3 branch)

**Additional context**

Windows version:
- [ ] Insider Build (xxxxx)
- [x] May 2021 Update (19043) -- 19043.1266
- [ ] October 2020 Update (19042)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by gregwoo-microsoft** [comment]
When you click on the documentation link to see the namespace (in this case: Microsoft.UI.Xaml.Media). Hope this helps @krisgustafson!

@chingucoding we could include the namespace at the top of the samples page. I think this would save people a trip to the documentation page. What do you think?

**Comment by chingucoding** [comment]
Sure we can add this, would you like to do it or should I @gregwoo-microsoft ? Also should we do this for both the WinUI 2 and WinUI 3 version of the app?

**Comment by gregwoo-microsoft** [comment]
I can work on it :) I'll let you know once I get it done.

**Comment by niels9001** [comment]
This is resolved in the latest version.
