### ISSUE TITLE
Settings page styling issue

### ISSUE THREAD

**Issue by calloncampbell** [microsoft/WinUI-Gallery#834]
**Describe the bug**
When comparing XAML Controls Gallery to WinUI3 Controls Gallery, the Setting page styling and/or layout is not matching any of the other pages or the settings page found in the original XAML Controls Gallery app. 

Settings page also missing the Screenshots section unless this is by design.

**Steps to reproduce the bug**
Run WinUI app and go to Settings page.

**Expected behavior**
Controls under the page title should line up with "Settings" title and the section titles should be smaller than the page title.

**Actual behavior**
Controls under the page title are not line up with "Settings" title. Also the section heading fonts are too big.

**Screenshots**
![image](https://user-images.githubusercontent.com/4095080/147178373-f24d419e-0edd-4a96-9e4f-6ac5224d3c52.png)

**Version Info**
- [x] Xaml Controls Gallery - Downloaded from Store
    - If so, which version? (1.2.22.0)
- [x] WinUI 3 Controls Gallery - Downloaded from Store 
    - If so, which version? (1.3.10.0)
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3 branch)

**Additional context**

Windows version:
- [x] Windows 11
- [ ] Insider Build (xxxxx)
- [ ] May 2021 Update (19043)
- [ ] October 2020 Update (19042)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by gregwoo-microsoft** [comment]
Thank you for pointing this out @calloncampbell. I will look into the styling/layout difference. For the screenshot mode, we decided to disable it for now in the WinUI3 CG due to stability issues. We plan on adding it back to the WinUI3 CG once those bugs are dealt with :)
