### ISSUE TITLE
WinUI3 branch crash 100% time upon hitting enter at auto suggestion

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/WinUI-Gallery#838]
**Describe the bug**

The WinUI3 version of Xaml controls gallery crash 100% time upon hitting enter at auto suggestion. Wired thing is, it **doesn't** crash if you click the auto suggestion by mouse.

**Steps to reproduce the bug**

1. Type on the search box, like `button`
2. Hit enter on the first suggestion to go to `Button` page.

**Expected behavior**
Navigate to `Button` page.

**Actual behavior**
Crash

**Screenshots**

![Winui3GalleryCrash](https://user-images.githubusercontent.com/42881734/147918258-2f7dc9a1-7947-4674-bc01-2419cbe798c2.gif)

**Version Info**
- [ ] Xaml Controls Gallery - Downloaded from Store
    - If so, which version? (1.2.x -- Found on the Settings page of the app.)
- [x] WinUI 3 Controls Gallery - Downloaded from Store 
    - If so, which version? (1.3.x -- Found on the Settings page of the app.) `1.3.10.0`
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3 branch)

**Additional context**

Windows version:
Windows 11 

Device form factor:
- [x] Desktop

**Comment by gregwoo-microsoft** [comment]
Hey @HO-COOH! Thanks for filing this bug. Unfortunately I am unable to reproduce it. Maybe try to uninstall/reinstall the app? I am not quite sure what is causing this bug.

**Comment by HO-COOH** [comment]
@gregwoo-microsoft I managed to reproduce it on Windows 10 21H2 19044 with the same version `1.3.10.0`, 100% of the time. Btw, which branch are used to publish the version on store? I want to debug it locally.

**Comment by gregwoo-microsoft** [comment]
I have tried again today and I was able to reproduce it. Thanks for noticing this bug. Right now, the version that is in the store is not yet published on this repo. We need to finalize some changes before we are able to publish it. It will be coming pretty soon 🙂
