### ISSUE TITLE
Crash when scrolling to end of a list in the NavigationView page

### ISSUE THREAD

**Issue by wbokkers** [microsoft/WinUI-Gallery#841]
**Describe the bug**
Crash when scrolling to the end of a list in the NavigationView page.

**Steps to reproduce the bug**

1. On my machine (1920x1080, 125% scaling)
2. Go to xamlcontrolsgallery://item/NavigationView
3. Scroll down **using the touch pad** in some of the examples and see a crash happening
4. Keep trying scrolling up/down **using the touch pad** on some of the list boxes. The crash will happen eventually. (at least on my machine)

**Expected behavior**
No crash

**Actual behavior**
The app crashes without a message

**Version Info**
   
* Xaml Controls Gallery 1.2.22.0 - Downloaded from Store 
* WinUI 3 Controls Gallery 1.3.10.0 - Downloaded from Store 
   
**Additional context**
This is probably related to this WinUI issue: https://github.com/microsoft/microsoft-ui-xaml/issues/6218

Windows version:
Windows 11 (22000.434)

Device form factor:
- [ x] Desktop

**Comment by gregwoo-microsoft** [comment]
Hey @wbokkers! Thanks for filing this bug. I tried to reproduce the crash in the XCG and WinUI 3 CG by scrolling up and down using my touchpad in the NavView control page but I wasn't able to make any app crash. Is there something else I should do to reproduce this bug?

**Comment by wbokkers** [comment]
@gregwoo-microsoft I think this crash is very machine/monitor/dpi dependent. Sometimes I don't get crashes, so I expect there's a timing issue involved as well. I am using a Dell XPS 15 19570. First I focus on one of the example NavigiationView controls and there I do the scrolling. 

At Xelion I have a lot of similar crashes in our app. Not all of our users do encounter the crash. That will make reproducing this issue hard.

It will hopefully be solved, if it is the same issue as this one: https://github.com/microsoft/microsoft-ui-xaml/issues/6218

**Comment by gregwoo-microsoft** [comment]
Thank you for the info @wbokkers. You are right, I think that this is a WinUI bug and by looking at the other issue that you filed, it seems like the team is handling it now. I will leave this bug open until the fix is pushed. Feel free to close this issue when the fix is in :)

**Comment by gregwoo-microsoft** [comment]
Closing this as this is a WinUI bug, not an app bug.
