### ISSUE TITLE
Xaml gallery closes/crashes

### ISSUE THREAD

**Issue by get-flat** [microsoft/WinUI-Gallery#844]
**Steps to reproduce the bug**
1. Start xaml gallery (1.3.10.0)
2. Click on Searchbox
3. type "TabView"
4. press arrow down on your keyboard to select "TabView" item
5. press enter on your keboard
6. app closes/crashes

**Expected behavior**

**Actual behavior**

**Screenshots**

**Version Info**
- [ ] Xaml Controls Gallery - Downloaded from Store
    - If so, which version? (1.2.x -- Found on the Settings page of the app.)
- [x] WinUI 3 Controls Gallery - Downloaded from Store 
    - If so, which version? (1.3.10.0x -- Found on the Settings page of the app.)
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3 branch)

**Additional context**

Windows version:
- [ ] Insider Build (xxxxx)
- [ ] May 2021 Update (19043)
- [ ] October 2020 Update (19042)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [ x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by get-flat** [comment]
Question: This is maybe per design but if so it's extremely interesting design
1. click "what's new"
2. click i.e. "pipspager" from the list
3. it moves you to PipsPager description but still in NavView "what's new" is selected. so clicking on "what's new" causes no action. IMO it might be maybe more user friendly if it can bring you back to the "whats new" page. (you can use back button, btu still)

**Comment by gregwoo-microsoft** [comment]
Thank you for filing this bug @get-flat. We are aware of the bug crash when using the SearchBox. We are trying to fix this and it should be patched in the next update.

Regarding your comment, this is a different bug. I created a second issue (#845) to track it. Let me know what you think.

**Comment by gregwoo-microsoft** [comment]
I'm reopening this as it is still not fixed. When this gets patched, I'll make sure to close this issue :) Have a great weekend @get-flat and thanks again for filing this.
