### ISSUE TITLE
Add C++/Winrt code behind in addition to C#

### ISSUE THREAD

**Issue by odyright** [microsoft/WinUI-Gallery#857]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] New sample
- [*] Addition to existing sample
- [*] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**
WinUI3 Controls Gallery - All controls

**Describe the sample**

![c++](https://user-images.githubusercontent.com/4316506/151851680-232409a9-c039-46f0-b7e4-a20d78b1ddb6.png)

**Comment by gregwoo-microsoft** [comment]
Hey @odyright. Thanks for the suggestion. Right now, we are only providing the C# code but feel free to submit a PR with the C++ code.
