### ISSUE TITLE
Request: buttons with progress ring animation

### ISSUE THREAD

**Issue by alessandrocaseti** [microsoft/WinUI-Gallery#859]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- Addition to existing sample page

**If this is an addition/modification to an existing sample page, which one?**
Standard Button

**Describe the sample**
Microsoft Store's button with progress ring animation integrated

**Is your sample request related to a problem? Please describe it**
No

**Additional context**
![Screenshot (96)](https://user-images.githubusercontent.com/90320229/152033824-dd7f6f46-bf3e-402d-9006-77469f86730e.png)
Fore example, when you check for updates in the MS Store.

**Comment by rmbl-xD** [comment]
Just use 

```
<Button>
   <muxc:ProgressRing IsActive="true" />
</Button>
```

inside a standard Button and bind IsActive to your boolean in the VM?

**Comment by gregwoo-microsoft** [comment]
Thanks for providing the solution @rmbl-xD . I'll close this issue.
