### ISSUE TITLE
TreeViewList demo is missing

### ISSUE THREAD

**Issue by HubKing** [microsoft/WinUI-Gallery#862]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [x] New sample
- [ ] Addition to existing sample
- [ ] Modification to existing sample

**Describe the sample**
I found that WinUI has [TreeViewList class](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.treeviewlist?view=winui-3.0). I wanted to see how it looks or works, but I could not find any other websites that mention this. That Microsoft's page's Example section mentions this "XAML Controls Gallery app", but this app only has `TreeView` which is a different control. Please add a demo for TreeViewList.

**Comment by gregwoo-microsoft** [comment]
Hi @hubking! Thank you for the suggestion. We will keep in mind for future updates :)

**Comment by karkarl** [comment]
Hey @HubKing, TreeViewList is part of an internal implementation for TreeView, and wouldn't be used under normal circumstances. It is exposed to allow for re-templating. Thus it would not make sense to have a control page dedicated for it.
