### ISSUE TITLE
Changing color in the SplitButton control sample

### ISSUE THREAD

**Issue by eduardobragaxz** [microsoft/WinUI-Gallery#865]
**Describe the bug**

The first SplitButton sample breaks the app when you choose a different color from its dropdown.

**Steps to reproduce the bug**

1. Go to Basic Input section, then choose the SplitButton control.
2. Click on the dropdown button of the first SplitButton sample and choose a color.

**Expected behavior**

The color on the left side of the SplitButton should change to the one you chose, and the XAML sample below should probably change too.

**Actual behavior**

The app just breaks and closes.

**Screenshots**

**Version Info**
- [x] Xaml Controls Gallery - Downloaded from Store
    - If so, which version? (1.2.22.0 -- Found on the Settings page of the app.)
- [ ] WinUI 3 Controls Gallery - Downloaded from Store 
    - If so, which version? (1.3.x -- Found on the Settings page of the app.)
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3 branch)

**Additional context**

Windows version:
- [ ] Insider Build (xxxxx)
- [x] Windows 11 (22000)
- [ ] May 2021 Update (19043)
- [ ] October 2020 Update (19042)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by gregwoo-microsoft** [comment]
Thank you @eduardobragaxz for filing this issue. We are aware of the issue and are trying to fix it. I will update this issue once this is fixed. Thanks again for taking the time to file this!
