### ISSUE TITLE
Crash when navigating the menu in compact mode

### ISSUE THREAD

**Issue by lgneves-dev** [microsoft/WinUI-Gallery#869]
**Describe the bug**

When the app is in compact mode and I try to navigate the menu, it crashes!

**Steps to reproduce the bug**

1. Reduce the windows width to compact mode (preferably width < 370px)
2. Navigate to "Basic Input -> Button"
3. Navigate to "Basic Input -> DropDownButton"

**Expected behavior**

Open "DropDownButton" control example.

**Actual behavior**

Crash

**Screenshots**

![WinUI3_Crash](https://user-images.githubusercontent.com/37562573/152943067-cccd641d-27ae-47cd-995a-c118b45890b9.gif)

**Version Info**
- [ ] Xaml Controls Gallery - Downloaded from Store
    - If so, which version? (1.2.x -- Found on the Settings page of the app.)
- [x] WinUI 3 Controls Gallery - Downloaded from Store 
    - If so, which version? (1.3.x -- Found on the Settings page of the app.) `1.3.10.0`
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3 branch)

**Additional context**
This behavior occurs with all menu items when the width of the application is less than 370px.

Windows version:
- [x] Windows 11 (22000.469)
- [ ] Insider Build (xxxxx)
- [ ] May 2021 Update (19043)
- [ ] October 2020 Update (19042)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by gregwoo-microsoft** [comment]
Thansk for filing this issue. I was able to repro this bug. I don't know what is causing this but we will definitely have a look :)
