### ISSUE TITLE
The Settings NavigationViewItem doesn't play the full animation

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/WinUI-Gallery#870]
This issue doesn't repro in the MUXControlsTestApp

https://user-images.githubusercontent.com/7758786/153655341-157143d0-7d44-4306-b654-3e112bad78fe.mp4

**Comment by chingucoding** [comment]
It's worth noting that running extensive tasks on the UI thread while loading the settings page might actually delay the running of animation. Switching displaymode of the NavigationView (unsurprisingly) kills it.
