### ISSUE TITLE
Could not find SDK "Microsoft.UniversalCRT.Debug, Version=10.0.18362.0"

### ISSUE THREAD

**Issue by odyright** [microsoft/WinUI-Gallery#871]
**Describe the bug**
i cloned the project from winui3 branch and when trying to build, i got **Could not find SDK "Microsoft.UniversalCRT.Debug, Version=10.0.18362.0"**

**Steps to reproduce the bug**

**Screenshots**
<img width="1913" alt="image" src="https://user-images.githubusercontent.com/4316506/153728320-3706ae5c-d18a-4771-92bd-e2254b4caa43.png">

**Version Info**
- [ ] Xaml Controls Gallery - Downloaded from Store
    - If so, which version? (1.2.x -- Found on the Settings page of the app.)
- [*] WinUI 3 Controls Gallery - Downloaded from Store 
   1.3.10.0
- [*] App built locally from source 
  - WinUI 3 branch

Windows version:
- [*] 11 (21H2)

Device form factor:
- [*] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by gregwoo-microsoft** [comment]
Thanks for filing this issue. We are in the process of updating the source code for the WinUI 3 Controls Gallery so let's revisit this problem once the branches are updated.

**Comment by bpulliam** [comment]
Fixed

**Comment by ThatMouse** [comment]
I'm getting this error too when I try to build...

**Comment by K3UL** [comment]
Same here, NOT fixed.

**Comment by ThatMouse** [comment]
Thank you @K3UL , changing the target worked!

**Comment by AMArostegui** [comment]
Or rather, tough overkill, install the exact same Windows 10 SDK version (in this case 10.0.18362.1), as the Universal CRT files are part of Windows 10 Sdk

**Comment by octaviordz** [comment]
Faced same issue. Worked around by doing[1] as described in previous comment by @K3UL.

[1]:
> In the WinUIGallery.DesktopWap.Package.wapproj file, in the node <TargetPlatformVersion>, I replaced the version (10.0.18362.0, the one of the error message) with 10.0.19041.0 .

**Comment by octaviordz** [comment]
Hi @AMArostegui how to install the specific version of Windows 10 SDK?
I installed the SDK following instructions on [1] but there is no mention about how to install a specific version.

[1] https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=cs-vs-community%2Ccpp-vs-community%2Cvs-2022-17-1-a%2Cvs-2022-17-1-b

**Comment by AMArostegui** [comment]
> Hi @AMArostegui how to install the specific version of Windows 10 SDK? I installed the SDK following instructions on [1] but there is no mention about how to install a specific version.
> 
> [1] https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=cs-vs-community%2Ccpp-vs-community%2Cvs-2022-17-1-a%2Cvs-2022-17-1-b

In [this link](https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/) you can find specific SDK versions

**Comment by MarkBrainfire** [comment]
I have the same issue.

**Comment by mastersamm-db** [comment]
Good
![Image](https://github.com/user-attachments/assets/f74abf03-467f-475a-a4bc-56335c092b9f)

Credits:
https://stackoverflow.com/a/76456587

**Comment by Jay-o-Way** [comment]
I'm getting the same thing with version 10.0.22621.0 now

> Could not find SDK "Microsoft.UniversalCRT.Debug, Version=10.0.22621.0".
