### ISSUE TITLE
Clicking navigation view -> tab view -> navigation view again crashes in version 1.2.22.0

### ISSUE THREAD

**Issue by roxk** [microsoft/WinUI-Gallery#879]
**Describe the bug**
Navigating specific entries make XCG crash.

**Steps to reproduce the bug**
1. Launch it
2. Click navigation -> navigation view
3. After it finishes loading (idk why it took ~1s on my machine...), click tab view
4. After it finishes loading, click navigation view
5. Observe XCG crash 

I crashes for me 100%. 

Also, for me after (3), the tab view automatically scrolls down to the middle of the page, which is weird 

**Expected behavior**
No crash.

**Actual behavior**
App crashed.

**Screenshots**
https://user-images.githubusercontent.com/16918354/158187311-b93d2a1c-6107-4ddb-9fa9-d3c47f3ad7cc.mp4

**Version Info**
- [x] Xaml Controls Gallery - Downloaded from Store
    - If so, which version? (1.2.x -- Found on the Settings page of the app.)
- [ ] WinUI 3 Controls Gallery - Downloaded from Store 
    - If so, which version? (1.3.x -- Found on the Settings page of the app.)
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3 branch)

**Additional context**
N/A

Windows version:
- [ ] Insider Build (xxxxx)
- [x] Windows 11 21H2 (22000)
- [ ] May 2021 Update (19043)
- [ ] October 2020 Update (19042)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by gregwoo-microsoft** [comment]
Hey @roxk, thanks for filing this issue. I wasn't able to repro this using the latest master branch. We are working on updating the Store app soon so this should fix the issue. I'll close this issue when the Store update is live.
