### ISSUE TITLE
ResourceDictionary with Code-behind

### ISSUE THREAD

**Issue by odyright** [microsoft/WinUI-Gallery#882]
How to add ResourceDictionary with Code-behind?
![Screenshot 2022-03-16 135343](https://user-images.githubusercontent.com/4316506/158605959-6728e7f9-e0d8-4fcb-8c92-17005e861fc1.png)

error : `This Xaml file must have a code-behind class to use {x:Bind}`

**Comment by Usama-Aziz** [comment]
I don't know why a resource dictionary needs to have a code-behind class. But I fixed this issue by adding a **Blank Page template** from this window, and then replacing the Page.xaml contents with myResourceDictionary.xaml contents. Also make sure to change the base-class of this file to ResourceDictionary in code-behind class.

**Comment by gregwoo-microsoft** [comment]
Thanks for providing the solution @Usama-Aziz . I'll close this issue but feel free to reopen it @odyright if you are still having issues.

**Comment by odyright** [comment]
> I don't know why a resource dictionary needs to have a code-behind class. But I fixed this issue by adding a **Blank Page template** from this window, and then replacing the Page.xaml contents with myResourceDictionary.xaml contents. Also make sure to change the base-class of this file to ResourceDictionary in code-behind.

Yeah, that's how i used to do. 
But , i got my answer there : [ResourceDictionary ~ code behind](https://docs.microsoft.com/en-us/windows/apps/design/style/xaml-resource-dictionary?ns-enrollment-type=Collection&ns-enrollment-id=n55dc3jyr5751m)

> All resources need to have a key. Usually that key is a string defined with x:Key="myString". However, there are a few other ways to specify a key:

> [Style](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Style) and [ControlTemplate](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.ControlTemplate) require a TargetType, and will use the TargetType as the key if [x:Key](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/x-key-attribute) is not specified. In this case, the key is the actual Type object, not a string. (See examples below)
[DataTemplate](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.DataTemplate) resources that have a TargetType will use the TargetType as the key if [x:Key](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/x-key-attribute) is not specified. In this case, the key is the actual Type object, not a string.
[x:Name](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/x-name-attribute) can be used instead of [x:Key](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/x-key-attribute). However, **x:Name also generates a code behind field for the resource**. As a result, x:Name is less efficient than x:Key because that field needs to be initialized when the page is loaded.
