### ISSUE TITLE
The application crashes when pressing Enter in the search field.

### ISSUE THREAD

**Issue by aybe** [microsoft/WinUI-Gallery#887]
**Describe the bug**

The application crashes when pressing Enter in the search field.

**Steps to reproduce the bug**

1. Go to 'Search'
2. Type 'icon'
3. Press down key
4. Press Enter key
5. crash

**Expected behavior**

The application shouldn't crash.

**Actual behavior**

The application crashes.

**Version Info**
- [x] WinUI 3 Controls Gallery - Downloaded from Store 
    - If so, which version? (1.3.10.0 -- Found on the Settings page of the app.)

**Additional context**

Windows version:

Microsoft Windows [Version 10.0.19044.1586]

Device form factor:
- [x] Desktop

**Comment by chingucoding** [comment]
I can't repro this, it opens the iconelement page as expected.

**Comment by aybe** [comment]
Here's a video:

https://1drv.ms/v/s!AqAtR29m3cqG2kQBafNXeZALnXfQ?e=eOb8cJ

Here's the crash dump:

https://1drv.ms/u/s!AqAtR29m3cqG2kX7osyuhnmZ8bp1?e=ezUI3T

**Comment by chingucoding** [comment]
That interesting, thanks for the video and dump file!

**Comment by gregwoo-microsoft** [comment]
Thanks for filing this issue @aybe. It seems like this problem is fixed using the latest winui3 branch. We are working to update the Store version which would fix the issue there. I'll make sure to close this issue when we publish the Store update.

**Comment by aybe** [comment]
@gregwoo-microsoft Thank you.
