### ISSUE TITLE
Opening list in ComboBox causes layout side effects

### ISSUE THREAD

**Issue by gwalschlager** [microsoft/WinUI-Gallery#889]
When clicking in a ComboBox in order to display list of choices, any immediately adjacent control on the right "disappears" until a selection is made when it reappears. I assumed the adjacent control didn't disappear, but was just hidden. If I examine the ComboBox ActualWidth property while no list is showing it's 321.6. If I then click the list, the ActualWidth is reduced to 64. After making a selection, the ActualWidth is once again 321.6 so clearly the size is changing and thus causing the adjacent control to be hidden behind the ComboBox while list is open.

Create a Grid with two Auto width columns: column 0 is a ComboBox and column 1 is a ToggleSwitch. Set the source of the ComboBox to show a list of strings each of maybe 20 characters. When run, you can see the ComboBox on left and ToggleSwitch on the right. Now click in ComboBox. List will appear overlaying the combo box, but the ToggleSwitch cannot be seen. It appears to be happening because the width of the ComboBox is being reduced while the list is open, thus affecting the layout.

ComboBox should retain the same width regardless of whether or not list is overlayed or not and thus should not affect adjacent control layout. 

WindowsAppSDK 1.0.0
Windows 11 Home 22000.556
Desktop

**Comment by gregwoo-microsoft** [comment]
For this, I suggest that you create an issue on the WinUI [repository](https://github.com/microsoft/microsoft-ui-xaml).
