### ISSUE TITLE
Cannot add <InfoBadge> control to XAML page

### ISSUE THREAD

**Issue by gwalschlager** [microsoft/WinUI-Gallery#890]
Cannot add <InfoBadge> control to XAML page as I get XAML error and cannot compile it either.

Simply try to add an <InfoBadge> control to a XAML page and XAML indicates "The type InfoBadge was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built".  For some reason, this control gives this error. When you build, you get "XamlCompiler error WMC0001: Unknown type 'InfoBadge' in XML namespace 'http://schemas.microsoft.com/winfx/2006/xaml/presentation'" in the output window, so it's not just a XAML editor issue.

Since this control is in the XAML controls gallery, I assumed it's available in WindowsAppSDK 1.0.0, but apparently not. All other controls I've used work without a hitch. 

WindowsAppSDK 1.0.0
Windows 11 Home 22000.556
Desktop

**Comment by gregwoo-microsoft** [comment]
Hey @gwalschlager ! Thanks for filing this issue. Unfortunately, the InfoBadge control is not yet part of the WInAppSDK. We are actively working on bringing it to the WInAppSDK. For the future, I suggest that you use the WInUI 3 Controls Gallery which uses the WinAppSDK, unlike the XAML Controls Gallery. Hope this helps!
