### ISSUE TITLE
CalendarDatePicker set Language does't work

### ISSUE THREAD

**Issue by jsrgckf** [microsoft/WinUI-Gallery#892]
CalendarDatePicker set Language does't work

<CalendarDatePicker Language="zh" PlaceholderText="请选择出生日期"   Name="dp" DateFormat="{}{year.full}/{month.integer}/{day.integer}"></CalendarDatePicker>

**Screenshots**
![image](https://user-images.githubusercontent.com/27858634/160866410-edb3ed3a-07d8-40f7-b0d8-cee18325f56f.png)

**Version Info**
- [ ] Xaml Controls Gallery - Downloaded from Store
    - If so, which version? (1.2.x -- Found on the Settings page of the app.)

**Additional context**

Windows version:
- [ ] May 2021 Update (19043)

Device form factor:
- [ ] Desktop

**Comment by gregwoo-microsoft** [comment]
This repo is for the WinUI Galleries, for issues with WinUI, you can create an issue on their [repository](https://github.com/microsoft/microsoft-ui-xaml). Have a great weekend!
