### ISSUE TITLE
The Win UI 3.0 Controls Gallery ContentDialog Sample Doesn't Work In Visual Studio 2022

### ISSUE THREAD

**Issue by riccardo10** [microsoft/WinUI-Gallery#896]
**Describe the bug**

I created a new WinUI 3 project in Visual Studio 2022 and copied the ContentDialog sample code and tried to run.

**Steps to reproduce the bug**

1. Copied only the C# code into my brand new Win UI 3.0 project. I did not copy the XAML code.
2. I noticed that VS did not recognise the class ContentDialogContent, as per the sample (the line dialog.Content = new ContentDialogContent()), so eventually I took it out and replaced with a string,
3. I ran the code.

**Expected behavior**

I expected my sample to execute just like the one in the gallery.

**Actual behavior**

It failed with an obscure error message on the line which calls the **dialog.ShowSync()** method.

**Screenshots**

![image](https://user-images.githubusercontent.com/16414608/162177955-4a3527c4-2da5-4bb6-8810-7abec414efed.png)

**Version Info**
- [ ] Xaml Controls Gallery - Downloaded from Store
    - If so, which version? (1.2.x -- Found on the Settings page of the app.)
- [**X**] WinUI 3 Controls Gallery - Downloaded from Store 
    - If so, which version? (1.3.x -- Found on the Settings page of the app.) **1.3.10.0**
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3 branch)

**Additional context**

I searched online and found something on StackOverflow that advised I should add the following line, which I did in my constructor:
`XamlRoot = this.Content.XamlRoot;`

And then it worked!

So, my question is, shouldn't your code sample in the gallery be updated or have I missed something?
I checked on the Microsoft website and found WinUI 3.0 ContentDialog code samples but the line of code was not included.

Windows version:
- [ ] Insider Build (xxxxx)
- [ ] May 2021 Update (19043)
- [**X** ] October 2020 Update (19042)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [**X** ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by gregwoo-microsoft** [comment]
Interesting! Thanks for sharing @riccardo10 . I'll check if we should add your solution to the WinUI Gallery app. Thanks again for sharing your solution.

**Comment by gregwoo-microsoft** [comment]
You are right, we forgot to include this line in the "sample code" but this line was present in the C# code behind the control. I've included this fix in one of my PRs. Thanks @riccardo10 !
