### ISSUE TITLE
WinUI 3 до сих пор не работает на Xbox, Surface Hub и HoloLens? 

### ISSUE THREAD

**Issue by DmitryBorodiy** [microsoft/WinUI-Gallery#902]
I see the absolute incompetence of the current WinUI 3 development team. The new graphics framework still doesn't work on all Windows-based devices (Xbox is the most expected). The new team is so biased in the issue of universality of Windows applications that shields xbox not as part of Windows (Although we know perfectly well that since 2015, Xbox now runs on Windows and uses the UWP as the main platform for apps). As a consequence, we have an absolute incompatibility of WinUI 3 with the UWP. WinAppSdk is just another failure like WinUI 3. So I stayed on the UWP + WinUI 2.

**Comment by gregwoo-microsoft** [comment]
I'm sorry you feel this way. If you would like to submit suggestions on how we can improve WinUI 3, feel free to file an issue on the [WinUI repo ](https://github.com/microsoft/microsoft-ui-xaml)
