### ISSUE TITLE
Please add a VB.net Code

### ISSUE THREAD

**Issue by magus666** [microsoft/WinUI-Gallery#904]
Hi guys please add a vb.net code to use it in our proyects

best regards

**Comment by gregwoo-microsoft** [comment]
Thanks for the suggestion @magus666. We'll keep that in mind :)

**Comment by Nukepayload2** [comment]
I've tried to use VB.NET to write WinUI3 apps. However there're some blocking problems (most of them are in the `Microsoft.WindowsAppSDK` NuGet package ) that prevent compiling XAML files in VB projects. However, the "WinUI-Gallery" project can't run without App.xbf . 

**Major Problems:**
- Missing source files in the `include` folder of `Microsoft.WindowsAppSDK`: `MddBootstrapAutoInitializer.vb` , `UndockedRegFreeWinRT-AutoInitializer.vb` and `WindowsAppSDK-VersionInfo.vb`. One of them is using the "module initializer" language feature, which is not supported by the official VB compiler. So, we can't just generate them with a C#->VB converter. 
- Missing project files in the `buildTransitive` folder of `Microsoft.WindowsAppSDK`: `Microsoft.WindowsAppSDK.Bootstrap.VB.targets` and `Microsoft.WindowsAppSDK.UndockedRegFreeWinRT.VB.targets` . They are used to reference source files in the `include` folder.
- `Microsoft.WindowsAppSDK` has compile-time dependency conflicts with the VB runtime. The full VB runtime depends on `Windows Forms`. `<UseWindowsForms>true</UseWindowsForms>` imports `Microsoft.NET.Sdk.WindowsDesktop.targets`. It references `Microsoft.WinFX.Targets`, which generates errors when processing XAML files . This problem can be skipped by adding `.<ImportFrameworkWinFXTargets>true</ImportFrameworkWinFXTargets>` to `<PropertyGroup>`.
- `Microsoft.UI.Xaml.Markup.Compiler.dll` in `Microsoft.WindowsAppSDK` generates wrong code in `Sub Main`. `WinRT.ComWrappersSupport.InitializeComWrappers` should be called before launching the application. So, we need to define the `DISABLE_XAML_GENERATED_MAIN` constant and write our own `Sub Main`.
- The temporary project in markup compilation can't reference VB runtime correctly. This problem generates compilation errors, such as `BC35000` and `BC30560`. These errors don't disappear even if `<VBRuntime>Default</VBRuntime>` is added to `<PropertyGroup>`
