### ISSUE TITLE
Incorrect attribute for navigationview sample

### ISSUE THREAD

**Issue by RKhanjian** [microsoft/WinUI-Gallery#915]
**Describe the bug**
In the sample code for Data Binding within NavigationView you have:
<NavigationView x:Name="nvSample"
                MenuItemTemplateSelector="{StaticResource selector}"
                MenuItemSource="{x:Bind Categories, Mode=OneWay}" />

It should read MenuItemsSource not MenuItemSource.

**Steps to reproduce the bug**

1. Go to NavigationView within the WINUI 3 Controls Gallery
2. Scroll down to Data Binding

**Expected behavior**
Should read as MenuItemsSource

**Actual behavior**
Currently is MenuItemSource

**Screenshots**

**Version Info**
- [ ] WinUI 3 Controls Gallery - Downloaded from Store 
    - Version 1.3.10.0

Windows version:

Device form factor:
- [ ] Desktop

**Comment by gregwoo-microsoft** [comment]
Thanks for pointing this out. I will make sure that this gets fixed. Thank you @RKhanjian !
