### ISSUE TITLE
NavigationViewItem Icons - Unicode Character

### ISSUE THREAD

**Issue by smbridges91** [microsoft/WinUI-Gallery#916]
In the ControlInfoData.json file it accepts Unicode Characters for Segoe MDL2 icons, but the sub items will not accept the Unicode characters. Please make it possible for "ItemPage.xaml" and "ItemTemplate.xaml" to accept Segoe MDL2 icons so that they can be used within the ControlInfoData.json file.

**Comment by gregwoo-microsoft** [comment]
Thanks for filing this issue @smbridges91. I am not familiar with this but we will keep this in mind for the future. I've labeled it as an "enhancement" to ensure that this doesn't get lost.

**Comment by karkarl** [comment]
We currently have no plans to consume icons within the ItemPage and ItemTemplate. I'm curious why you are making this request. Closing for now as won't fix.
