### ISSUE TITLE
[WinUI 3 Gallery] Visual update bugs

### ISSUE THREAD

**Issue by roxk** [microsoft/WinUI-Gallery#951]
**Describe the bug**
Congratulation on the visual update! I have found several visual bugs in WinUI 3 Gallery, they are all too minor to be a standalone issue and there are too many of them so I have grouped all of them here.

1. The window has weird shadow when content is extended into title bar
![image](https://user-images.githubusercontent.com/16918354/168816836-ebc4abc4-3e80-408a-b98f-234693a7779d.png)
You can see the shadow is dark than usual.

2. Link banner width isn't adaptive
![image](https://user-images.githubusercontent.com/16918354/168817081-5d6845fa-6994-4b39-aede-995b5df810d2.png)
Some part of "Template Studio" is clipped. It happens at basically all breakpoints.

3. Top banner not respecting image aspect ratio
![image](https://user-images.githubusercontent.com/16918354/168817385-d714e517-5a3d-4e4b-8110-0e9d47fde13e.png)
I believe we should use `UniformToFill` instead.

4. Home's title is going out of the banner image
![image](https://user-images.githubusercontent.com/16918354/168817618-76ec6268-8bb0-461e-bd95-0b808f6d211c.png)
Notice how the bottom part of "p" is getting out of the banner. The text should stay within the image. Best to have some bottom padding for the text.

5. Navigation back from control detail page to list page still has the awkward connected animation where the title is animated back into list item, and then the list title would abruptly show up.
**Clicking back in a control detail page, see title is being animated as list item**
![image](https://user-images.githubusercontent.com/16918354/168818301-e1bc6caa-d888-4a2c-9f11-1d033794af08.png)
**Settled down, notice how the title is missing**
![image](https://user-images.githubusercontent.com/16918354/168818483-143ba591-0213-4970-b5d5-5e902ba2f3e6.png)
**And then the title just abruptly shows up**
![image](https://user-images.githubusercontent.com/16918354/168818576-aa351b93-4642-42e9-9e99-92eb1d2e8ee6.png)
**Expected behavior**
The title and list view item doesn't animated, use drill-in's reverse animation as navigating into control detail page is now using drill-in animation. Just like WinUI 2 control gallery.

6. Newly created window doesn't extend content into titlebar, showing 2 app title at once.
![image](https://user-images.githubusercontent.com/16918354/168818966-c012df00-6519-4c98-8b78-696f85eb46f6.png)

7. After creating new window in window -> Create Multiple Windows page, the first window's title bar isn't draggable. All caption button visually react but don't actually do anything upon click either.

8. The design of caption button of the default titlebar when extend into title bar is set to true is different than the system one. The rendering is also bad, notice the 1-pixel "dirt" on the maximize button. System's maximize button also has anti-aliasing "artifact" in the form of extra grey pixels but at least those are at the corner.
![image](https://user-images.githubusercontent.com/16918354/168819626-6c71e08c-cf4d-49a9-8a2c-4f99c85c0bd3.png)

**Version Info**

Gallery version (found on Settings page): 
1.3.11.0

Windows 10 version:
- [x] Insider Build (22621.1)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by gregwoo-microsoft** [comment]
Thank you very much @roxk for taking the time to file this issue and for the kind words. We hope that you like the visual update! Regarding the bugs you mentioned, we are aware of some of them and are actively working to fix them. To give you insights as to why we didn't wait to fix those bugs before updating the apps in the Store: The community had been requesting a Store update for a long time so we wanted to get an update in the Store before the May Community call (May 18th). We didn’t feel like those bugs should block the Store release. This is not to say that those bugs are not important: we want the WinUI Gallery to be the best reflection of the Microsoft Design principles. So as soon as the fixes for those bugs are in, we will push out another Store update. Thanks again for filing this issue and let us know if you find any other bugs :)

**Comment by Jay-o-Way** [comment]
I can add one (possibly related to number 6?)
When clicking the button <kbd>Reset to system title bar</kbd> the colored title bar is _added_
![image](https://user-images.githubusercontent.com/65828559/169135919-a5993589-c329-4fb8-ada6-cbf392116c93.png)

**Comment by webdomlabs** [comment]
When I set navigation style from left to top, I can’t select any menu items. I’ve tried on Windows 10 and Windows 11, same issue. Thanks

**Comment by jp-weber** [comment]
What I also noticed is that the coloured top border is missing and when moving the window there are errors that it drags and the theme background is just visible.
![WinUI3GalleryBug](https://user-images.githubusercontent.com/10946850/169658239-3bbb6d56-a42a-41f8-a511-2dc068d33353.gif)

**Comment by Jay-o-Way** [comment]
Is this still an issue with the latest version?

**Comment by chingucoding** [comment]
Closing since all of the issues seem to be resolved. If you noticed one of them not being fixed, feel free to reopen @roxk!
