### ISSUE TITLE
WinUI 2 Gallery makes all controls's corner radius 8, deviating from fluent design spec

### ISSUE THREAD

**Issue by roxk** [microsoft/WinUI-Gallery#957]
**Describe the bug**
WinUI 2 Gallery is overriding `ControlCornerRadius` in `App.xaml`, causing all controls to have a corner radius of 8.

**Steps to reproduce the bug**
Just launch the app and observe button or check boxes.

**Expected behavior**
`ControlCornerRadius` stays at 4. If some specific control needs to have a corner radius of 8, customize the resources only for that control.

**Actual behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/16918354/169203649-59af6943-2933-4573-b9ad-3a9af43f8a93.png)
You can see WinUI 2's button is rounder, whereas WinUI 3 is "normal", having a corner radius of 4, as defined in WinUI 2.6+ styles.

**Gallery version (found on Settings page):**
WinUI 2 Gallery 1.2.24.0

**Windows 10 version:**
- [x] Insider Build (22621.1)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)
(Shouldn't the template be updated to say Windows 11?)

**Device form factor:**
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**
A UWP community member @yoshiask noticed that the change is introduced in https://github.com/microsoft/WinUI-Gallery/pull/934/commits/4fea127fa3e046e02f7f457fae407dad7ee0c256, and his guess for the bug is, lemme quote:
> Most everything else in that commit is related to the tiles on the home page. I'm guessing they wanted to change the corner radius for those tiles, but instead changed it for literally every control

If this is indeed the case, simply moving the `ControlCornerRadius` override to `HeaderTiles.xaml` should fix it while keeping the desired behavior.

**Comment by dongle-the-gadget** [comment]
Looks like this is fixed.
