### ISSUE TITLE
WebView Page Out of Date

### ISSUE THREAD

**Issue by MSEDGE-CORE** [microsoft/WinUI-Gallery#963]
![image](https://user-images.githubusercontent.com/74437699/169484175-21a6ca08-d5a6-4ad7-9a66-0c64e2a19c45.png)

**Comment by themerror** [comment]
It is not a bug, because WebView uses EdgeHTML, and Microsoft has removed its support.

**Comment by chingucoding** [comment]
@gregwoo-microsoft Should we add some kind of information on the sample page?

**Comment by bpulliam** [comment]
This no longer applies since we have moved to Webview2.
