### ISSUE TITLE
Window can't be closed if a new window was created

### ISSUE THREAD

**Issue by bekir-ozturk** [microsoft/WinUI-Gallery#964]
**Describe the bug**
The close button at the top-right corner of the main app window doesn't work if you first created and closed a window using "Windows/Create Multiple Windows/Create single threaded Multiple top level Windows(MTW)/Create new Window" button.

**Steps to reproduce the bug**

1. Start WinUI 3 Gallery. Let's call the window that has just opened 'main window'.
2. On the left side, go to 'Windows' category.
3. Select 'Create Multiple Windows' page
4. On the page that opened, there will be a 'Create new Window' button.
5. Click the 'Create new Window' button.
6. A new window will pop up.
7. Close the newly opened window by the close button on the top-right.
8. Attempt to also close the 'main window' by clicking the close button on the top-right.

**Expected behavior**

Main window closes.

**Actual behavior**

Nothing happens. Window stays open

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 

1.3.12.0

Windows 10 version:
Windows 10 Pro 21H2 19044.1706

**Additional context**

**Comment by FinnurHrafn** [comment]
I get this same behavior. I get the same Gallery version in Settings. I think this is the old version, for some reason the app store does not give me the latest version.

**Comment by bekir-ozturk** [comment]
Testing with 1.3.16, I can see that the close button works as expected.
