### ISSUE TITLE
WinUI 3 Gallery: Caption buttons appear disabled

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/WinUI-Gallery#966]
**Describe the bug**

Caption buttons appear disabled.
They are also oddly sized. The titlebar isn't the same size as UWP apps.
There are no pressed states.
The hover state doesn't look right.
Pressing and dragging outside of the buttons don't cancel the action.

There is an issue with the top window border. This may be a bug in Windows, but I'd expect a resolution and progress tracking in some way as well as backported fixes.

**Steps to reproduce the bug**
N/A

**Expected behavior**

Consistency with apps like File Explorer, and in terms of size, consistency with UWP apps like WinUI 2 Gallery.

**Actual behavior**

See screenshots and bug description. 

**Screenshots**

![image](https://user-images.githubusercontent.com/51363864/169776665-378d8674-f96d-4e9a-99bd-ee4e66055a6f.png)
Window is active, hovering over close button.
![image](https://user-images.githubusercontent.com/51363864/169777581-f719bf95-3d81-455e-8c35-e800611838bd.png)
Window is active, hovering over maximise button.
![image](https://user-images.githubusercontent.com/51363864/169777591-863e2564-e38b-4c9e-bd40-e3adbace32b7.png)

Compare this to WinUI 2 Gallery: 
![image](https://user-images.githubusercontent.com/51363864/169777453-d2c9ebda-6878-40f4-88d6-701cd4ffe1e4.png)

**Version Info**

Gallery version (found on Settings page): 

1.3.12.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] 21H2 (19044)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by Jaiganeshkumaran** [comment]
This is why a framework should do basic stuff built-in and well. Now every app needs to create a custom title bar even to get the default look that UWP provided out of the box, which enables inconsistency and accessibility issues to go unnoticed.

**Comment by niels9001** [comment]
This is resolved with later versions of WASDK

**Comment by Poopooracoocoo** [comment]
@niels9001 quite a few things were mentioned in this issue. Were all of them addressed in that new version of WASDK?
