### ISSUE TITLE
Sample Area cut-off on right at different DPIs

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/WinUI-Gallery#968]
**Describe the bug**
If you open the WinUI 2 Gallery on a monitor which has a larger DPI, then the sample area/source code area/page itself is cut-off on the right hand side. See screenshot below.

**Steps to reproduce the bug**
1. Make sure DPI is larger ~150+
2. Open app
3. Open a page
4. See issue

**Expected behavior**
Shouldn't be clipped

**Actual behavior**
Page is clipped on right

**Screenshots**
![image](https://user-images.githubusercontent.com/24302614/170100662-3ea9d786-ecc3-48f6-bd4a-ff38e74123fc.png)

**Version Info**

Gallery version (found on Settings page): 1.2.25.0

Windows 10 version:
- [x] Windows 10 21H2
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by chingucoding** [comment]
Are you still able to reproduce this @michael-hawker ?

**Comment by michael-hawker** [comment]
@chingucoding, I believe so, but only on the WinUI 2 app?

**Comment by chingucoding** [comment]
Would you think it's fine to close this issue then given the WinUI 2 version being mostly deprecated/not receiving fixes beyond critical ones?

**Comment by karkarl** [comment]
> Would you think it's fine to close this issue then given the WinUI 2 version being mostly deprecated/not receiving fixes beyond critical ones?

Agreed, closing as won't fix.
