### ISSUE TITLE
Clicking NavigationView from search results crashes the app

### ISSUE THREAD

**Issue by wbokkers** [microsoft/WinUI-Gallery#972]
**Describe the bug**
Searching for 'navigation' and clicking the NavigationView result will crash the app

**Steps to reproduce the bug**

1. Enter 'navigation' in the search box
2. Click on the search icon
3. NavigationView will appear in the search results
4. Click on NavigationView

**Expected behavior**
Opening the NavigationView page

**Actual behavior**
Crash

**Screenshots**
![image](https://user-images.githubusercontent.com/4835617/170671005-5ef5fec7-ac2e-48c0-b59c-a1a2890c7bf5.png)

**Version Info**

Gallery version (found on Settings page): 
- Version: 1.3.12.0

Windows 11 version: 
- Windows 11

Device form factor:
- Desktop

**Comment by dongle-the-gadget** [comment]
It seems as if you try to go to the NavigationView page, from any method, it causes the app to get terribly slow or crash entirely.
(1.3.15.0, Store)

**Comment by l619534951** [comment]
> I'm not able to repro this. Are you building yourself (which branch?) or using the store version? We have a store update on the way, so let us know if that fixes the issue as well.

store version(Version: 1.3.15.0), click "NavigationView" item, and then click another menu item(such as "Pivot" item), repeat many times, WinUI 3 Gallery will crash. I can repro this.

**Comment by Ninzeige** [comment]
I enter the NavigationView twice from search box, and repro this crash(version: 1.3.15.0)

**Comment by chingucoding** [comment]
I was able to reproduce this, the error and stack trace is the same as for #1050 .

**Comment by karkarl** [comment]
Seems it is fixed already. Closing.
