### ISSUE TITLE
WinUI3 Gallery title bar become unresponsive after toggle back from using system titlebar

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/WinUI-Gallery#977]
**Describe the bug**
WinUI3 Gallery title bar become unresponsive after toggle back from using system titlebar

**Steps to reproduce the bug**
1. Go to `Windows` -> `Titlebar` from the left panel
2. Click on `Reset to system titlebar` button, then click `set fallback custom titlebar`
3. Double click on the custom title bar now, the window won't maximize as before. Holding on the left mouse button won't even drag the window.

**Version Info**
WinUI3

Gallery version (found on Settings page): 
`1.3.12.0`

Windows 11

**Comment by gregwoo-microsoft** [comment]
Thanks for filing this bug @HO-COOH . We are aware of this bug and currently working on fixing it. I'll make sure to update this thread once we fix it.

**Comment by HO-COOH** [comment]
Duplicate of #959
