### ISSUE TITLE
WinUI3 API Links bring to 404 Page

### ISSUE THREAD

**Issue by navarone77** [microsoft/WinUI-Gallery#987]
**Any API link brings to 404**

**Steps to reproduce the bug**
1. Open WinUI 3 Gallery 
2. Open page for any control
3. Under Documentation , click _controlname_ - API
4. Microsoft page to 404 Page Not Found

**Example: RichText Block
![Screenshot 2022-06-03 212624](https://user-images.githubusercontent.com/97413201/171971274-e2f452c7-7680-4df8-9cbd-710ae3ad7d0c.png)
404 Link**
![Screenshot 2022-06-03 212708](https://user-images.githubusercontent.com/97413201/171971276-c6e9f891-20d6-46f2-9b42-433e601f6b71.png)

**Version Info**
![Screenshot 2022-06-03 212814](https://user-images.githubusercontent.com/97413201/171971350-4be3c06b-33bc-43f5-9cfe-48f08d2bab4a.png)

Gallery version 
_**1.3.12.0**_

UPDATE 6/6 2022: 

Issue still there on new version  **1.3.14.0**
![image](https://user-images.githubusercontent.com/97413201/172241337-c74ffa3f-e898-4c09-9151-ff6d555cbcee.png)

**Comment by riverar** [comment]
Related: https://github.com/MicrosoftDocs/windows-uwp/issues/3872

**Comment by RossCoeH** [comment]
Agree, it is a similar, but it is not the same. This is for Button Api, not RichTextBlock. Both bugs are valid, they may or may not have the same root cause.

**Comment by navarone77** [comment]
> Agree, it is a similar, but it is not the same. This is for Button Api, not RichTextBlock. Both bugs are valid, they may or may not have the same root cause.

RichTextBlock was an example I showed but they all don't work still on new update. 
![image](https://user-images.githubusercontent.com/97413201/172240618-088604da-71dd-415a-8a02-db370a5b3713.png)

**Comment by kmgallahan** [comment]
@gregwoo-microsoft The WinUI 3 Gallery API reference buttons now link to the WinUI 2.8 doc content, which is an improvement over 404 errors, but they still need to be updated to point at the new WASDK API docs.

https://docs.microsoft.com/windows/windows-app-sdk/api/winrt/
