### ISSUE TITLE
Update "new issue templates"

### ISSUE THREAD

**Issue by gregwoo-microsoft** [microsoft/WinUI-Gallery#992]
**Describe the bug**

Switch to the new issue form template system as mentioned here: https://github.com/microsoft/WinUI-Gallery/pull/984

**Steps to reproduce the bug**

**Expected behavior**

**Actual behavior**

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 

WinUI version:
- [ ] WinUI3 / WinAppSDK 1.1
- [ ] WinUI3 / WinAppSDK 1.0
- [ ] WinUI2

Windows 11 version:
- [ ] Insider Build (xxxxx)
- [ ] Windows 11 22H2 (22621)
- [ ] Windows 11 21H2 (22000)

Windows 10 version:
- [ ] November 2021 Update/21H2 (19044)
- [ ] May 2021 Update/21H1 (19043)
- [ ] October 2020 Update/20H2 (19042)
- [ ] October 2018 Update/RS5 (17763)

Device form factor:
- [ ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by chingucoding** [comment]
I'll work on this.
