### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by liesauer** [microsoft/WinUI-Gallery#993]
![image](https://user-images.githubusercontent.com/8676741/172276006-77767827-1abf-4f06-ad2d-a8082ed95910.png)

![image](https://user-images.githubusercontent.com/8676741/172276099-92acefff-d94e-4178-a710-7b36246da9aa.png)

![image](https://user-images.githubusercontent.com/8676741/172276290-f61fafda-177e-4658-8b6e-c611af9fcc44.png)

you didn't even define `UNPACKAGED` constant, i am wondering how can the unpackaged app run?

**Comment by chingucoding** [comment]
The `UNPACKEGED` constant is being set by the framework IIRC. Can you elaborate what steps you did to get the app to crash?

**Comment by liesauer** [comment]
i did nothing, after temporary fixing the #983 issue by copy tons of wasdk look like dlls from other winui app, relaunch `WinUIGallery.DesktopWap` and you will facing this issue. the app tries to load the bundle resources which would never success since we are launching the unpackaged `WinUIGallery.DesktopWap`.

and there is a another issue
if i launch `WinUIGallery.DesktopWap.Package` in VS, the app launches as expected. but if launch it in explorer, the app crashes as this https://github.com/microsoft/WinUI-Gallery/issues/983#issuecomment-1151788456 descripted.

**Comment by chingucoding** [comment]
Are you still able to reproduce this issue on main? 😅

**Comment by pratikone** [comment]
this is now fixed with support for unpackaged app
