### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by eaddisu00** [microsoft/WinUI-Gallery#995]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] New sample
- [ ] Addition to existing sample
- [ ] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**

**Describe the sample**

**Is your sample request related to a problem? Please describe it**

**Additional context**

**Comment by gregwoo-microsoft** [comment]
Please provide a description of the issue. Closing it for now.
