### ISSUE TITLE
WinUI Gallery crashes on start

### ISSUE THREAD

**Issue by nikolayvpavlov** [microsoft/WinUI-Gallery#996]
**Describe the bug**
When I start the application, nothing happens.  In Windows Application Log the following error is reported:

Faulting application name: WinUIGallery.DesktopWap.exe, version: 1.0.0.0, time stamp: 0x62571213
Faulting module name: CoreMessagingXP.dll, version: 10.0.22621.1000, time stamp: 0xc93a5eeb
Exception code: 0xc000027b
Fault offset: 0x0000000000090e1c
Faulting process id: 0x20b8
Faulting application start time: 0x01d87a56a744175c
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WinUI3ControlsGallery_1.3.13.0_x64__8wekyb3d8bbwe\WinUIGallery.DesktopWap\WinUIGallery.DesktopWap.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.1_1000.516.2156.0_x64__8wekyb3d8bbwe\CoreMessagingXP.dll
Report Id: 5988c9c5-12f9-465c-bac4-f272b57da6ec
Faulting package full name: Microsoft.WinUI3ControlsGallery_1.3.13.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Steps to reproduce the bug**
Install the latest version of WinUI gallery.  Along I have Visual Studio 2022 17.2.3 with Windows App Sdk installed.  Trying to start WinUI gallery causes the app to crash.  I tried repair, reset, uninstall and install, nothing worked.

**Expected behavior**
The application should start normally.

WinUI version:
- [x] WinUI3 / WinAppSDK 1.1

Windows 11 version:
- [ ] Windows 11 22H2 (22621)

Device form factor:
- [ ] Desktop

**Comment by bpulliam** [comment]
I see that the version of the package is 1.3.13.  An update (1.3.14) was released yesterday to resolve this issue. Check the store for the update.
