### ISSUE TITLE
"Fallback custom titlebar" does not drag/drop, controls stop responding

### ISSUE THREAD

**Issue by fredemmott** [microsoft/WinUI-Gallery#999]
**Describe the bug**

* window can not be dragged by custom title bar
* after maximizing the window, controls are un-responsive. No hover effects, clicking minimize/maximize/close does nothing. Can un-maximize by double-clicking the title bar

**Steps to reproduce the bug**

1. Launch WinUI 3 Gallery
2. Open Title Bar page
3. Click "Reset to system title bar"
4. Click " Set fallback custom title bar"

**Expected behavior**

* Window draggable by title bar
* min/max/close controls consistently work

**Actual behavior**

* window is not draggable by title bar
* min/max/close controls do not work while window is maximized

**Version Info**

Gallery version (found on Settings page 1.3.14.0

WinUI version:
- [x] WinUI3 / WinAppSDK 1.1
- [ ] WinUI3 / WinAppSDK 1.0
- [ ] WinUI2

Windows 11 version:
- [ ] Insider Build (xxxxx)
- [ ] Windows 11 22H2 (22621)
- [ ] Windows 11 21H2 (22000)

Windows 10 version:
- [x] November 2021 Update/21H2 (19044)
- [ ] May 2021 Update/21H1 (19043)
- [ ] October 2020 Update/20H2 (19042)
- [ ] October 2018 Update/RS5 (17763)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

Does not appear to be dupe of #959: does not require editing settings, just enabling the fallback custom title bar.

**Comment by dongle-the-gadget** [comment]
This looks more like a WinUI 3 problem than in the gallery itself. One thing to note is that if you don't specify a particular region for dragging (the fallback custom titlebar), the three control buttons become the drag region. (region in red is draggable)

<img width="883" alt="image" src="https://user-images.githubusercontent.com/29563098/172789996-24e979d0-1865-4d10-a23f-7884daa8020c.png">

**Comment by bpulliam** [comment]
Can you check a current build from the 1.2 feature branch and verify that this is fixed?  Thanks!

**Comment by niels9001** [comment]
@bpulliam With the latest version, I think the expected behavior is shown: only the draggable area left of the min/max/close buttons is draggable, which is the default WASDK titlebar behavior. Minimizing/maximizing works as expected. I guess we can close this issue?

**Comment by pratikone** [comment]
Thanks for verifying it. I will close it now.
